/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.Divisors
import Mathlib.RingTheory.ClassGroup.Basic

/-!
# Principal divisors and the class group of a Weierstrass curve

Building on `EllipticCurves.FunctionField.Divisors` (the order-of-vanishing / divisor calculus on
the function field `F(W) = Frac F[W]` of a Weierstrass curve whose coordinate ring is a Dedekind
domain), this file records the two facts that tie the *principal* divisors — those of the form
`divisor W f` for a rational function `f` — to the group structure of the curve, namely the class
group `ClassGroup F[W]` on which Mathlib already builds the elliptic-curve group law
(`WeierstrassCurve.Affine.Point.toClass`).

## Main results

* `WeierstrassCurve.Affine.divisorHom` : the divisor map `f ↦ divisor W f`, packaged as a group
  homomorphism from the unit group `F(W)ˣ` (written multiplicatively) to the (additive) divisor
  group `HeightOneSpectrum F[W] →₀ ℤ` (via `Multiplicative`). This bundles `divisor_mul`,
  `divisor_one`, `divisor_inv` on nonzero arguments.
* `WeierstrassCurve.Affine.divisor_coe_units` / `ord_coe_units` : a **unit** of the coordinate ring
  `F[W]` has trivial divisor (empty zero/pole set) — it is invertible everywhere.
* `WeierstrassCurve.Affine.classGroup_mk_toPrincipalIdeal` : a **principal** fractional ideal
  `⟨f⟩ = spanSingleton f` has trivial class in `ClassGroup F[W]`. This is the concrete
  "principal ⟹ trivial class" tie-in to the class-group group law of the curve; the divisor of a
  rational function is principal, so it is class-trivial.

## Design

Everything here carries the explicit hypothesis `[IsDedekindDomain W.CoordinateRing]`, exactly as in
`Divisors.lean`, decoupling the development from the Part A normality discharge of issue #396.

## References

Silverman, *The Arithmetic of Elliptic Curves*, II.3 (divisors), III.3 (the group law as a subgroup
of the Picard group) and III.8 (the Weil pairing).
-/

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum FractionalIdeal

open scoped nonZeroDivisors

namespace WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W : Affine F} [IsDedekindDomain W.CoordinateRing]

/-- The order of vanishing of a **unit** of the coordinate ring `F[W]` is zero at every closed
point: a unit is invertible everywhere, so it has no zeros or poles. -/
@[simp]
lemma ord_coe_units (u : W.CoordinateRingˣ) (v : HeightOneSpectrum W.CoordinateRing) :
    ord v (algebraMap W.CoordinateRing W.FunctionField (u : W.CoordinateRing)) = 0 := by
  have h1 : spanSingleton W.CoordinateRing⁰
      (algebraMap W.CoordinateRing W.FunctionField (u : W.CoordinateRing)) = 1 := by
    rw [← coeIdeal_span_singleton, Ideal.span_singleton_eq_top.mpr u.isUnit, coeIdeal_top]
  rw [ord, h1, count_one]

/-- The **divisor** of a unit of the coordinate ring `F[W]` is trivial. -/
@[simp]
lemma divisor_coe_units (u : W.CoordinateRingˣ) :
    divisor W (algebraMap W.CoordinateRing W.FunctionField (u : W.CoordinateRing)) = 0 := by
  ext v
  simp

variable (W) in
/-- The **divisor homomorphism**: `f ↦ divisor W f`, as a group homomorphism from the unit group
`F(W)ˣ` (multiplicative) to the divisor group `HeightOneSpectrum F[W] →₀ ℤ` (additive, seen through
`Multiplicative`). This packages the additivity `divisor_mul` together with `divisor_one`. -/
noncomputable def divisorHom :
    W.FunctionFieldˣ →* Multiplicative (HeightOneSpectrum W.CoordinateRing →₀ ℤ) where
  toFun f := Multiplicative.ofAdd (divisor W (f : W.FunctionField))
  map_one' := by
    simp only [Units.val_one, divisor_one]
    rfl
  map_mul' f g := by
    simp only [Units.val_mul]
    rw [divisor_mul (Units.ne_zero f) (Units.ne_zero g)]
    rfl

@[simp]
lemma divisorHom_apply (f : W.FunctionFieldˣ) :
    divisorHom W f = Multiplicative.ofAdd (divisor W (f : W.FunctionField)) :=
  rfl

/-- A **principal** fractional ideal `spanSingleton ⟨x⟩` of the coordinate ring — the fractional
ideal generated by a single nonzero element `x` of the function field — has trivial class in
`ClassGroup F[W]`. Equivalently, the class-group map kills the range of `toPrincipalIdeal`.

Since the fractional ideal `⟨f⟩` underlying the divisor `divisor W f` of any rational function `f`
is principal, this says every principal divisor is class-trivial — the affine incarnation of
"the group law lives in the degree-zero part of the Picard group". -/
lemma classGroup_mk_toPrincipalIdeal (x : W.FunctionFieldˣ) :
    ClassGroup.mk W.FunctionField
      (toPrincipalIdeal W.CoordinateRing W.FunctionField x) = 1 := by
  rw [ClassGroup.mk_def]
  refine (QuotientGroup.eq_one_iff _).mpr ?_
  rw [canonicalEquiv_self, RingEquiv.coe_monoidHom_refl, Units.map_id, MonoidHom.id_apply]
  exact MonoidHom.mem_range.mpr ⟨x, rfl⟩

end WeierstrassCurve.Affine
