/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.Finiteness.Ideal
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import EllipticCurves.FunctionField.LocalRingTaylor

/-!
# The Nakayama step: the maximal ideal of the local ring at a nonsingular point is principal

This file supplies the **milestone lemma** of the normality crux (issue #396 Part A /
milestone #469):

> for `W : WeierstrassCurve.Affine F` over a field `F` and a nonsingular point `(x, y)`, the
> maximal ideal of the local ring `Localization.AtPrime (XYIdeal W x (C y))` is principal.

It is the "Jacobian–uniformizer" lemma: at a nonsingular point one of the two partial derivatives
is nonzero, and combined with the first-order (Taylor) expansion of `W.polynomial` this collapses
the two generators `X - x`, `Y - y` of the maximal ideal to a single uniformizer.

## The mathematics

The two previous bricks provide the inputs:

* `taylor_cotangent_mem_sq` (`LocalRingTaylor.lean`, #186) — the **cotangent relation**
  `W_X(x, y)·[X - x] + W_Y(x, y)·[Y - y] ∈ ⟨X - x, Y - y⟩²`, a linear relation among the two
  maximal-ideal generators in `m/m²` with the *evaluated* partials `W_X(x, y)`, `W_Y(x, y)` as
  scalar coefficients.
* nonsingularity — `W.Nonsingular x y` unfolds to `W.Equation x y ∧ (W_X(x, y) ≠ 0 ∨
  W_Y(x, y) ≠ 0)`, i.e. one of the two *scalar* coefficients above is nonzero, hence its image
  `mk W (C (C ·))` in `F[W]` is a **unit** (image of a nonzero field element), and remains a unit
  in the localization.

The heart is a `Nakayama` argument, isolated here as the ring-theoretic lemma
`isPrincipal_maximalIdeal_of_span_pair_relation`, which needs no elliptic-curve input at all:

> if a prime ideal `P` of a commutative ring `A` is generated by two elements `a`, `b`, and there
> is a relation `ca·a + cb·b ∈ P²` whose coefficient `cb` becomes a unit in `Localization.AtPrime
> P`, then the maximal ideal of `Localization.AtPrime P` is principal (generated by the image of
> `a`).

Indeed the extended ideal `m = P · A_P = ⟨a, b⟩` maps the relation into `m²`; since `cb` is a unit
there, `b ∈ ⟨a⟩ + m²`, so `m = ⟨a⟩ + m·m`, whence Nakayama's lemma
(`Submodule.le_of_le_smul_of_le_jacobson_bot`, using `m ≤ jacobson ⊥` for the local ring `A_P`)
forces `m = ⟨a⟩`.

## Main statements

* `isPrincipal_maximalIdeal_of_span_pair_relation` — the general Nakayama lemma above.
* `maximalIdeal_isPrincipal_of_nonsingular` — the milestone: `(maximalIdeal (Localization.AtPrime
  (XYIdeal W x (C y)))).IsPrincipal` at a nonsingular point.

## Out of scope (the remaining #469 work)

The milestone lemma is the whole deliverable of `#469`.  The mechanical downstream assembly remains
for a follow-on: `principal ⇒ IsIntegrallyClosed ⇒ IsDedekindDomain` via
`tfae_of_isNoetherianRing_of_isLocalRing_of_isDomain`, the `of_localization_maximal` step, and the
`F` vs `F̄` closed-point classification / integral descent (see `#469`).

## References

* [J. Silverman, *The arithmetic of elliptic curves*][silverman2009], II.1–II.3, III.8.
-/

open Polynomial
open scoped Polynomial.Bivariate

namespace WeierstrassCurve.Affine

namespace CoordinateRing

/-- **The Nakayama step, ring-theoretically.**

Let `P` be a prime ideal of a commutative ring `A` generated by two elements `a`, `b`
(`hP : P = ⟨a, b⟩`).  Suppose there is a relation `ca·a + cb·b ∈ P²` whose coefficient `cb` becomes
a **unit** in the localization `Localization.AtPrime P`.  Then the maximal ideal of
`Localization.AtPrime P` is **principal**, generated by the image of `a`.

The extended ideal `m = P · A_P` equals `⟨aₚ, bₚ⟩` (images of `a`, `b`); the relation maps into
`m²`, and inverting `cb` shows `bₚ ∈ ⟨aₚ⟩ + m²`, so `m = ⟨aₚ⟩ + m·m`.  As `A_P` is local,
`m ≤ jacobson ⊥`, and `m` is finitely generated, so Nakayama's lemma collapses `m` to `⟨aₚ⟩`. -/
theorem isPrincipal_maximalIdeal_of_span_pair_relation {A : Type*} [CommRing A] (P : Ideal A)
    [P.IsPrime] {a b ca cb : A} (hP : P = Ideal.span {a, b}) (hrel : ca * a + cb * b ∈ P ^ 2)
    (hu : IsUnit (algebraMap A (Localization.AtPrime P) cb)) :
    (IsLocalRing.maximalIdeal (Localization.AtPrime P)).IsPrincipal := by
  -- The extended ideal is the maximal ideal, generated by the images of `a` and `b`.
  have hmap : Ideal.map (algebraMap A (Localization.AtPrime P)) P =
      IsLocalRing.maximalIdeal (Localization.AtPrime P) :=
    Localization.AtPrime.map_eq_maximalIdeal
  have hm_span : IsLocalRing.maximalIdeal (Localization.AtPrime P) =
      Ideal.span {algebraMap A (Localization.AtPrime P) a,
        algebraMap A (Localization.AtPrime P) b} := by
    rw [← hmap, congrArg (Ideal.map (algebraMap A (Localization.AtPrime P))) hP,
      Ideal.map_span, Set.image_pair]
  have ha_mem : algebraMap A (Localization.AtPrime P) a ∈
      IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
    rw [hm_span]; exact Ideal.subset_span (Set.mem_insert _ _)
  -- The mapped cotangent relation lands in `m · m`.
  have hz : algebraMap A (Localization.AtPrime P) ca * algebraMap A (Localization.AtPrime P) a +
      algebraMap A (Localization.AtPrime P) cb * algebraMap A (Localization.AtPrime P) b ∈
      IsLocalRing.maximalIdeal (Localization.AtPrime P) *
        IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
    have h0 := Ideal.mem_map_of_mem (algebraMap A (Localization.AtPrime P)) hrel
    rw [pow_two, Ideal.map_mul, hmap, map_add, map_mul, map_mul] at h0
    exact h0
  -- Invert `cb`: the image of `b` lies in `⟨aₚ⟩ + m · m`.
  obtain ⟨v, hv⟩ := hu
  have hbinv : algebraMap A (Localization.AtPrime P) cb * (↑v⁻¹ : Localization.AtPrime P) = 1 := by
    rw [← hv]; exact v.mul_inv
  have hb_sup : algebraMap A (Localization.AtPrime P) b ∈
      Ideal.span {algebraMap A (Localization.AtPrime P) a} ⊔
        IsLocalRing.maximalIdeal (Localization.AtPrime P) *
          IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
    have hbeq : algebraMap A (Localization.AtPrime P) b =
        (↑v⁻¹ : Localization.AtPrime P) *
            (algebraMap A (Localization.AtPrime P) ca * algebraMap A (Localization.AtPrime P) a +
              algebraMap A (Localization.AtPrime P) cb * algebraMap A (Localization.AtPrime P) b) -
          (↑v⁻¹ : Localization.AtPrime P) * algebraMap A (Localization.AtPrime P) ca *
            algebraMap A (Localization.AtPrime P) a := by
      have key : (↑v⁻¹ : Localization.AtPrime P) *
            (algebraMap A (Localization.AtPrime P) ca * algebraMap A (Localization.AtPrime P) a +
              algebraMap A (Localization.AtPrime P) cb * algebraMap A (Localization.AtPrime P) b) -
          (↑v⁻¹ : Localization.AtPrime P) * algebraMap A (Localization.AtPrime P) ca *
            algebraMap A (Localization.AtPrime P) a =
          ((↑v⁻¹ : Localization.AtPrime P) * algebraMap A (Localization.AtPrime P) cb) *
            algebraMap A (Localization.AtPrime P) b := by ring
      rw [key, mul_comm (↑v⁻¹ : Localization.AtPrime P) (algebraMap A (Localization.AtPrime P) cb),
        hbinv, one_mul]
    rw [hbeq]
    refine sub_mem (Ideal.mem_sup_right ?_) (Ideal.mem_sup_left ?_)
    · exact Ideal.mul_mem_left _ _ hz
    · exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)
  -- Nakayama: `m ≤ ⟨aₚ⟩`.
  have hPfg : P.FG := by
    rw [hP]; exact Submodule.fg_span ((Set.finite_singleton b).insert a)
  have hmfg : (IsLocalRing.maximalIdeal (Localization.AtPrime P)).FG := by
    rw [← hmap]; exact hPfg.map _
  have hjac : IsLocalRing.maximalIdeal (Localization.AtPrime P) ≤ Ideal.jacobson ⊥ :=
    (IsLocalRing.jacobson_eq_maximalIdeal ⊥ bot_ne_top).ge
  have hNN : IsLocalRing.maximalIdeal (Localization.AtPrime P) ≤
      Ideal.span {algebraMap A (Localization.AtPrime P) a} ⊔
        IsLocalRing.maximalIdeal (Localization.AtPrime P) •
          IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
    conv_lhs => rw [hm_span]
    rw [Ideal.span_le]
    intro t ht
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ht
    rcases ht with rfl | rfl
    · exact Ideal.mem_sup_left (Ideal.mem_span_singleton_self _)
    · rw [Ideal.smul_eq_mul]; exact hb_sup
  have hle : IsLocalRing.maximalIdeal (Localization.AtPrime P) ≤
      Ideal.span {algebraMap A (Localization.AtPrime P) a} :=
    Submodule.le_of_le_smul_of_le_jacobson_bot hmfg hjac hNN
  have hge : Ideal.span {algebraMap A (Localization.AtPrime P) a} ≤
      IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
    rw [Ideal.span_le, Set.singleton_subset_iff]; exact ha_mem
  exact ⟨⟨_, le_antisymm hle hge⟩⟩

variable {F : Type*} [Field F] {W : Affine F} {x y : F}

/-- **A nonzero scalar becomes a unit in the coordinate ring.**
For `c : F` with `c ≠ 0`, the class `mk W (C (C c))` of the constant polynomial is a unit in
`F[W]`, being the image of the field unit `c` under the ring homomorphism `mk W ∘ C ∘ C`. -/
theorem isUnit_mk_CC {c : F} (hc : c ≠ 0) : IsUnit (mk W (C (C c))) :=
  (isUnit_iff_ne_zero.mpr hc).map
    ((mk W).comp ((C : F[X] →+* F[X][Y]).comp (C : F →+* F[X])))

/-- **The maximal ideal of the local ring at a nonsingular point is principal** (milestone #469).

For a nonsingular point `(x, y)` on `W`, the maximal ideal of the local ring
`Localization.AtPrime (XYIdeal W x (C y))` at the closed point `⟨X - x, Y - y⟩` is principal.
This is the Jacobian–uniformizer lemma: nonsingularity makes one of the two evaluated partial
derivatives a unit, and the cotangent relation `taylor_cotangent_mem_sq` then collapses the two
generators `X - x`, `Y - y` to a single uniformizer via Nakayama
(`isPrincipal_maximalIdeal_of_span_pair_relation`). -/
theorem maximalIdeal_isPrincipal_of_nonsingular (h : W.Nonsingular x y)
    [(XYIdeal W x (C y)).IsPrime] :
    (IsLocalRing.maximalIdeal (Localization.AtPrime (XYIdeal W x (C y)))).IsPrincipal := by
  rcases h.2 with hX | hY
  · -- `W_X(x, y) ≠ 0`: keep the uniformizer `Y - y`.
    refine isPrincipal_maximalIdeal_of_span_pair_relation (XYIdeal W x (C y))
      (a := YClass W (C y)) (b := XClass W x)
      (ca := mk W (C (C (W.polynomialY.evalEval x y))))
      (cb := mk W (C (C (W.polynomialX.evalEval x y)))) ?_ ?_ ?_
    · change Ideal.span {XClass W x, YClass W (C y)} = Ideal.span {YClass W (C y), XClass W x}
      rw [Set.pair_comm]
    · rw [add_comm]; exact taylor_cotangent_mem_sq h.1
    · exact (isUnit_mk_CC hX).map (algebraMap W.CoordinateRing _)
  · -- `W_Y(x, y) ≠ 0`: keep the uniformizer `X - x`.
    refine isPrincipal_maximalIdeal_of_span_pair_relation (XYIdeal W x (C y))
      (a := XClass W x) (b := YClass W (C y))
      (ca := mk W (C (C (W.polynomialX.evalEval x y))))
      (cb := mk W (C (C (W.polynomialY.evalEval x y)))) rfl ?_ ?_
    · exact taylor_cotangent_mem_sq h.1
    · exact (isUnit_mk_CC hY).map (algebraMap W.CoordinateRing _)

end CoordinateRing

end WeierstrassCurve.Affine
