/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Nakayama
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import EllipticCurves.FunctionField.LocalRingTaylor
import EllipticCurves.Torsion.CoordinateRingDedekind

/-!
# The Jacobian–uniformizer lemma: the maximal ideal at a nonsingular point is principal

This file supplies the **Nakayama heart** of the normality crux (issue #396 Part A /
milestone #469): at a nonsingular affine point the maximal ideal of the local ring at the
corresponding closed point is *principal* — the local ring is a discrete valuation ring, which is
the local-normality input for `IsIntegrallyClosed W.CoordinateRing`.

## The mathematics

The load-bearing input is the **cotangent relation** already established in `LocalRingTaylor.lean`
(`taylor_cotangent_mem_sq`, the Taylor/first-order brick, #186):
```
W_X(x, y)·[X - x] + W_Y(x, y)·[Y - y]  ∈  ⟨X - x, Y - y⟩²     in F[W].
```
Localising at the closed point `⟨X - x, Y - y⟩`, its maximal ideal `m` is generated by the images
`X - x`, `Y - y`, and the relation says the two generators are linearly dependent modulo `m²`,
with scalar coefficients `W_X(x, y)`, `W_Y(x, y)`.  At a nonsingular point one of these partial
derivatives is nonzero — a nonzero *constant* of the base field `F`, hence a unit of `F[W]`
(`isUnit_mk_CC`) — so one generator is expressible through the other modulo `m²`.  A
Noetherian-local Nakayama step (`maximalIdeal_isPrincipal_of_span_pair`) then collapses `m` to a
single uniformizer.

## Main statements

* `maximalIdeal_isPrincipal_of_span_pair` — the ring-level Nakayama step: in a Noetherian local
  ring, if the maximal ideal is `⟨a, b⟩` with `b ∈ ⟨a⟩ + m²`, then it is principal.
* `isUnit_mk_CC` — a nonzero constant of `F` is a unit in `F[W]`.
* `maximalIdeal_isPrincipal_of_nonsingular` — **the `#469` milestone**: at a nonsingular point the
  maximal ideal of `Localization.AtPrime ⟨X - x, Y - y⟩` is principal (the Jacobian–uniformizer
  lemma).

## Out of scope *here* — and the next rung has since been built

⚠️ **This section used to be headed `## Out of scope (the remaining #469 work)`.**  Its single
bullet is still out of scope for this file and is no longer out of scope for the project:

* The passage `principal maximal ideal ⇒ IsIntegrallyClosed ⇒ IsDedekindDomain` via
  `IsIntegrallyClosed.of_localization_maximal` is
  `EllipticCurves.FunctionField.LocalRingNormal`
  (`isIntegrallyClosed_localization_of_nonsingular` and
  `isIntegrallyClosed_of_maximalIdeal_classification`), which consumes
  `maximalIdeal_isPrincipal_of_nonsingular` below.  The `F` vs `F̄` closed-point classification is
  `exists_equation_and_eq_XYIdeal_of_isMaximal`
  (`EllipticCurves.FunctionField.CoordinateRingNormalAlgClosed`) — and the sentence that follows it
  here, that over an algebraically closed base every maximal ideal is `⟨X - x, Y - y⟩` so that this
  lemma discharges them all, is exactly the argument that file runs.  The integral descent to a
  general base field is `EllipticCurves.FunctionField.CoordinateRingNormalGeneral`.

⚠️ **The whole `#396` / `#469` ladder was written and closed inside one afternoon, and none of
its five rungs was revisited.**  Pickaxe dating (`git log --format=%ci -S'<clause>' -- <file>`),
all on 2026-08-16: `LocalRingUnit` predicted the Taylor brick and the Nakayama step at 10:40;
`LocalRingTaylor` landed the first at 11:24 and predicted the second; `LocalRingUniformizer` landed
it at 11:48 and predicted the passage to `IsIntegrallyClosed`; `LocalRingNormal` landed that at
12:30 and predicted the maximal-ideal classification; `CoordinateRingNormalAlgClosed` landed it at
12:48 and predicted the general-base-field descent, which `CoordinateRingNormalGeneral` registered
as a **global instance** at 13:59.  Three hours and nineteen minutes, five files, five surviving
predictions.

## References

* [J. Silverman, *The arithmetic of elliptic curves*][silverman2009], II.1–II.3, III.8.
-/

open Polynomial
open scoped Polynomial.Bivariate

namespace WeierstrassCurve.Affine

namespace CoordinateRing

variable {F : Type*} [Field F] (W : Affine F) (x y : F)

/-- **Nakayama uniformizer criterion.**  In a Noetherian local ring `R`, if the maximal ideal is
generated by two elements `a`, `b` and the second lies in `⟨a⟩ + m²`, then the maximal ideal is
principal (generated by `a`).  This is the ring-level Nakayama step that turns the localised
cotangent relation into principality. -/
theorem maximalIdeal_isPrincipal_of_span_pair {R : Type*} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] {a b : R}
    (hm : IsLocalRing.maximalIdeal R = Ideal.span {a, b})
    (hb : b ∈ Ideal.span {a} ⊔
        IsLocalRing.maximalIdeal R * IsLocalRing.maximalIdeal R) :
    (IsLocalRing.maximalIdeal R).IsPrincipal := by
  have ha : a ∈ IsLocalRing.maximalIdeal R :=
    hm ▸ Ideal.subset_span (Set.mem_insert _ _)
  refine ⟨a, le_antisymm ?_ ?_⟩
  · refine Submodule.le_of_le_smul_of_le_jacobson_bot (I := IsLocalRing.maximalIdeal R)
      (IsNoetherian.noetherian _) ?_ ?_
    · exact le_of_eq (IsLocalRing.jacobson_eq_maximalIdeal (⊥ : Ideal R) bot_ne_top).symm
    · conv_lhs => rw [hm]
      rw [Ideal.smul_eq_mul, Ideal.span_insert]
      exact sup_le le_sup_left (by rwa [Ideal.span_le, Set.singleton_subset_iff])
  · rw [Ideal.span_le, Set.singleton_subset_iff]; exact ha

/-- **A nonzero constant is a unit in the coordinate ring.**  For `c ≠ 0` in the field `F`, the
class `mk W (CC c)` (`= algebraMap F F[W] c`) is a unit. -/
theorem isUnit_mk_CC {c : F} (hc : c ≠ 0) : IsUnit (mk W (CC c)) := by
  have h1 : mk W (CC c) * mk W (CC c⁻¹) = 1 := by
    simp only [CC, ← map_mul, mul_inv_cancel₀ hc, map_one]
  exact (Units.mkOfMulEqOne _ _ h1).isUnit

/-- **The Jacobian–uniformizer lemma (`#469` milestone).**  At a nonsingular affine point `(x, y)`
of `W`, the maximal ideal of the local ring `Localization.AtPrime ⟨X - x, Y - y⟩` is **principal**.

The proof localises the cotangent relation `taylor_cotangent_mem_sq`: the maximal ideal `m` is
generated by the images `X - x`, `Y - y`; the first-order part
`W_X(x, y)·(X - x) + W_Y(x, y)·(Y - y)` lands in `m²`; and the nonzero partial derivative — a
nonzero constant, hence a unit — lets one generator be solved for in terms of the other modulo `m²`,
so
Nakayama (`maximalIdeal_isPrincipal_of_span_pair`) collapses `m` to a single uniformizer.  This is
the local-normality input for `IsIntegrallyClosed W.CoordinateRing` (over an algebraically closed
base, via `IsIntegrallyClosed.of_localization_maximal`) and hence for `IsDedekindDomain
W.CoordinateRing` (`#396` Part A). -/
theorem maximalIdeal_isPrincipal_of_nonsingular (h : W.Nonsingular x y)
    [(XYIdeal W x (C y)).IsPrime] :
    (IsLocalRing.maximalIdeal (Localization.AtPrime (XYIdeal W x (C y)))).IsPrincipal := by
  set Rp := Localization.AtPrime (XYIdeal W x (C y)) with hRp
  set φ := algebraMap W.CoordinateRing Rp with hφ
  set X' := φ (XClass W x) with hX'
  set Y' := φ (YClass W (C y)) with hY'
  set m := IsLocalRing.maximalIdeal Rp with hm
  -- (1) the maximal ideal is the span of the two generator images
  have hmap : Ideal.map φ (XYIdeal W x (C y)) = m :=
    Localization.AtPrime.map_eq_maximalIdeal
  have hmspan : m = Ideal.span {X', Y'} := by
    rw [← hmap]
    change Ideal.map φ (Ideal.span {XClass W x, YClass W (C y)}) = Ideal.span {X', Y'}
    rw [Ideal.map_span, Set.image_pair]
  -- (2) the localised cotangent relation: the first-order part lands in `m * m`
  have hcot : φ (mk W (CC (W.polynomialX.evalEval x y))) * X'
      + φ (mk W (CC (W.polynomialY.evalEval x y))) * Y' ∈ m * m := by
    have hsq : mk W (CC (W.polynomialX.evalEval x y)) * XClass W x
        + mk W (CC (W.polynomialY.evalEval x y)) * YClass W (C y)
        ∈ XYIdeal W x (C y) * XYIdeal W x (C y) := by
      have hmem := taylor_cotangent_mem_sq h.1
      rwa [pow_two] at hmem
    have hφ2 := Ideal.mem_map_of_mem φ hsq
    rw [Ideal.map_mul, hmap] at hφ2
    simpa only [map_add, map_mul, ← hX', ← hY'] using hφ2
  -- (3) case split on which partial derivative is nonzero
  rcases h.2 with hX0 | hY0
  · -- `W_X(x, y) ≠ 0`: solve `X'` through `Y'` mod `m²`; uniformizer `Y'`
    have hu : IsUnit (φ (mk W (CC (W.polynomialX.evalEval x y)))) :=
      (isUnit_mk_CC W hX0).map φ
    have hin : φ (mk W (CC (W.polynomialX.evalEval x y))) * X'
        ∈ Ideal.span {Y'} ⊔ m * m := by
      have he : φ (mk W (CC (W.polynomialX.evalEval x y))) * X'
          = (φ (mk W (CC (W.polynomialX.evalEval x y))) * X'
              + φ (mk W (CC (W.polynomialY.evalEval x y))) * Y')
            - φ (mk W (CC (W.polynomialY.evalEval x y))) * Y' := by ring
      rw [he]
      exact Ideal.sub_mem _ (Ideal.mem_sup_right hcot)
        (Ideal.mem_sup_left (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))))
    have hmem : X' ∈ Ideal.span {Y'} ⊔ m * m := (Ideal.unit_mul_mem_iff_mem _ hu).mp hin
    exact maximalIdeal_isPrincipal_of_span_pair
      (hmspan.trans (congrArg _ (Set.pair_comm _ _))) hmem
  · -- `W_Y(x, y) ≠ 0`: solve `Y'` through `X'` mod `m²`; uniformizer `X'`
    have hu : IsUnit (φ (mk W (CC (W.polynomialY.evalEval x y)))) :=
      (isUnit_mk_CC W hY0).map φ
    have hin : φ (mk W (CC (W.polynomialY.evalEval x y))) * Y'
        ∈ Ideal.span {X'} ⊔ m * m := by
      have he : φ (mk W (CC (W.polynomialY.evalEval x y))) * Y'
          = (φ (mk W (CC (W.polynomialX.evalEval x y))) * X'
              + φ (mk W (CC (W.polynomialY.evalEval x y))) * Y')
            - φ (mk W (CC (W.polynomialX.evalEval x y))) * X' := by ring
      rw [he]
      exact Ideal.sub_mem _ (Ideal.mem_sup_right hcot)
        (Ideal.mem_sup_left (Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))))
    have hmem : Y' ∈ Ideal.span {X'} ⊔ m * m := (Ideal.unit_mul_mem_iff_mem _ hu).mp hin
    exact maximalIdeal_isPrincipal_of_span_pair hmspan hmem

end CoordinateRing

end WeierstrassCurve.Affine
