/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.MulByThreeModuleFinite

/-!
# Module-finiteness of `F(W)` over the multiplication-by-`3` subfield `[3]∗F(W)`

Building on the two integrality facts of `MulByThreeModuleFinite.lean` (issue #428) — both generic
coordinates `genX`, `genY` are integral over the image subfield
`[3]∗F(W) = (mulByThreeEndo h2 h3).range` — this file completes the **finiteness gate** for the
multiplication-by-`3` pullback, the `n = 3` analogue of the merged `module_finite_mulByTwoRange`
(`MulByTwoExtensionFinite.lean`):

* `isField_mulByThreeRange`: the image `[3]∗F(W)` is a field (the range of an injective field
  endomorphism).
* `module_finite_mulByThreeRange`: `F(W)` is a **finite module** over `[3]∗F(W)`.

## Strategy

Let `A₀ = [3]∗F(W)` (a field) and `B = A₀[genX, genY] ⊆ F(W)` the subalgebra generated by the two
integral coordinates. Then:

* `B` is module-finite over `A₀` — a finite set of integral generators
  (`Algebra.finite_adjoin_of_finite_of_isIntegral`).
* `B` is a field — a domain that is integral over the field `A₀`
  (`isField_of_isIntegral_of_isField'`).
* `B = ⊤`. The image `genPsi '' F[W]` of the coordinate ring lands in `B` (both generators and the
  base constants do, and `B` is a subring), so `B` contains `algebraMap F[W] F(W) a` for every `a`;
  and since every element of `F(W) = Frac F[W]` is `genPsi a / genPsi b` and `B` is a field, `B`
  contains all of `F(W)`.

Chaining these (`Subalgebra.topEquiv` to transport `Module.Finite`) gives `Module.Finite A₀ F(W)`.

This is the finiteness half of Silverman AEC II.2 (a nonconstant map of curves is finite): the
degree-`≤ 9` extension `F(W) / [3]∗F(W)`. Only `[Field F]`, `(2 : F) ≠ 0` and `(3 : F) ≠ 0` are
used; Ward- and normality-independent. The Dedekind integral-closure identification (subtle because
`[3]∗F[W] ⊄ F[W]`) remains for a follow-on; this module-finiteness is its main input.

## References

* [J. Silverman, *The arithmetic of elliptic curves*][silverman2009], II.2.
-/

open Polynomial

namespace WeierstrassCurve.Affine
namespace CoordinateRing

open scoped Polynomial.Bivariate

variable {F : Type*} [Field F] {W : Affine F}

/-- **The multiplication-by-`3` subfield `[3]∗F(W)` is a field.** It is the range of the injective
field endomorphism `mulByThreeEndo h2 h3`, so every nonzero element `mulByThreeEndo w` has inverse
`mulByThreeEndo w⁻¹` inside the range. -/
theorem isField_mulByThreeRange (h2 : (2 : F) ≠ 0) (h3 : (3 : F) ≠ 0) :
    IsField ↥(mulByThreeEndo (W := W) h2 h3).range := by
  refine ⟨⟨0, 1, zero_ne_one⟩, mul_comm, ?_⟩
  rintro ⟨x, w, hw⟩ hx
  -- `x = mulByThreeEndo w`, and `x ≠ 0` gives `w ≠ 0`
  have hx0 : x ≠ 0 := by
    intro h; apply hx; exact Subtype.ext h
  have hw0 : w ≠ 0 := by
    intro h; apply hx0; rw [← hw, h, map_zero]
  refine ⟨⟨mulByThreeEndo h2 h3 w⁻¹, w⁻¹, rfl⟩, ?_⟩
  apply Subtype.ext
  change x * mulByThreeEndo h2 h3 w⁻¹ = 1
  rw [← hw, ← map_mul, mul_inv_cancel₀ hw0, map_one]

/-- **`F(W)` is a finite module over `[3]∗F(W)`.** Both generic coordinates are integral over the
subfield `[3]∗F(W)`, so the subalgebra they generate is a module-finite field, and (being a field
containing the coordinate ring `F[W]` inside the fraction field `F(W)`) it is all of `F(W)`. -/
theorem module_finite_mulByThreeRange (h2 : (2 : F) ≠ 0) (h3 : (3 : F) ≠ 0) :
    letI : Algebra ↥(mulByThreeEndo (W := W) h2 h3).range W.FunctionField :=
      ((mulByThreeEndo (W := W) h2 h3).range.subtype).toAlgebra
    Module.Finite ↥(mulByThreeEndo (W := W) h2 h3).range W.FunctionField := by
  letI : Algebra ↥(mulByThreeEndo (W := W) h2 h3).range W.FunctionField :=
    ((mulByThreeEndo (W := W) h2 h3).range.subtype).toAlgebra
  -- the two integrality facts (from `MulByThreeModuleFinite.lean`)
  have hIX : IsIntegral ↥(mulByThreeEndo (W := W) h2 h3).range (genX W) :=
    mulByThreeRange_isIntegral_genX (W := W) h2 h3
  have hIY : IsIntegral ↥(mulByThreeEndo (W := W) h2 h3).range (genY W) :=
    mulByThreeRange_isIntegral_genY (W := W) h2 h3
  -- the generated subalgebra `B = A₀[genX, genY]`
  set B := Algebra.adjoin ↥(mulByThreeEndo (W := W) h2 h3).range
    ({genX W, genY W} : Set W.FunctionField) with hB
  have hgenXB : genX W ∈ B := Algebra.subset_adjoin (by simp)
  have hgenYB : genY W ∈ B := Algebra.subset_adjoin (by simp)
  -- `B` is module-finite over `A₀`
  have hfinB : Module.Finite ↥(mulByThreeEndo (W := W) h2 h3).range ↥B := by
    apply Algebra.finite_adjoin_of_finite_of_isIntegral
      ((Set.finite_singleton (genY W)).insert (genX W))
    intro x hx
    rcases hx with hx | hx
    · rw [hx]; exact hIX
    · rw [Set.mem_singleton_iff] at hx; rw [hx]; exact hIY
  -- `A₀` is a field, hence `B` is a field (domain integral over a field)
  have hAfield : IsField ↥(mulByThreeEndo (W := W) h2 h3).range := isField_mulByThreeRange h2 h3
  haveI : Algebra.IsIntegral ↥(mulByThreeEndo (W := W) h2 h3).range ↥B :=
    Algebra.IsIntegral.of_finite (R := ↥(mulByThreeEndo (W := W) h2 h3).range) (B := ↥B)
  have hBfield : IsField ↥B := isField_of_isIntegral_of_isField' hAfield
  -- an element of `A₀` (viewed in `F(W)`) lies in `B`
  have hAB : ∀ z : W.FunctionField, z ∈ (mulByThreeEndo (W := W) h2 h3).range → z ∈ B := by
    intro z hz
    have h := B.algebraMap_mem (⟨z, hz⟩ : ↥(mulByThreeEndo (W := W) h2 h3).range)
    have he : (algebraMap ↥(mulByThreeEndo (W := W) h2 h3).range W.FunctionField)
        (⟨z, hz⟩ : ↥(mulByThreeEndo (W := W) h2 h3).range) = z := rfl
    rwa [he] at h
  -- `genPsi (mk (C a)) = algebraMap F[X] F(W) a`, and every `algebraMap F[X] F(W) a` lies in `B`
  have hmemX : ∀ a : F[X], algebraMap F[X] W.FunctionField a ∈ B := by
    intro a
    induction a using Polynomial.induction_on' with
    | add p q hp hq => rw [map_add]; exact add_mem hp hq
    | monomial m c =>
        rw [← C_mul_X_pow_eq_monomial, map_mul, map_pow]
        refine mul_mem ?_ (pow_mem ?_ m)
        · -- `algebraMap F[X] F(W) (C c) = algebraMap F F(W) c ∈ A₀ ⊆ B`
          have hCc : algebraMap F[X] W.FunctionField (C c) = algebraMap F W.FunctionField c := by
            rw [IsScalarTower.algebraMap_apply F F[X] W.FunctionField, Polynomial.algebraMap_eq]
          rw [hCc]
          exact hAB _ (algebraMap_mem_mulByThreeRange h2 h3 c)
        · -- `algebraMap F[X] F(W) X = genX ∈ B`
          have hX : algebraMap F[X] W.FunctionField X = genX W := by
            rw [genX, genPsi, show mk W (C X) = AdjoinRoot.of W.polynomial X from rfl,
              ← AdjoinRoot.algebraMap_eq,
              ← IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField]
          rw [hX]; exact hgenXB
  -- every image `genPsi (mk W p)` of the coordinate ring lies in `B`
  have hmemP : ∀ p : F[X][Y], genPsi W (mk W p) ∈ B := by
    intro p
    induction p using Polynomial.induction_on' with
    | add p q hp hq => rw [map_add, map_add]; exact add_mem hp hq
    | monomial n a =>
        rw [← C_mul_X_pow_eq_monomial, map_mul, map_pow, map_mul, map_pow]
        refine mul_mem ?_ (pow_mem ?_ n)
        · -- `genPsi (mk (C a)) = algebraMap F[X] F(W) a ∈ B`
          have hCa : genPsi W (mk W (C a)) = algebraMap F[X] W.FunctionField a := by
            rw [genPsi, show mk W (C a) = AdjoinRoot.of W.polynomial a from rfl,
              ← AdjoinRoot.algebraMap_eq,
              ← IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField]
          rw [hCa]; exact hmemX a
        · -- `genPsi (mk X) = genY ∈ B`
          have hXY : genPsi W (mk W X) = genY W := by
            rw [genY, AdjoinRoot.mk_X]
          rw [hXY]; exact hgenYB
  have hmem : ∀ c : W.CoordinateRing, genPsi W c ∈ B := by
    intro c
    obtain ⟨p, rfl⟩ := AdjoinRoot.mk_surjective c
    exact hmemP p
  -- every element of `F(W)` lies in `B`, using that `B` is a field
  have hBtop : B = ⊤ := by
    rw [Algebra.eq_top_iff]
    intro z
    obtain ⟨a, b, hb, hab⟩ := IsFractionRing.div_surjective (A := W.CoordinateRing) z
    have hga : genPsi W a ∈ B := hmem a
    have hgb : genPsi W b ∈ B := hmem b
    -- `genPsi b ≠ 0`
    have hgb0 : genPsi W b ≠ 0 := by
      have : b ≠ 0 := nonZeroDivisors.ne_zero hb
      simpa [genPsi] using
        (map_ne_zero_iff _ (IsFractionRing.injective W.CoordinateRing W.FunctionField)).2 this
    -- invert `genPsi b` inside the field `B`
    obtain ⟨β', hβ'⟩ := hBfield.mul_inv_cancel (a := (⟨genPsi W b, hgb⟩ : ↥B))
      (by intro h; exact hgb0 (congrArg Subtype.val h))
    have hmul : genPsi W b * (β' : W.FunctionField) = 1 := congrArg Subtype.val hβ'
    have hinv : (genPsi W b)⁻¹ = (β' : W.FunctionField) := inv_eq_of_mul_eq_one_right hmul
    rw [← hab, div_eq_mul_inv, hinv]
    exact mul_mem hga (SetLike.coe_mem β')
  -- transport `Module.Finite A₀ B` along `B = ⊤ ≃ F(W)`
  rw [hBtop] at hfinB
  haveI := hfinB
  exact Module.Finite.equiv (Subalgebra.topEquiv.toLinearEquiv)

end CoordinateRing
end WeierstrassCurve.Affine
