/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.MulByNXCoordFormula
import EllipticCurves.Torsion.CoprimeAdjacent

/-!
# `[F(W) : [n]∗F(W)] = n²` at general `n`, with no hypothesis left

`EllipticCurves.FunctionField.MulByNDegreeTower` reduces the degree of the multiplication-by-`n`
pullback at general `n` to three gates.  `EllipticCurves.FunctionField.MulByNXCoordFormula`
discharges the first (`nMulRatFunc W n = ΦDivΨSq W n`, by applying the merged coordinate formula at
the generic point) and leaves two: the coprimality of `Φₙ` and `ΨSqₙ`, and `(n : F) ≠ 0`.

`EllipticCurves.Torsion.CoprimeAdjacent` supplies the first of those two over a field of
characteristic `≠ 2` on an elliptic curve.  **This file is the composition, and it is four
tokens long.**

```
finrank_mulByNFieldRange_eq_sq_of_isCoprime_ΨSq_adjacent h2 hn (isCoprime_ΨSq_adjacent h2 _)
```

## ⚠️ What is and is not settled

* The degree `[F(W) : [n]∗F(W)] = n²` now holds at **every** index with `((n : ℤ) : F) ≠ 0`, over
  any field of characteristic `≠ 2`, for an elliptic curve — with no unsupplied hypothesis.  The two
  merged instances `finrank_mulByTwoFieldRange` and `finrank_mulByThreeFieldRange` are the `n = 2`
  and `n = 3` cases; the `example` below is `n = 5`, the smallest index at which no coprimality
  certificate exists in this development and which therefore certifies that this is not those two
  in disguise.
* ⚠️ **`(n : F) ≠ 0` is not removable by anything here.**  It is gate 3 of
  `EllipticCurves.FunctionField.MulByNDegreeTower` and it enters twice over: through
  `WeierstrassCurve.natDegree_ΨSq` and through the transcendence of `x(n • 𝒫)`.  In characteristic
  `p` at `p ∣ n` this file says nothing.
* ⚠️ **A field degree is not a point count.**  Nothing here bears on `#E[n] = n²`: the step from a
  degree to a kernel cardinality is separability of the isogeny `[n]`, which is in this development
  at no index — `EllipticCurves.FunctionField.MulByTwoDegree`'s scope section says so, and
  `EllipticCurves.Torsion.OddTorsionCount` prices the remaining torsion gate independently, as
  separability of `preΨₙ`.  Do not read this file as progress on `#242` / `#293`.
* ⚠️ **The `y`-half of `[n]∗` is untouched.**  What is measured is the degree of the subfield
  generated by the `x`-coordinate route; identifying the full pair `(Φₙ/ΨSqₙ, ωₙ/ψₙ³)` with `n • P`
  is a separate obligation and is not consumed by a degree count.

## Main statements

* `WeierstrassCurve.Affine.CoordinateRing.finrank_mulByNFieldRange_eq_sq_of_two_ne_zero` :
  **`[F(W) : [n]∗F(W)] = n²`** at every index with `((n : ℤ) : F) ≠ 0`.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2 and III.4.
-/

open Polynomial Module

namespace WeierstrassCurve.Affine

namespace CoordinateRing

variable {F : Type*} [Field F] {W : Affine F} [W.IsElliptic]

/-- **`[F(W) : [n]∗F(W)] = n²`**, at every index with `((n : ℤ) : F) ≠ 0`, over a field of
characteristic `≠ 2` — with no remaining hypothesis.

`finrank_mulByNFieldRange_eq_sq_of_isCoprime_ΨSq_adjacent`
(`EllipticCurves.FunctionField.MulByNXCoordFormula`) carries the coprimality as its last
hypothesis; `isCoprime_ΨSq_adjacent` (`EllipticCurves.Torsion.CoprimeAdjacent`) supplies it, at
every `n : ℤ` and with no hypothesis on `n` at all.

⚠️ The transcendence proof in the subfield is a *parameter of the statement*, because the subfield
whose degree is measured depends on it; the one fixed here is
`transcendental_xCoord_nsmul_genericPoint_of_intCast_ne_zero`, which asks `((n : ℤ) : F) ≠ 0` and no
algebraic closure.  Any proof of the same `Transcendental` gives the same subfield, by proof
irrelevance. -/
theorem finrank_mulByNFieldRange_eq_sq_of_two_ne_zero (h2 : (2 : F) ≠ 0) {n : ℕ}
    (hn : ((n : ℤ) : F) ≠ 0) :
    finrank
      ↥(mulByNEndoAlgHom n
        (transcendental_xCoord_nsmul_genericPoint_of_intCast_ne_zero (W := W) h2 hn)).fieldRange
      W.FunctionField = n ^ 2 :=
  finrank_mulByNFieldRange_eq_sq_of_isCoprime_ΨSq_adjacent h2 hn (isCoprime_ΨSq_adjacent h2 _)

/-- **`[F(W) : [5]∗F(W)] = 25`.**  ⚠️ Not a new theorem — it is the instance of the one above at the
smallest index outside `{2, 3}`, and therefore the machine-checked certificate that the general
statement is not the two merged instances re-parametrised.  `n = 5` has no coprimality certificate
anywhere in this development; `EllipticCurves.FunctionField.MulByNXCoordFormula` could only state
gate 1 there. -/
example (h2 : (2 : F) ≠ 0) (h5 : (5 : F) ≠ 0) :
    finrank
      ↥(mulByNEndoAlgHom 5
        (transcendental_xCoord_nsmul_genericPoint_of_intCast_ne_zero (W := W) h2
          (by simpa using h5))).fieldRange
      W.FunctionField = 5 ^ 2 :=
  finrank_mulByNFieldRange_eq_sq_of_two_ne_zero h2 (by simpa using h5)

end CoordinateRing

end Affine

end WeierstrassCurve
