/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.NegYGalois
import EllipticCurves.FunctionField.SubfieldAut

/-!
# `Gal(F(W) / F(x)) ≃* ⟨ι⟩`: the Galois group is generated by the hyperelliptic involution

`EllipticCurves.FunctionField.NegYGalois` closes the Artin sandwich

```
F(x)  =  Fixed(⟨ι⟩)  ⊆  F(W),      [F(W) : F(x)] = 2 = |⟨ι⟩| = [F(W) : Fixed(⟨ι⟩)]
```

and concludes `IsGalois ↥(ratFuncRange W) F(W)` — over an **arbitrary** field and in **every**
characteristic.  It then says, in its `## Scope`, that it is *"not a statement about
`Gal(F(W)/F(x))` as a group"* and names `ratFuncRange_eq_fixedField_negYGroup` as what such an
identification *"would start from"*.  This file carries it out, and that bullet is retired in the
same change.

```
negYGroupGaloisEquiv : ⟨ι⟩ ≃* (F(W) ≃ₐ[F(x)] F(W))
```

## ⚠️ What is new here, measured rather than assumed

An `≃*` between two groups of order `2` is by itself no information at all — every two groups of
order `2` are isomorphic.  So it is worth being exact about which of the three statements below
carries content:

* **`negYGroupGaloisEquiv_apply` is the content.**  The isomorphism *is* the inclusion
  `⟨ι⟩ ↪ Aut_F F(W)`, read as acting over `F(x)`; it holds by `rfl`.
* **`forall_eq_or_forall_eq_negYAlgEquiv` is the payoff.**  Every `F(x)`-automorphism of `F(W)` is
  the identity or `ι` — the concrete reading, and the analogue of
  `exists_mem_torsion_translateAut_eq_of_smooth` in
  `EllipticCurves.FunctionField.MulByNGaloisGroup`.
* ⚠️ **`card_galoisGroup_ratFuncRange` is *not* new, and this file says so rather than implying
  otherwise.**  `|Gal(F(W)/F(x))| = 2` follows from merged material with no new declaration at all,
  by `IsGalois.card_aut_eq_finrank` against `finrank_ratFuncRange`; that three-line proof is
  committed below as an `example` beside the one-line proof off the equivalence.  The named form is
  kept because it is what a consumer reaches for, not because it was unreachable.

## No hypothesis is added, and that is the point of the file it extends

`EllipticCurves.FunctionField.NegYGalois` carries **no** `[IsAlgClosed F]` and **no** condition on
the characteristic, unlike `EllipticCurves.FunctionField.MulByTwoGalois`, whose hypotheses come
from `#E[2] = 4`.  Nothing in the route below adds one: `Finite ↥(negYGroup W)` is the
unconditional instance `finite_negYGroup`, `FaithfulSMul ↥(negYGroup W) F(W)` is Mathlib's
`Subgroup.instFaithfulSMulSubtypeMem` applied to the tautological action of `Aut_F F(W)`, and
neither `FixedPoints.toAlgAutMulEquiv` nor `Subfield.autMulEquivOfEq` asks for more.  So — unlike
every other Galois-group statement in this directory — the results below hold in characteristic
`2`, and the non-vacuity block at the bottom is committed **there**, on `y² + y = x³` over
`ZMod 2`.

⚠️ `[W.IsElliptic]` is not decoration: it is spent in `negYAlgEquiv_ne_one`, which is what makes
`⟨ι⟩` have order `2` rather than `1`.  For a bare Weierstrass curve over a field of characteristic
`2` with `a₁ = a₃ = 0` the involution *is* the identity and everything below is false.

## ⚠️ `MulByNGaloisGroup` is quoted below but no longer imported (`#1267`)

Every reference to `EllipticCurves.FunctionField.MulByNGaloisGroup` in this docstring is a
comparison, and this file no longer imports it.  ⚠️ **It used to, for exactly one name** — the
curve-free `Subfield.autMulEquivOfEq`, which is now the leaf
`EllipticCurves.FunctionField.SubfieldAut` — and that import carried **53 project modules** into a
file whose whole point is that it assumes nothing.  Project-import closure `71 → 19`, total closure
`3027 → 2891`; the leaf's own project closure is `0` and its two `Mathlib` imports were already
inside `EllipticCurves.FunctionField.NegYGalois`'s closure, so nothing was added to pay for it.
The prose pointers stay: a sibling file worth comparing against is not the same thing as a
dependency.

## ⚠️ The one real difference from `EllipticCurves.FunctionField.MulByNGaloisGroup`

That file's sandwich `fixedPoints_subfield_eq_mulByNEndoFieldRange` is an equality of **`Subfield`
`F(W)`**, which is exactly what `FixedPoints.toAlgAutMulEquiv` produces and what
`Subfield.autMulEquivOfEq` transports along.  This file's merged sandwich

```lean
ratFuncRange_eq_fixedField_negYGroup : ratFuncRange W = IntermediateField.fixedField (negYGroup W)
```

is an equality of **`IntermediateField F F(W)`**, so the helper does not apply to it as it stands.
`fixedPoints_subfield_eq_ratFuncRange` below drops it to the `Subfield` level by `SetLike.ext` —
membership on both sides is literally the same proposition, so the merged headline is the only
input and no second degree computation is needed.  This is the same move
`finrank_fixedField_negYGroup` already makes one screen above the retired bullet, and for the same
reason.

## ⚠️ The two presentations of `F(x)` give the same automorphism group — no second declaration

`EllipticCurves.FunctionField.MulByNGaloisGroup` measured that
`F(W) ≃ₐ[↥(I : IntermediateField _ _)] F(W)` and `F(W) ≃ₐ[↥(S : Subfield _)] F(W)` are
definitionally equal when the carriers are, and committed the measurement as an `example` rather
than minting a twin.  The same holds here for `ratFuncRange W` and `(ratFuncRange W).toSubfield`
and is committed the same way, so `negYGroupGaloisEquiv` is stated over the `IntermediateField`
form — the one every merged consumer holds — with **no** `Subfield` twin.

## Main definitions

Every public declaration of this file is listed, here and under `## Main statements`; all are in
namespace `WeierstrassCurve.Affine.CoordinateRing`.

* `negYGroupGaloisEquiv` — `⟨ι⟩ ≃* Gal(F(W) / F(x))`.

## Main statements

* `fixedPoints_subfield_eq_ratFuncRange` — the merged sandwich at the `Subfield` level;
* `negYGroupGaloisEquiv_apply` and `negYGroupGaloisEquiv_negYAlgEquiv` — the isomorphism is the
  inclusion of `⟨ι⟩` into `Aut_F F(W)`, and it sends the generator to `ι`; both by `rfl`;
* `eq_one_or_eq_negYAlgEquiv_of_mem_negYGroup` — a member of `⟨ι⟩` is `1` or `ι`;
* **`forall_eq_or_forall_eq_negYAlgEquiv`** — every `F(x)`-automorphism of `F(W)` is `1` or `ι`;
* `card_galoisGroup_ratFuncRange` — `|Gal(F(W) / F(x))| = 2`.

## What is *not* here

* **Not `mapProjPoint ι ≠ 1`.**  `EllipticCurves.FunctionField.NegYInvolution`'s `## Scope` is
  explicit that `ι ≠ 1` is a statement about the automorphism and not about the permutation of
  `ProjPoint W` it induces, and `EllipticCurves.FunctionField.NegYGalois` repeats it.  Nothing here
  changes that, and nothing here mentions `ProjPoint`.
* **Nothing about `[2]∗F(W)`.**  `F(W)/F(x)` and `F(W)/[2]∗F(W)` are different extensions;
  `EllipticCurves.FunctionField.MulByTwoGalois` is a template and not an input, and its
  `[IsAlgClosed F]` and `(2 : F) ≠ 0` — which come from `#E[2] = 4` — are removed by nothing here.
  ⚠️ In particular this file does **not** say the two Galois groups are related; at
  characteristic `2` the merged `n = 2` statements are unavailable and these are not.
* **No Galois correspondence** — no `IntermediateField.fixingSubgroup` statement, no subgroup
  lattice, nothing about the intermediate fields of `F(W)/F(x)`.  ⚠️ That there are no proper ones
  is immediate from `finrank_ratFuncRange = 2` and multiplicativity of degree, and needs neither
  the correspondence nor anything below; it is simply not stated anywhere.
* **Nothing about places, divisors, ramification or the degree comparison.**
  `EllipticCurves.FunctionField.PlaceDegreeComparison` consumes
  `isGalois_fractionRing_polynomial`, not the group, and is untouched.
* **No new mathematics about `ι`.**  `orderOf_negYAlgEquiv`, `card_negYGroup` and the sandwich are
  all merged inputs; this file transports them.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2 and III.2.
* Artin's theorem on fixed fields, [stacks 09I3].
-/

open Module Polynomial

namespace WeierstrassCurve.Affine

namespace CoordinateRing

variable {F : Type*} [Field F] {W : Affine F} [W.IsElliptic]

/-! ### The merged sandwich at the `Subfield` level -/

/-- **`Fixed(⟨ι⟩)` and `F(x)` are the same subfield of `F(W)`.**

This is `ratFuncRange_eq_fixedField_negYGroup` (`EllipticCurves.FunctionField.NegYGalois`) with the
`IntermediateField` presentation replaced by the `Subfield` one that
`FixedPoints.toAlgAutMulEquiv` produces.  Membership in `FixedPoints.subfield ⟨ι⟩ F(W)` and in
`IntermediateField.fixedField (negYGroup W)` unfold to the same proposition — both are
`MulAction.fixedPoints ↥(negYGroup W) F(W)` — so this is `SetLike.ext` off the merged headline and
needs **no** second degree computation. -/
theorem fixedPoints_subfield_eq_ratFuncRange :
    FixedPoints.subfield ↥(negYGroup W) W.FunctionField = (ratFuncRange W).toSubfield := by
  refine SetLike.ext fun g => ?_
  have hg : g ∈ ratFuncRange W ↔ g ∈ IntermediateField.fixedField (negYGroup W) := by
    rw [← ratFuncRange_eq_fixedField_negYGroup]
  exact hg.symm

/-! ### The Galois group -/

/-- **`Gal(F(W) / F(x)) ≃* ⟨ι⟩`**, over an arbitrary field and in every characteristic — the
identification `EllipticCurves.FunctionField.NegYGalois` records as missing, on top of the sandwich
it proves.

`FixedPoints.toAlgAutMulEquiv` gives `⟨ι⟩ ≃* (F(W) ≃ₐ[Fixed(⟨ι⟩)] F(W))` from the action of the
subgroup, its faithfulness and its finiteness — all three unconditional instances here;
`fixedPoints_subfield_eq_ratFuncRange` says the base is `F(x)`; `Subfield.autMulEquivOfEq`
(`EllipticCurves.FunctionField.SubfieldAut`) moves it there.

⚠️ See `negYGroupGaloisEquiv_apply`: the map is the inclusion of `⟨ι⟩` into `Aut_F F(W)`, and that
is the content — an abstract `≃*` between two groups of order `2` carries none. -/
noncomputable def negYGroupGaloisEquiv (W : Affine F) [W.IsElliptic] :
    ↥(negYGroup W) ≃* (W.FunctionField ≃ₐ[↥(ratFuncRange W)] W.FunctionField) :=
  (FixedPoints.toAlgAutMulEquiv ↥(negYGroup W) W.FunctionField).trans
    (Subfield.autMulEquivOfEq fixedPoints_subfield_eq_ratFuncRange)

/-- **The isomorphism is the inclusion `⟨ι⟩ ↪ Aut_F F(W)`.**  True by `rfl`:
`FixedPoints.toAlgAutMulEquiv` is `MulEquiv.ofBijective` of `MulSemiringAction.toAlgAut`, the action
of a `Subgroup` of `Aut_F F(W)` on `F(W)` is application, and `Subfield.autMulEquivOfEq` changes no
underlying function. -/
@[simp] lemma negYGroupGaloisEquiv_apply (W : Affine F) [W.IsElliptic] (σ : ↥(negYGroup W))
    (g : W.FunctionField) :
    negYGroupGaloisEquiv W σ g = (σ : W.FunctionField ≃ₐ[F] W.FunctionField) g := rfl

/-- **The generator goes to `ι`**, by `rfl` — the specialisation of `negYGroupGaloisEquiv_apply`
that names the hyperelliptic involution, since it is the one a reader checks. -/
lemma negYGroupGaloisEquiv_negYAlgEquiv (W : Affine F) [W.IsElliptic] (g : W.FunctionField) :
    negYGroupGaloisEquiv W ⟨negYAlgEquiv W, Subgroup.mem_zpowers _⟩ g = negYAlgEquiv W g := rfl

/-! ### Every `F(x)`-automorphism is `1` or `ι` -/

/-- **A member of `⟨ι⟩` is `1` or `ι`.**  `Subgroup.zpowers` is the set of integer powers and
`orderOf_negYAlgEquiv` says the order is `2`, so the exponent may be reduced mod `2`.

⚠️ Group-theoretic and curve-free apart from `orderOf_negYAlgEquiv`; the mathematics of the
involution is entirely in that merged input. -/
theorem eq_one_or_eq_negYAlgEquiv_of_mem_negYGroup
    {τ : W.FunctionField ≃ₐ[F] W.FunctionField} (hτ : τ ∈ negYGroup W) :
    τ = 1 ∨ τ = negYAlgEquiv W := by
  obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hτ
  rw [← zpow_mod_orderOf, orderOf_negYAlgEquiv]
  push_cast
  rcases Int.emod_two_eq_zero_or_one k with hk | hk <;> rw [hk]
  · exact Or.inl (by norm_num)
  · exact Or.inr (by norm_num)

/-- **Every `F(x)`-automorphism of `F(W)` is the identity or the hyperelliptic involution** — the
concrete reading of `negYGroupGaloisEquiv`, and the analogue of
`exists_mem_torsion_translateAut_eq_of_smooth`
(`EllipticCurves.FunctionField.MulByNGaloisGroup`) for this extension.

⚠️ This is the statement worth having.  `card_galoisGroup_ratFuncRange` says the group has two
elements; this one says **which** two, and the answer is a map written down in
`EllipticCurves.FunctionField.NegYInvolution` in closed form (`x ↦ x`, `y ↦ −y − a₁x − a₃`).  Both
alternatives really occur, since `negYAlgEquiv_ne_one` is merged. -/
theorem forall_eq_or_forall_eq_negYAlgEquiv
    (σ : W.FunctionField ≃ₐ[↥(ratFuncRange W)] W.FunctionField) :
    (∀ g : W.FunctionField, σ g = g) ∨ (∀ g : W.FunctionField, σ g = negYAlgEquiv W g) := by
  obtain ⟨τ, hτ⟩ := (negYGroupGaloisEquiv W).surjective σ
  rcases eq_one_or_eq_negYAlgEquiv_of_mem_negYGroup τ.2 with h | h
  · exact Or.inl fun g => by rw [← hτ, negYGroupGaloisEquiv_apply, h]; rfl
  · exact Or.inr fun g => by rw [← hτ, negYGroupGaloisEquiv_apply, h]

/-! ### The order of the Galois group

⚠️ **This section adds no reach**, and says so rather than reading as though it did — see the
`example` below `card_galoisGroup_ratFuncRange`. -/

/-- **`|Gal(F(W) / F(x))| = 2`**, by `Nat.card` off the equivalence and `card_negYGroup`. -/
theorem card_galoisGroup_ratFuncRange :
    Nat.card (W.FunctionField ≃ₐ[↥(ratFuncRange W)] W.FunctionField) = 2 :=
  (Nat.card_congr (negYGroupGaloisEquiv W).toEquiv).symm.trans card_negYGroup

/-- ⚠️ **The count was already reachable without this file, and here is the proof that does not use
it.**  `isGalois_ratFuncRange` is a merged instance and `finrank_ratFuncRange` is merged, so
`IsGalois.card_aut_eq_finrank` closes the same goal in three lines.  This `example` is committed so
that the value of `card_galoisGroup_ratFuncRange` is not overstated: it is a *name* for a fact the
tree already had, whereas `negYGroupGaloisEquiv_apply` and `forall_eq_or_forall_eq_negYAlgEquiv`
are not. -/
example : Nat.card (W.FunctionField ≃ₐ[↥(ratFuncRange W)] W.FunctionField) = 2 := by
  haveI : FiniteDimensional ↥(ratFuncRange W) W.FunctionField :=
    Module.finite_of_finrank_pos (by rw [finrank_ratFuncRange]; norm_num)
  rw [IsGalois.card_aut_eq_finrank, finrank_ratFuncRange]

/-- ⚠️ **The `IntermediateField` and `Subfield` presentations of `F(x)` give the same automorphism
group, and this commits it.**  Same measurement `EllipticCurves.FunctionField.MulByNGaloisGroup`
records for `[n]∗F(W)`; it is why nothing above has a `Subfield` twin. -/
example : (W.FunctionField ≃ₐ[↥(ratFuncRange W)] W.FunctionField)
    = (W.FunctionField ≃ₐ[↥(ratFuncRange W).toSubfield] W.FunctionField) := rfl

/-! ### Non-vacuity, in characteristic `2`

Every statement above needs `[W.IsElliptic]` and nothing else, so a certificate is cheap — but the
choice of curve is not arbitrary.  ⚠️ It is committed over `ZMod 2`, where
`EllipticCurves.FunctionField.MulByTwoGalois`'s `n = 2` analogue is **unavailable** (it needs
`(2 : F) ≠ 0` and `[IsAlgClosed F]`), because that is the case these statements reach and the
`[n]∗` front does not.  The curve is `y² + y = x³`, of discriminant `−27 = 1 ≠ 0` in
characteristic `2`; it is the reduction of the same curve the `[n]∗` non-vacuity blocks use.
⚠️ Every hypothesis is **produced**, not assumed. -/

section Nonvacuity

/-- The field of two elements — chosen so that the certificates below are in characteristic `2`. -/
private abbrev exampleFieldNegYGalois : Type := ZMod 2

/-- The curve `y² + y = x³` over `ZMod 2`, of discriminant `−27 = 1`.

⚠️ `a₁ = 0` and `a₃ = 1`, so the involution `y ↦ −y − a₁x − a₃` is `y ↦ y + 1` and is *not* the
identity — which is exactly what `negYAlgEquiv_ne_one` extracts from `Δ ≠ 0`, and what would fail
for `y² = x³ + …` over this field. -/
private noncomputable def exampleCurveNegYGalois : Affine exampleFieldNegYGalois := ⟨0, 0, 1, 0, 0⟩

private instance : exampleCurveNegYGalois.IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero]
  decide +kernel

/-- **The group identification on a genuine curve, in characteristic `2`.** -/
noncomputable example : ↥(negYGroup exampleCurveNegYGalois) ≃*
    (exampleCurveNegYGalois.FunctionField ≃ₐ[↥(ratFuncRange exampleCurveNegYGalois)]
      exampleCurveNegYGalois.FunctionField) :=
  negYGroupGaloisEquiv exampleCurveNegYGalois

/-- **`|Gal(F(W) / F(x))| = 2` on a genuine curve in characteristic `2`.** -/
example : Nat.card (exampleCurveNegYGalois.FunctionField ≃ₐ[↥(ratFuncRange
    exampleCurveNegYGalois)] exampleCurveNegYGalois.FunctionField) = 2 :=
  card_galoisGroup_ratFuncRange

/-- **Every `F(x)`-automorphism is `1` or `ι`**, committed on the same curve. -/
example (σ : exampleCurveNegYGalois.FunctionField ≃ₐ[↥(ratFuncRange exampleCurveNegYGalois)]
    exampleCurveNegYGalois.FunctionField) :
    (∀ g : exampleCurveNegYGalois.FunctionField, σ g = g) ∨
      (∀ g : exampleCurveNegYGalois.FunctionField,
        σ g = negYAlgEquiv exampleCurveNegYGalois g) :=
  forall_eq_or_forall_eq_negYAlgEquiv σ

end Nonvacuity

end CoordinateRing

end WeierstrassCurve.Affine
