/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.PlaceResidueField

/-!
# Every place of the projective curve is a discrete valuation ring

`EllipticCurves.FunctionField.Places` (`#651`) classifies the places of `F(W)` over `F` as
`placeOf W p` for `p : ProjPoint W`, and `EllipticCurves.FunctionField.PlaceOrder` equips each with
an order function `divisorProj W · p : F(W) → ℤ` whose nonnegativity locus is the place itself and
which attains the value `1`.  `EllipticCurves.FunctionField.PlaceResidueField` (`#742`) reads the
maximal ideal off that order function and shows it is generated by any uniformizer.

This file closes the gap between "the maximal ideal is principal" and the typeclass:

```lean
instance : IsDiscreteValuationRing (placeOf W p)
```

**uniformly in `p`, with no case split on `none` / `some v`** — that is the point of `placeOf`, and
the argument below never unfolds either branch.  It runs entirely on the order function, so the two
branches' very different provenance (a valuation subring built from `ordInfty` at infinity, a
localisation of `F[W]` at an affine closed point) is invisible to it.

## Why this is not free from `#742`

Mathlib's `IsDiscreteValuationRing R` is *a local principal ideal domain that is not a field*, so a
principal **maximal** ideal is not enough: every ideal has to be principal.  For a ring with a
`ℤ`-valued order function that is the classical argument — an ideal is generated by any of its
elements of least order — and it is `isPrincipalIdealRing_placeOf` below.  The two ingredients are
`mem_placeOf_iff_divisorProj_nonneg` (`#658`) and the multiplicativity of `divisorProj`; nothing
about curves enters.

## Main results

* **`WeierstrassCurve.Affine.mem_span_singleton_of_divisorProj_le`** — divisibility inside a place
  is a comparison of orders: if `a ≠ 0` has order at most that of `x`, then `a ∣ x` there.  This is
  the one computational step, and it is the same "divide and stay in the place" move that
  `maximalIdeal_placeOf_eq_span` makes at order `1`;
* **`WeierstrassCurve.Affine.isPrincipalIdealRing_placeOf`** — an ideal is generated by any element
  of least order in it;
* `WeierstrassCurve.Affine.maximalIdeal_placeOf_ne_bot` — a place is not a field, because it has a
  uniformizer;
* **`WeierstrassCurve.Affine.isDiscreteValuationRing_placeOf`** — the headline, an `instance`;
* `WeierstrassCurve.Affine.isNoetherianRing_placeOf` and
  `WeierstrassCurve.Affine.isDomain_placeOf` — the by-products later work consumes.  A place being
  Noetherian is what every route to the fundamental identity `∑ e_p · f_p = 4` needs of the ring
  *below* (`#744`): `Ideal.sum_ramification_inertia_eq_finrank` wants `Module.Finite`, and
  Mathlib's only route to that for an integral closure, `IsIntegralClosure.finite`, wants
  `[IsNoetherianRing R]`;
* **`WeierstrassCurve.Affine.irreducible_placeOf_iff`** — an element of a place is irreducible
  exactly when it is a uniformizer, i.e. has order `1`.  This is what connects the order function
  to `IsDiscreteValuationRing.addVal` and hence to `Ideal.ramificationIdx`.

## What is *not* here

* Any identification of `divisorProj W · p` with `IsDiscreteValuationRing.addVal (placeOf W p)`.
  `irreducible_placeOf_iff` is the bridge that makes it available; carrying it out is separate
  work, and the two disagree on `0` anyway (`addVal` returns `⊤`, `divisorProj` returns `0`).
* The integral closure of a place of `[2]∗F(W)` in `F(W)` and its module-finiteness; the
  `primesOver` ↔ fibre dictionary; the fundamental identity itself.
* Any computation of `ramificationIdxTwo`, and any comparison with `degPt`.

Ward-independent, normality-independent, `#418`-independent: `[Field F]` and
`[IsDedekindDomain W.CoordinateRing]` throughout, with no `[W.IsElliptic]`, no `[IsAlgClosed F]`
and no hypothesis on the characteristic.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.1.
* Stichtenoth, *Algebraic Function Fields and Codes*, I.1 (a place is a discrete valuation ring).
* Serre, *Local Fields*, I.1, Proposition 1.
-/

open IsDedekindDomain

namespace WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W : Affine F} [IsDedekindDomain W.CoordinateRing]

/-! ### Divisibility inside a place is a comparison of orders -/

/-- **The order of an element of a place is nonnegative**, with no nonvanishing hypothesis.  The
junk value `divisorProj W 0 p = 0` is nonnegative too, so unlike `mem_maximalIdeal_placeOf_iff`
this one needs no side condition. -/
theorem divisorProj_placeOf_nonneg {p : ProjPoint W} (x : placeOf W p) :
    0 ≤ divisorProj W (x : W.FunctionField) p := by
  rcases eq_or_ne (x : W.FunctionField) 0 with h | h
  · rw [h, divisorProj_zero, Finsupp.zero_apply]
  · exact (mem_placeOf_iff_divisorProj_nonneg p h).1 x.2

/-- **Divisibility inside a place is a comparison of orders.**  If `a` is a nonzero element of the
place whose order is at most that of `x`, then `x` lies in the ideal `a` generates.

The proof is the same move `maximalIdeal_placeOf_eq_span` makes at order `1`: the quotient `x / a`
has nonnegative order, hence lies back in the place, and multiplying it by `a` returns `x`.  The
vanishing case `x = 0` is split off first, because the junk value `divisorProj W 0 p = 0` would
otherwise make the hypothesis say the wrong thing. -/
theorem mem_span_singleton_of_divisorProj_le {p : ProjPoint W} {a x : placeOf W p}
    (ha : (a : W.FunctionField) ≠ 0)
    (h : divisorProj W (a : W.FunctionField) p ≤ divisorProj W (x : W.FunctionField) p) :
    x ∈ Ideal.span {a} := by
  rcases eq_or_ne (x : W.FunctionField) 0 with hx | hx
  · have hx0 : x = 0 := Subtype.ext (by simpa using hx)
    simp [hx0]
  · have hq : (x : W.FunctionField) / (a : W.FunctionField) ∈ placeOf W p := by
      rw [mem_placeOf_iff_divisorProj_nonneg p (div_ne_zero hx ha), divisorProj_div hx ha,
        Finsupp.sub_apply]
      omega
    exact Ideal.mem_span_singleton'.2
      ⟨⟨_, hq⟩, Subtype.ext (by simpa using div_mul_cancel₀ (x : W.FunctionField) ha)⟩

/-! ### Every ideal is principal -/

/-- **An ideal of a place is generated by any of its elements of least order.**

Let `I ≠ ⊥`.  The orders of the nonzero elements of `I` form a nonempty set of naturals — nonempty
because `I ≠ ⊥`, naturals because every element of the place has nonnegative order — so it has a
least element, attained at some `a ∈ I`.  Then `mem_span_singleton_of_divisorProj_le` puts every
element of `I` in `Ideal.span {a}`, and `a ∈ I` gives the other inclusion.

Nothing about curves is used: this is the classical argument for any ring cut out as the
nonnegativity locus of a `ℤ`-valued order function on a field. -/
theorem isPrincipalIdealRing_placeOf (p : ProjPoint W) : IsPrincipalIdealRing (placeOf W p) := by
  refine ⟨fun I => ?_⟩
  rcases eq_or_ne I ⊥ with rfl | hI
  · exact bot_isPrincipal
  obtain ⟨b, hbI, hb0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hI
  have hb0' : (b : W.FunctionField) ≠ 0 := fun h => hb0 (Subtype.ext (by simpa using h))
  have hne : {n : ℕ | ∃ x ∈ I, (x : W.FunctionField) ≠ 0 ∧
      (divisorProj W (x : W.FunctionField) p).toNat = n}.Nonempty :=
    ⟨_, b, hbI, hb0', rfl⟩
  obtain ⟨a, haI, ha0, han⟩ := Nat.sInf_mem hne
  refine ⟨⟨a, ?_⟩⟩
  rw [Ideal.submodule_span_eq]
  refine le_antisymm (fun x hx => ?_) ((Ideal.span_singleton_le_iff_mem _).2 haI)
  rcases eq_or_ne (x : W.FunctionField) 0 with hx0 | hx0
  · have : x = 0 := Subtype.ext (by simpa using hx0)
    simp [this]
  · refine mem_span_singleton_of_divisorProj_le ha0 ?_
    have hmem : (divisorProj W (x : W.FunctionField) p).toNat ∈
        {n : ℕ | ∃ x ∈ I, (x : W.FunctionField) ≠ 0 ∧
          (divisorProj W (x : W.FunctionField) p).toNat = n} := ⟨x, hx, hx0, rfl⟩
    have hle := Nat.sInf_le hmem
    have hpa := divisorProj_placeOf_nonneg a
    have hpx := divisorProj_placeOf_nonneg x
    omega

/-! ### The discrete valuation ring -/

/-- **A place is not a field**, because it has a uniformizer: the maximal ideal is generated by an
element of order `1`, which is in particular nonzero. -/
theorem maximalIdeal_placeOf_ne_bot (p : ProjPoint W) :
    IsLocalRing.maximalIdeal (placeOf W p) ≠ ⊥ := by
  obtain ⟨π, hπ0, hπ⟩ := exists_divisorProj_eq_one p
  have hmem : π ∈ placeOf W p :=
    (mem_placeOf_iff_divisorProj_nonneg p hπ0).2 (by rw [hπ]; norm_num)
  rw [maximalIdeal_placeOf_eq_span (⟨π, hmem⟩ : placeOf W p) hπ, Ne,
    Ideal.span_singleton_eq_bot]
  exact fun h => hπ0 (congrArg Subtype.val h)

/-- **Every place of the projective curve is a discrete valuation ring.**  Uniform in `p`: the
proof never unfolds `placeOf`, and in particular the point at infinity is not special.

The three fields are `isPrincipalIdealRing_placeOf`, the local-ring instance every
`ValuationSubring` carries, and `maximalIdeal_placeOf_ne_bot`.  No hypothesis on `F` and no
`[W.IsElliptic]` beyond what `[IsDedekindDomain W.CoordinateRing]` already asks for. -/
instance isDiscreteValuationRing_placeOf (p : ProjPoint W) :
    IsDiscreteValuationRing (placeOf W p) where
  toIsPrincipalIdealRing := isPrincipalIdealRing_placeOf p
  toIsLocalRing := inferInstance
  not_a_field' := maximalIdeal_placeOf_ne_bot p

/-- A place is an integral domain — it is a subring of `F(W)`.  Named because the DVR interface
takes it as an argument everywhere. -/
theorem isDomain_placeOf (p : ProjPoint W) : IsDomain (placeOf W p) := inferInstance

/-- **A place is Noetherian.**  Free from the previous instance, and named because this is the
hypothesis the fundamental identity of `#744` needs of the ring *below*:
`Ideal.sum_ramification_inertia_eq_finrank` wants `Module.Finite R S`, and Mathlib's route to that
for an integral closure, `IsIntegralClosure.finite`, wants `[IsNoetherianRing R]`. -/
theorem isNoetherianRing_placeOf (p : ProjPoint W) : IsNoetherianRing (placeOf W p) := inferInstance

/-! ### Uniformizers are the irreducible elements -/

/-- **An element of a place is irreducible exactly when it has order `1`.**

Mathlib does not define `Uniformizer` for a DVR, using `Irreducible` instead
(`IsDiscreteValuationRing.irreducible_iff_uniformizer`), so this is the dictionary between that
convention and the order function of `#651`.  It is what makes
`IsDiscreteValuationRing.addVal (placeOf W p)` computable in terms of `divisorProj`, and hence what
connects this file to `Ideal.ramificationIdx`.

The interesting direction is `→`: if `π` generates the maximal ideal then a uniformizer `ρ` is a
multiple of it, `1 = ord ρ = ord c + ord π` with both summands nonnegative and `ord π` positive, so
`ord π = 1`. -/
theorem irreducible_placeOf_iff {p : ProjPoint W} (π : placeOf W p) :
    Irreducible π ↔ divisorProj W (π : W.FunctionField) p = 1 := by
  rw [IsDiscreteValuationRing.irreducible_iff_uniformizer]
  refine ⟨fun h => ?_, fun h => maximalIdeal_placeOf_eq_span π h⟩
  have hπ0 : (π : W.FunctionField) ≠ 0 := by
    intro h0
    refine maximalIdeal_placeOf_ne_bot p ?_
    rw [h, Ideal.span_singleton_eq_bot]
    exact Subtype.ext (by simpa using h0)
  have hpos : 0 < divisorProj W (π : W.FunctionField) p :=
    (mem_maximalIdeal_placeOf_iff hπ0).1 (h ▸ Ideal.mem_span_singleton_self π)
  obtain ⟨ρ, hρ0, hρ⟩ := exists_divisorProj_eq_one p
  have hmem : ρ ∈ placeOf W p :=
    (mem_placeOf_iff_divisorProj_nonneg p hρ0).2 (by rw [hρ]; norm_num)
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1
    (h ▸ (mem_maximalIdeal_placeOf_iff (p := p) (x := ⟨ρ, hmem⟩) hρ0).2 (by rw [hρ]; norm_num))
  have hc0 : (c : W.FunctionField) ≠ 0 := by
    intro h0
    refine hρ0 ?_
    have := congrArg (Subtype.val (p := fun z => z ∈ placeOf W p)) hc
    simpa [h0] using this.symm
  have hsplit : divisorProj W ((c : W.FunctionField) * (π : W.FunctionField)) p = 1 := by
    rw [← hρ]
    exact congrArg (fun z => divisorProj W z p) (congrArg Subtype.val hc)
  rw [divisorProj_mul hc0 hπ0, Finsupp.add_apply] at hsplit
  have := divisorProj_placeOf_nonneg c
  omega

/-! ### Non-vacuity

Everything above carries `[IsDedekindDomain W.CoordinateRing]`, and the headline is an `instance`,
so what has to be committed is that the instance really fires — at a genuine curve, in *both*
branches of `placeOf`, with every side condition discharged by instance search rather than by hand.
`y² = x³ - x` over `ℚ` (discriminant `64`) is the certificate curve `PlaceResidueField.lean`,
`PullbackDivisor.lean` and `MulByTwoPlaceAtInfinity.lean` use; the Dedekind instance follows from
`IsElliptic` alone, and no algebraically closed base field is needed anywhere in this file. -/

section Nonvacuity

/-- The curve `y² = x³ - x` over `ℚ`, of discriminant `64`. -/
private def exampleCurve : Affine ℚ := ⟨0, 0, 0, -1, 0⟩

private instance : exampleCurve.IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero]
  norm_num [exampleCurve, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]

/-- **The place at infinity of a curve that exists is a discrete valuation ring**, by instance
search.  This is the branch of `placeOf` that is *not* a localisation of anything. -/
example : IsDiscreteValuationRing (placeOf exampleCurve none) := inferInstance

/-- **And so is every affine closed point**, by the same instance. -/
example (v : HeightOneSpectrum exampleCurve.CoordinateRing) :
    IsDiscreteValuationRing (placeOf exampleCurve (some v)) := inferInstance

/-- There is at least one affine closed point to say that about, so the `some` branch of the
previous certificate is not vacuous. -/
example : Nonempty (HeightOneSpectrum exampleCurve.CoordinateRing) :=
  nonempty_heightOneSpectrum

/-- The by-products fire too, uniformly in `p`. -/
example (p : ProjPoint exampleCurve) : IsNoetherianRing (placeOf exampleCurve p) :=
  isNoetherianRing_placeOf p

example (p : ProjPoint exampleCurve) : IsPrincipalIdealRing (placeOf exampleCurve p) :=
  inferInstance

/-- **A uniformizer of a curve that exists really is irreducible.**  The dictionary of
`irreducible_placeOf_iff` fired at a place of a genuine curve, with the uniformizer produced by
`exists_divisorProj_eq_one` rather than assumed. -/
example (p : ProjPoint exampleCurve) : ∃ π : placeOf exampleCurve p, Irreducible π := by
  obtain ⟨π, hπ0, hπ⟩ := exists_divisorProj_eq_one p
  exact ⟨⟨π, (mem_placeOf_iff_divisorProj_nonneg p hπ0).2 (by rw [hπ]; norm_num)⟩,
    (irreducible_placeOf_iff _).2 hπ⟩

end Nonvacuity

end WeierstrassCurve.Affine
