/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.Fixtures
import EllipticCurves.FunctionField.PlaceOrder

/-!
# The local ring of a projective place: its maximal ideal, and its residue field

`EllipticCurves.FunctionField.Places` (`#651`) classifies the places of `F(W)` over `F`: every
valuation subring containing `F` and different from `F(W)` is `placeOf W p` for exactly one point
`p` of the projective curve,

```lean
placeOf : ProjPoint W → ValuationSubring W.FunctionField
  | none   => ordInftyValuationSubring W
  | some v => HeightOneSpectrum.valuationSubringAtPrime W.FunctionField v
```

and `EllipticCurves.FunctionField.PlaceOrder` supplies the dictionary between that subring and the
projective divisor: `f ∈ placeOf W p ↔ 0 ≤ divisorProj W f p`, together with a uniformizer at every
place.  This file takes the next step up, from the subring to its **local structure**: the maximal
ideal, which is principal and generated by any uniformizer, and the **residue field**

```lean
residueFieldProj W p := IsLocalRing.ResidueField (placeOf W p)
```

as an `F`-algebra, with the residue degree `residueDegreeProj W p = Module.finrank F κ(p)`.

## Why there is no case split below

A `ValuationSubring` is a local ring on the nose (`ValuationSubring.isLocalRing`), so `κ(p)` is
available uniformly over `ProjPoint W` with no `none` / `some` analysis at all — the two branches
were already reconciled by `placeOf`.  Every proof here runs through the order function instead of
through either branch's construction, so nothing below mentions `ordInfty`, `ord`, `relNorm` or a
localisation.  In particular the residue field at infinity is not built by hand; it is the residue
field of `ordInftyValuationSubring W`, which `#650` produced.

## The convention `ord v 0 = 0`, and the one hypothesis it forces

`WeierstrassCurve.Affine.ord` is `FractionalIdeal.count` of a principal fractional ideal, with the
junk value `ord v 0 = 0` (`Divisors.lean`), hence `divisorProj W 0 p = 0`.  So the naive
characterisation of the maximal ideal — "`x` is in it iff its order is positive" — would say `0`
is a unit.  `mem_maximalIdeal_placeOf_iff` therefore carries `(x : F(W)) ≠ 0`, exactly as
`mem_placeOf_iff_divisorProj_nonneg` does, and `zero_mem` covers the excluded case.  The hypothesis
is about the encoding, not about the mathematics.

## Main results

* **`WeierstrassCurve.Affine.mem_maximalIdeal_placeOf_iff`** — membership of the maximal ideal is
  strict positivity of the order;
* `WeierstrassCurve.Affine.isUnit_placeOf_iff` — dually, a unit of a place is a nonzero function
  of order `0` there;
* **`WeierstrassCurve.Affine.maximalIdeal_placeOf_eq_span`** — the maximal ideal is generated by
  any uniformizer, and `isPrincipal_maximalIdeal_placeOf` is the unconditional consequence, off
  `exists_divisorProj_eq_one`;
* `WeierstrassCurve.Affine.instAlgebraPlaceOf` — `placeOf W p` is an `F`-algebra, because a place
  over `F` contains `F`; this is what makes `κ(p)` an `F`-algebra, through Mathlib's
  `IsLocalRing.ResidueField.algebra`;
* **`WeierstrassCurve.Affine.residueFieldProj`** and `residueDegreeProj`;
* `WeierstrassCurve.Affine.residue_placeOf_eq_zero_iff` — the kernel of the residue map, in order
  terms;
* `WeierstrassCurve.Affine.residueDegreeProj_eq_one_iff_surjective` — degree one is rationality of
  the place, i.e. surjectivity of `algebraMap F κ(p)`.  This is the form the sibling issue that
  proves `residueDegreeProj p = 1` over an algebraically closed base will consume.

## What is *not* here

* **Any value of `residueDegreeProj`.**  Not `= 1`, not finiteness, not even nonzero:
  `Module.finrank` is `0` on an infinite-dimensional module, so `residueDegreeProj W p ≠ 0` is a
  genuine theorem and is not proved.  Computing it needs Zariski's lemma in the affine branch and
  an explicit uniformizer argument at infinity, which is separate work.
* **The identification `κ(some v) ≃ₐ[F] F[W] ⧸ v.asIdeal`.**  Mathlib knows
  `valuationSubringAtPrime` is a localisation of `F[W]` at `v.asIdeal`, so this is available, but it
  belongs with the computation of the degree, not with the definition.
* **Any comparison with `degPt`** (`DivisorDegree.lean`).  `degPt v` is
  `Ideal.natDegreeGenerator (Ideal.relNorm F[X] v.asIdeal)`, a *relative ideal norm to `F[X]`*, not
  a residue-field degree.  Nothing below assumes any relation between the two.
  ⚠️ **This bullet used to end** *"The two agree, and nothing below assumes it."*  The second half
  was and remains true; the first half was an **assertion without a proof**, and it stayed one for
  as long as it stood.  It is now a theorem over **every** base field —
  `degPt_eq_residueDegreeProj` and `degProjPt_eq_residueDegreeProj`
  (`EllipticCurves.FunctionField.PlaceDegreeComparison`).  ⚠️ **A later revision of this bullet
  read** *"It is now a theorem over an algebraically closed base field, both by way of
  `degPt = 1` … ⚠️ Over a general base field it is open, and the obstruction is that Mathlib's
  `Ideal.relNorm_eq_pow_of_isMaximal` carries `[PerfectField (FractionRing R)]`, and `RatFunc F` is
  not perfect in characteristic `p`."*  **The prediction was wrong, though its diagnosis was not**:
  the perfect-field route really is unavailable, and the general comparison goes through
  `Ideal.relNorm_eq_pow_of_isPrime_isGalois` instead, whose Galois hypothesis is
  `EllipticCurves.FunctionField.NegYGalois`'s `isGalois_fractionRing_polynomial`.  ⚠️ The `F̄` route
  *"by way of `degPt = 1`"* is still there, still needs `[IsAlgClosed F]`, and still says strictly
  more where it applies — it computes the common value.  The definition below is deliberately not
  rephrased in terms of `degPt`: the two remain different constructions.
* **`IsDiscreteValuationRing (placeOf W p)`.**  A principal maximal ideal is not that typeclass —
  it wants *every* ideal principal, which is a separate argument off the same order function.  That
  argument is `EllipticCurves.FunctionField.PlaceDiscreteValuationRing` (`#753`), which imports this
  file and supplies the instance uniformly in `p`; `isPrincipal_maximalIdeal_placeOf` below is the
  input it starts from.
* The relative residue degree `[κ(p) : κ(q)]` along `[2]`, the contraction `κ(q) → κ(p)`,
  ramification indices, and the fundamental identity `∑ e_p · f_p = 4`.

Ward-independent, normality-independent, `#418`-independent: `[Field F]` and
`[IsDedekindDomain W.CoordinateRing]` throughout, with no `[W.IsElliptic]` and no `[IsAlgClosed F]`.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.1–II.2.
* Stichtenoth, *Algebraic Function Fields and Codes*, I.1 (the residue field of a place).
-/

open IsDedekindDomain

namespace WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W : Affine F} [IsDedekindDomain W.CoordinateRing]

/-! ### The maximal ideal -/

/-- **A function lies in the maximal ideal of a place exactly when it vanishes there.**

```
x ∈ 𝔪_p  ↔  0 < divisorProj W x p        (for x ≠ 0)
```

The nonvanishing hypothesis is forced by the junk value `divisorProj W 0 p = 0`; see the module
docstring.  Both directions are multiplicativity of the order function: a factorisation `x * y = 1`
inside the place forces `divisorProj W x p ≤ 0`, and conversely order `0` puts `x⁻¹` back in the
place. -/
theorem mem_maximalIdeal_placeOf_iff {p : ProjPoint W} {x : placeOf W p}
    (hx : (x : W.FunctionField) ≠ 0) :
    x ∈ IsLocalRing.maximalIdeal (placeOf W p) ↔ 0 < divisorProj W (x : W.FunctionField) p := by
  have hmem : 0 ≤ divisorProj W (x : W.FunctionField) p :=
    (mem_placeOf_iff_divisorProj_nonneg p hx).1 x.2
  rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff]
  constructor
  · intro hnu
    rcases lt_or_eq_of_le hmem with h | h
    · exact h
    · have hinv : (x : W.FunctionField)⁻¹ ∈ placeOf W p := by
        rw [mem_placeOf_iff_divisorProj_nonneg p (inv_ne_zero hx), divisorProj_inv,
          Finsupp.neg_apply, ← h, neg_zero]
      exact absurd (isUnit_iff_exists_inv.2
        ⟨⟨(x : W.FunctionField)⁻¹, hinv⟩, Subtype.ext (by simpa using mul_inv_cancel₀ hx)⟩) hnu
  · intro hlt hu
    obtain ⟨y, hy⟩ := isUnit_iff_exists_inv.1 hu
    have hxy : (x : W.FunctionField) * (y : W.FunctionField) = 1 := congrArg Subtype.val hy
    have hyne : (y : W.FunctionField) ≠ 0 := by
      intro h
      simp [h] at hxy
    have h0 : divisorProj W ((x : W.FunctionField) * y) p = 0 := by
      rw [hxy, divisorProj_one]
      rfl
    rw [divisorProj_mul hx hyne, Finsupp.add_apply] at h0
    have := (mem_placeOf_iff_divisorProj_nonneg p hyne).1 y.2
    omega

/-- **The maximal ideal of a place is generated by any uniformizer at that place.**

Containment `⊆` divides by `π`: an `x` of positive order has `x / π` of nonnegative order, hence
back in the place, and `(x / π) · π = x`.  Containment `⊇` is that `π` itself lies in the maximal
ideal, since `0 < 1`. -/
theorem maximalIdeal_placeOf_eq_span {p : ProjPoint W} (π : placeOf W p)
    (hπ : divisorProj W (π : W.FunctionField) p = 1) :
    IsLocalRing.maximalIdeal (placeOf W p) = Ideal.span {π} := by
  have hπ0 : (π : W.FunctionField) ≠ 0 := by
    intro h
    rw [h, divisorProj_zero] at hπ
    simp at hπ
  refine le_antisymm (fun x hx => ?_) ?_
  · rcases eq_or_ne (x : W.FunctionField) 0 with h0 | h0
    · have hx0 : x = 0 := Subtype.ext (by simpa using h0)
      simp [hx0]
    · have hpos := (mem_maximalIdeal_placeOf_iff h0).1 hx
      have hq : (x : W.FunctionField) / (π : W.FunctionField) ∈ placeOf W p := by
        rw [mem_placeOf_iff_divisorProj_nonneg p (div_ne_zero h0 hπ0), divisorProj_div h0 hπ0,
          Finsupp.sub_apply, hπ]
        omega
      exact Ideal.mem_span_singleton'.2
        ⟨⟨_, hq⟩, Subtype.ext (by simpa using div_mul_cancel₀ (x : W.FunctionField) hπ0)⟩
  · rw [Ideal.span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    exact (mem_maximalIdeal_placeOf_iff hπ0).2 (by rw [hπ]; norm_num)

/-- **A function is a unit of a place exactly when it is nonzero and has order `0` there.**

The complementary form of `mem_maximalIdeal_placeOf_iff`, in a local ring.  Unlike that lemma this
one needs no nonvanishing hypothesis: `0` is not a unit, and the junk value `divisorProj W 0 p = 0`
is excluded by the left conjunct rather than by a side condition. -/
theorem isUnit_placeOf_iff {p : ProjPoint W} (x : placeOf W p) :
    IsUnit x ↔ (x : W.FunctionField) ≠ 0 ∧ divisorProj W (x : W.FunctionField) p = 0 := by
  rcases eq_or_ne (x : W.FunctionField) 0 with h | h
  · have hx : x = 0 := Subtype.ext h
    simp [hx]
  · have hmem : 0 ≤ divisorProj W (x : W.FunctionField) p :=
      (mem_placeOf_iff_divisorProj_nonneg p h).1 x.2
    rw [← IsLocalRing.notMem_maximalIdeal, mem_maximalIdeal_placeOf_iff h]
    exact ⟨fun hh => ⟨h, by omega⟩, fun hh => by omega⟩

/-- **The maximal ideal of a place is principal.**  A uniformizer exists at every place
(`exists_divisorProj_eq_one`, `#658`), and generates it.

This is *not* yet `IsDiscreteValuationRing (placeOf W p)`, which additionally wants *every* ideal
to be principal.  That is `isDiscreteValuationRing_placeOf`
(`EllipticCurves.FunctionField.PlaceDiscreteValuationRing`, `#753`), proved off this statement and
the same order function; nothing below uses it. -/
theorem isPrincipal_maximalIdeal_placeOf (p : ProjPoint W) :
    (IsLocalRing.maximalIdeal (placeOf W p)).IsPrincipal := by
  obtain ⟨π, hπ0, hπ⟩ := exists_divisorProj_eq_one p
  have hmem : π ∈ placeOf W p :=
    (mem_placeOf_iff_divisorProj_nonneg p hπ0).2 (by rw [hπ]; norm_num)
  exact ⟨⟨⟨π, hmem⟩, by
    rw [maximalIdeal_placeOf_eq_span (⟨π, hmem⟩ : placeOf W p) hπ, Ideal.submodule_span_eq]⟩⟩

/-! ### The place as an `F`-algebra -/

/-- **A place of `F(W)` over `F` is an `F`-algebra**, by `algebraMap_mem_placeOf`.  There is no
such instance in Mathlib: `valuationSubringAtPrime` carries an algebra structure over the *Dedekind
ring* `F[W]`, not over the constant field, and the place at infinity is not a localisation of
anything. -/
noncomputable instance instAlgebraPlaceOf (p : ProjPoint W) : Algebra F (placeOf W p) :=
  ((algebraMap F W.FunctionField).codRestrict _ (algebraMap_mem_placeOf p)).toAlgebra

@[simp]
lemma coe_algebraMap_placeOf (p : ProjPoint W) (c : F) :
    ((algebraMap F (placeOf W p) c : placeOf W p) : W.FunctionField)
      = algebraMap F W.FunctionField c :=
  rfl

instance (p : ProjPoint W) : IsScalarTower F (placeOf W p) W.FunctionField :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

/-! ### The residue field -/

variable (W) in
/-- **The residue field of a place of the projective curve**, `κ(p)`.

An `abbrev`, so that Mathlib's `IsLocalRing.ResidueField` API — the `Field` instance, the residue
map, and the `Algebra F` instance induced by `instAlgebraPlaceOf` — applies with no
re-derivation. -/
abbrev residueFieldProj (p : ProjPoint W) : Type _ :=
  IsLocalRing.ResidueField (placeOf W p)

/-- **The residue map at a place kills exactly the functions that vanish there.**  The kernel form
of `mem_maximalIdeal_placeOf_iff`; the nonvanishing hypothesis is the same one, for the same
reason. -/
theorem residue_placeOf_eq_zero_iff {p : ProjPoint W} {x : placeOf W p}
    (hx : (x : W.FunctionField) ≠ 0) :
    IsLocalRing.residue (placeOf W p) x = 0 ↔ 0 < divisorProj W (x : W.FunctionField) p := by
  rw [IsLocalRing.residue_eq_zero_iff, mem_maximalIdeal_placeOf_iff hx]

/-- The residue map is surjective, being a quotient map. -/
theorem residue_placeOf_surjective (p : ProjPoint W) :
    Function.Surjective (IsLocalRing.residue (placeOf W p)) :=
  Ideal.Quotient.mk_surjective

/-- The constant field embeds in every residue field: a ring homomorphism out of a field into a
nontrivial ring is injective. -/
theorem algebraMap_residueFieldProj_injective (p : ProjPoint W) :
    Function.Injective (algebraMap F (residueFieldProj W p)) :=
  (algebraMap F (residueFieldProj W p)).injective

variable (W) in
/-- **The residue degree of a place over the constant field**, `deg p = [κ(p) : F]`.

⚠️ Nothing below computes this, and it is *not* known to be nonzero here: `Module.finrank` returns
`0` on an infinite-dimensional module, so finiteness is a theorem, not a convention.  It is also
not *definitionally* `degPt` (`DivisorDegree.lean`), which is a relative ideal norm to `F[X]`.

⚠️ **The values agree all the same, over an arbitrary base field**: `degPt_eq_residueDegreeProj` at
an affine place, `degProjPt_eq_residueDegreeProj` at every `p : ProjPoint W`
(`EllipticCurves.FunctionField.PlaceDegreeComparison`).  This sentence used to read *"It is also
**not** `degPt` …"* and stop there — correct about the constructions, and leaving a reader standing
at the definition with no route to the theorem. -/
noncomputable def residueDegreeProj (p : ProjPoint W) : ℕ :=
  Module.finrank F (residueFieldProj W p)

/-- **A place has residue degree one exactly when it is rational**, i.e. when every residue is the
residue of a constant.

This is the shape in which the degree is actually proved to be `1`: over an algebraically closed
base field the surjectivity on the right is what Zariski's lemma delivers in the affine branch, and
what an explicit uniformizer delivers at infinity. -/
theorem residueDegreeProj_eq_one_iff_surjective (p : ProjPoint W) :
    residueDegreeProj W p = 1 ↔ Function.Surjective (algebraMap F (residueFieldProj W p)) := by
  rw [residueDegreeProj, ← Subalgebra.bot_eq_top_iff_finrank_eq_one, eq_top_iff]
  exact ⟨fun h x => Algebra.mem_bot.1 (h Algebra.mem_top),
    fun h _ _ => Algebra.mem_bot.2 (h _)⟩

/-! ### Non-vacuity

Every statement above carries `[IsDedekindDomain W.CoordinateRing]`, and `placeOf` is built from a
classification whose two branches have quite different provenance.  A curve on which the whole
chain elaborates with every instance discharged is therefore committed rather than quoted.
`y² = x³ - x` over `ℚ` has discriminant `64`, and the Dedekind instance follows from `IsElliptic`
alone — no algebraically closed base field is needed.  This is the certificate curve
`PullbackDivisor.lean` and `MulByTwoPlaceAtInfinity.lean` use. -/

section Nonvacuity

/-! The certificate curve `y² = x³ − x` is the shared `EllipticCurves.Fixture.y2EqX3SubX`, whose
single `[CharZero F]` instance also supplies `IsElliptic` here. -/

open EllipticCurves.Fixture

example : IsDedekindDomain (y2EqX3SubX ℚ).CoordinateRing := inferInstance

/-- The residue field at the point at infinity of a curve that exists is a field, and a `ℚ`-algebra
whose structure map is injective — so it is not the zero ring, and `residueDegreeProj` is a degree
of a genuine extension. -/
example : Function.Injective (algebraMap ℚ (residueFieldProj (y2EqX3SubX ℚ) none)) :=
  algebraMap_residueFieldProj_injective none

/-- The maximal ideal at every place of a curve that exists is principal. -/
example (p : ProjPoint (y2EqX3SubX ℚ)) :
    (IsLocalRing.maximalIdeal (placeOf (y2EqX3SubX ℚ) p)).IsPrincipal :=
  isPrincipal_maximalIdeal_placeOf p

/-- On a curve that exists, a uniformizer really does generate the maximal ideal — the hypothesis of
`maximalIdeal_placeOf_eq_span` is satisfiable at every place, not merely stated. -/
example (p : ProjPoint (y2EqX3SubX ℚ)) :
    ∃ π : placeOf (y2EqX3SubX ℚ) p, IsLocalRing.maximalIdeal (placeOf (y2EqX3SubX ℚ) p)
      = Ideal.span {π} := by
  obtain ⟨π, hπ0, hπ⟩ := exists_divisorProj_eq_one p
  exact ⟨⟨π, (mem_placeOf_iff_divisorProj_nonneg p hπ0).2 (by rw [hπ]; norm_num)⟩,
    maximalIdeal_placeOf_eq_span _ hπ⟩

end Nonvacuity

end WeierstrassCurve.Affine
