/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.MulByTwoGalois
import EllipticCurves.FunctionField.PlaceInertiaGeneral
import EllipticCurves.FunctionField.PullbackPrincipalityTwo

/-!
# `[2]∗((S) − (O))` is principal over an arbitrary field, given rational `2`-torsion and a halving

`EllipticCurves.FunctionField.PullbackPrincipalityTwo` discharges `hprin` at `n = 2` — the `#418`
hypothesis of `exists_gS_two` — over an **algebraically closed** base field.  This file replaces
that instance by the two hypotheses it was ever used for:

* `hcard : Nat.card (W.torsion 2) = 4`, i.e. `E[2] ⊆ E(F)`;
* `hP : 2 • P = S` for the `2`-torsion point `S` in question.

Nothing else about `F` is assumed.  The headline
`exists_nsmul_divisor_eq_divisor_mulByTwoEndo_of_card` and its consumer form `exists_gS_two_of_card`
are therefore available over `ℚ`, and the last section exhibits both on a named rational curve.

## ⚠️ What this does *not* do

**It does not discharge `#962`**, and must not be reported as doing so.  `#962` asks for `hprin`
over a field where `E[2]` is *not* rational and `S` has *no* rational halving; reaching that from
here still needs, exactly as `#962`'s ledger says, Mathlib's **finite** Hilbert 90 applied to
`Gal(L/F)` for `L` the field generated by the missing coordinates, plus the descent statement
`L(W⁄L)^{Gal(L/F)} = F(W)` (`#692`'s open divisor/descent half), plus separability of `L/F` in
characteristic `p`.  None of those is here.

What *is* settled is the step that ledger lists as unstarted: **the chain below `hprin` contains no
use of `[IsAlgClosed F]` beyond those two rationality facts.**  `#962`'s first audit conjectured
this and its own self-correction refuted the conjecture, because
`sum_ramificationIdxTwo_eq_four` (`PlaceRamificationInertia`) collapses `∑ e_p · f_p` to `∑ e_p` by
*"every place is rational"*, which is equivalent to the closure.  PR #437's uncollapsed identity is
what makes the counting work without it, and the argument is the one that correction sketched.

## The counting argument, which is the mathematical content

Over the fibre of `[2]∗` above a rational point `S`:

* the four points `P ⊕ R`, `R ∈ E[2]`, are distinct (`projPointOfPoint_add_injective_two` with
  `hcard`), lie in the fibre (`comapProjPointTwo_add_torsion_two`), and each has `f_p = 1` because
  it is rational — `residueDegreeTwo_projPointOfPoint`, which needs no hypothesis on `F`;
* `e_p ≥ 1` everywhere (`ramificationIdxTwo_pos`) and `f_p ≥ 1` everywhere on the fibre
  (`residueDegreeComap_pos` below);
* `∑_{p ↦ q} e_p · f_p = 4` (`sum_ramificationIdxTwo_mul_residueDegreeTwo_of_isSeparable`).

Four terms of a four-term bound already exhaust it, so every `e_p` is `1` and the fibre is exactly
the coset.  ⚠️ **The second bullet is not decoration.**  Without `f_p ≥ 1` a fifth place could sit
in the fibre contributing `0` to the sum, and both the unramifiedness and the fibre description
would fail; `residueDegreeComap_pos` is the one genuinely new lemma in this file and it is what
closes that hole.

## Where the separability comes from

`sum_ramificationIdxTwo_mul_residueDegreeTwo_of_isSeparable` carries
`Algebra.IsSeparable ([2]∗F(W)) F(W)` as a hypothesis.  It is **not** a third hypothesis of the
headline: `MulByTwoGalois`'s Artin sandwich uses `[IsAlgClosed F]` in exactly one place — the count
`card_torsionTwoMul` — so at `hcard` the whole package goes through.  That is
`isSeparable_mulByTwoEndoFieldRange_of_card` below, and the headline discharges it internally.

⚠️ The characteristic-zero route `isSeparable_mulByTwoEndoFieldRange`
(`EllipticCurves.FunctionField.PlaceBelowIntegralClosure`) would also serve over `ℚ`, and is *not*
used: it would put `[CharZero F]` into statements that do not need it.  `hcard` is the weaker
hypothesis and it is already present.

## ⚠️ `Nat.card (W.torsion 2)` is indexed by a `DecidableEq F` instance

`torsion` is defined with `[DecidableEq F]` (`EllipticCurves.Torsion.Defs`), while
`TorsionTwoMul W` (`EllipticCurves.FunctionField.TranslationAction`) bakes in the classical one.
The statements here follow `MulByTwoFibreAffine` and `PullbackPrincipalityTwo` and take the
**binder**, which is the right choice for a *producer* — every statement below takes `hcard` as
input, so a caller supplies it at whatever instance it holds.  The single `convert` that bridges the
two lives inside `card_torsionTwoMul_of_card` and nowhere else.

## Main statements

* `WeierstrassCurve.Affine.residueDegreeComap_pos` — `f_p > 0` for a place in the fibre of an
  arbitrary `φ`, over an arbitrary field.  Mathlib's `Ideal.inertiaDeg_pos` through PR #437's
  `ideal_inertiaDeg_eq_residueDegreeComap`.
* `…CoordinateRing.isSeparable_mulByTwoEndoFieldRange_of_card` — the Galois package at `hcard`.
* `…CoordinateRing.ramificationIdxTwo_eq_one_of_card`,
  `…CoordinateRing.fibre_comapProjPointTwo_eq_range_of_card` — the fibre over a rational point,
  described without an algebraic closure.
* **`WeierstrassCurve.Affine.exists_nsmul_divisor_eq_divisor_mulByTwoEndo_of_card`** — `hprin` at
  `n = 2`, over an arbitrary field.
* **`WeierstrassCurve.Affine.exists_gS_two_of_card`** — rung 5 at `n = 2`, over an arbitrary field.

`Recovery` derives the merged `exists_nsmul_divisor_eq_divisor_mulByTwoEndo` and
`exists_gS_two_of_isAlgClosed` from these, by supplying `card_torsion_two` and
`exists_nsmul_two_eq`.  `Nonvacuity` instantiates the headline over `ℚ` on
`y² = x³ + 5x² + 4x`, with both hypotheses proved.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.8.
-/

open Module IsLocalRing IsDedekindDomain IsDedekindDomain.HeightOneSpectrum

namespace WeierstrassCurve.Affine

/-! ### Positivity of the relative residue degree -/

section Positivity

variable {F : Type*} [Field F] {W : Affine F} [IsDedekindDomain W.CoordinateRing]
  {φ : W.FunctionField →+* W.FunctionField} {q : ProjPoint W}
  (hφF : ∀ c : F, φ (algebraMap F W.FunctionField c) = algebraMap F W.FunctionField c)
  (hφint : ∀ z : W.FunctionField, φ.IsIntegralElem z)
  [Module.Finite ↥φ.fieldRange W.FunctionField]
  [Algebra.IsSeparable ↥φ.fieldRange W.FunctionField]

include hφF hφint in
/-- **The relative residue degree at a place of the fibre is positive**, over an arbitrary field.

`residueDegreeComap` is a `finrank`, so it is `0` when the residue extension is
infinite-dimensional; that this does not happen is Mathlib's `Ideal.inertiaDeg_pos`, transported by
PR #437's `ideal_inertiaDeg_eq_residueDegreeComap`.

⚠️ This is the lemma that lets a count inside a fibre conclude anything from a term being zero.  The
merged `[IsAlgClosed F]` route never needed it, because there every `f_p` is `1` outright
(`residueDegreeProj_eq_one`); over an arbitrary field the `f_p` are unknown and only their
positivity is available. -/
theorem residueDegreeComap_pos {p : ProjPoint W} (hp : comapProjPoint hφF hφint p = q) :
    0 < residueDegreeComap hφF hφint p := by
  obtain ⟨v, hv⟩ := exists_projPointOfHeightOne_eq hφF hφint hp
  haveI : v.asIdeal.LiesOver (maximalIdeal ↥(placeBelow φ q)) :=
    ⟨((comapProjPoint_projPointOfHeightOne_eq_iff hφF hφint v).1 (by rw [hv]; exact hp)).symm⟩
  haveI : Module.Finite ↥(placeBelow φ q)
      ↥(integralClosure ↥(placeBelow φ q) W.FunctionField) :=
    module_finite_integralClosure_placeBelow q
  haveI : v.asIdeal.IsPrime := v.isPrime
  rw [← hv, ← ideal_inertiaDeg_eq_residueDegreeComap hφF hφint v]
  exact Ideal.inertiaDeg_pos v.asIdeal ↥(placeBelow φ q)

end Positivity

variable {F : Type*} [Field F] {W : Affine F} [IsDedekindDomain W.CoordinateRing]
  [DecidableEq F] [W.IsElliptic]

namespace CoordinateRing

/-! ### The Galois package at a rational `E[2]`

`MulByTwoGalois` proves `Fixed(E[2]) = [2]∗F(W)` — hence separability — over `F̄`, and uses the
closure only to know `|E[2]| = 4`.  These are the same four statements with that count taken as a
hypothesis. -/

omit [IsDedekindDomain W.CoordinateRing] [W.IsElliptic] in
/-- **`|E[2]| = 4` in the multiplicative packaging**, from the count rather than from the closure.
This is `card_torsionTwoMul` (`EllipticCurves.FunctionField.TranslationAction`) with `hcard` in
place of `[IsAlgClosed F]`.

⚠️ The `convert` is the whole `DecidableEq` bridge of this file: `TorsionTwoMul W` bakes in
`Classical.propDecidable` while `hcard` is stated at the ambient binder, and the two are
propositionally but not syntactically equal.  It is discharged by `Subsingleton.elim`. -/
theorem card_torsionTwoMul_of_card (hcard : Nat.card (W.torsion 2) = 4) :
    Nat.card (TorsionTwoMul W) = 4 :=
  (Nat.card_congr Multiplicative.toAdd).trans (by convert hcard)

omit [IsDedekindDomain W.CoordinateRing] [W.IsElliptic] in
/-- `E[2]` is finite once it has four elements. -/
theorem finite_torsionTwoMul_of_card (hcard : Nat.card (W.torsion 2) = 4) :
    Finite (TorsionTwoMul W) :=
  Nat.finite_of_card_ne_zero (by rw [card_torsionTwoMul_of_card hcard]; omega)

omit [IsDedekindDomain W.CoordinateRing] in
open Classical in
/-- **Artin's theorem for the translation action**, at a rational `E[2]`: `[F(W) : Fixed(E[2])] =
4`. `finrank_fixedFieldTwo` with `hcard` in place of `[IsAlgClosed F]`; the proof is unchanged. -/
theorem finrank_fixedFieldTwo_of_card (hcard : Nat.card (W.torsion 2) = 4) :
    finrank ↥(fixedFieldTwo W) W.FunctionField = 4 := by
  haveI := finite_torsionTwoMul_of_card hcard
  haveI : Fintype (TorsionTwoMul W) := Fintype.ofFinite _
  have h : finrank ↥(FixedPoints.subfield (TorsionTwoMul W) W.FunctionField) W.FunctionField
      = 4 := by
    rw [FixedPoints.finrank_eq_card (TorsionTwoMul W) W.FunctionField, ← Nat.card_eq_fintype_card,
      card_torsionTwoMul_of_card hcard]
  exact h

omit [IsDedekindDomain W.CoordinateRing] in
open Classical in
/-- **`Fixed(E[2]) = [2]∗F(W)` at a rational `E[2]`.**  The sandwich of
`fixedFieldTwo_eq_mulByTwoFieldRange`: both outer degrees are `4`, the inner inclusion is `#758`'s,
and `IntermediateField.eq_of_le_of_finrank_eq'` closes it.  `finrank_mulByTwoFieldRange` (`#682`)
never needed a closure. -/
theorem fixedFieldTwo_eq_mulByTwoFieldRange_of_card (h2 : (2 : F) ≠ 0)
    (hcard : Nat.card (W.torsion 2) = 4) :
    (mulByTwoEndoAlgHom (W := W) h2).fieldRange = fixedFieldTwo W := by
  have hdeg : finrank ↥(mulByTwoEndoAlgHom (W := W) h2).fieldRange W.FunctionField = 4 :=
    finrank_mulByTwoFieldRange h2
  haveI : FiniteDimensional ↥(mulByTwoEndoAlgHom (W := W) h2).fieldRange W.FunctionField :=
    Module.finite_of_finrank_pos (by rw [hdeg]; norm_num)
  refine IntermediateField.eq_of_le_of_finrank_eq' ?_
    (by rw [hdeg, finrank_fixedFieldTwo_of_card hcard])
  rintro _ ⟨f, rfl⟩
  exact mulByTwoEndo_mem_fixedPoints h2 f

omit [IsDedekindDomain W.CoordinateRing] in
open Classical in
/-- **`F(W) / [2]∗F(W)` is separable at a rational `E[2]`**, in the `IntermediateField`
presentation. -/
theorem isSeparable_mulByTwoFieldRange_of_card (h2 : (2 : F) ≠ 0)
    (hcard : Nat.card (W.torsion 2) = 4) :
    Algebra.IsSeparable ↥(mulByTwoEndoAlgHom (W := W) h2).fieldRange W.FunctionField := by
  haveI := finite_torsionTwoMul_of_card hcard
  haveI : Algebra.IsSeparable ↥(fixedFieldTwo W) W.FunctionField := inferInstanceAs
    (Algebra.IsSeparable ↥(FixedPoints.subfield (TorsionTwoMul W) W.FunctionField) W.FunctionField)
  rw [fixedFieldTwo_eq_mulByTwoFieldRange_of_card h2 hcard]
  infer_instance

omit [IsDedekindDomain W.CoordinateRing] in
open Classical in
/-- **Separability in the `Subfield` presentation**, which is the one the fibre count consumes.
Carried across `mulByTwoFieldRangeEquivSubfield`, the identity on elements. -/
theorem isSeparable_mulByTwoEndoFieldRange_of_card (h2 : (2 : F) ≠ 0)
    (hcard : Nat.card (W.torsion 2) = 4) :
    Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField := by
  haveI := isSeparable_mulByTwoFieldRange_of_card h2 hcard
  exact Algebra.IsSeparable.of_equiv_equiv (mulByTwoFieldRangeEquivSubfield h2)
    (RingEquiv.refl W.FunctionField) (by ext a; rfl)

/-! ### The fibre over a rational point, without an algebraic closure -/

omit [DecidableEq F] in
/-- `f_p > 0` for `[2]∗` at a place of a fibre — the instantiation of `residueDegreeComap_pos`. -/
theorem residueDegreeTwo_pos_of_isSeparable (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    {p q : ProjPoint W} (hp : comapProjPointTwo h2 p = q) : 0 < residueDegreeTwo h2 p := by
  haveI := module_finite_mulByTwoEndoFieldRange (W := W) h2
  haveI := hsep
  exact residueDegreeComap_pos (mulByTwoEndo_algebraMap_base h2)
    (mulByTwoEndo_isIntegralElem h2) hp

omit [DecidableEq F] in
/-- Every summand of the fundamental identity is at least `1`, which is what turns a sum of `4` into
a bound on the number of places.  Both factors are positive: `e_p` by `ramificationIdxTwo_pos` and
`f_p` by the previous lemma. -/
theorem one_le_ramificationIdxTwo_mul_residueDegreeTwo (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    {p q : ProjPoint W} (hp : comapProjPointTwo h2 p = q) :
    1 ≤ (ramificationIdxTwo h2 p).toNat * residueDegreeTwo h2 p := by
  have he : 0 < (ramificationIdxTwo h2 p).toNat := by
    have := ramificationIdxTwo_pos h2 p; omega
  have hf := residueDegreeTwo_pos_of_isSeparable h2 hsep hp
  exact Nat.one_le_iff_ne_zero.2 (Nat.mul_ne_zero (by omega) (by omega))

omit [DecidableEq F] in
/-- **At most four places lie above any place of `[2]∗F(W)`**, over an arbitrary field.

`card_fibre_comapProjPointTwo_le_four` (`PlaceRamificationInertia`) is this bound over `F̄`, where
it comes from the collapsed `∑ e_p = 4`.  Here it comes from the uncollapsed `∑ e_p · f_p = 4`,
whose summands are bounded below by `1` for the two independent reasons above. -/
theorem card_fibre_comapProjPointTwo_le_four_of_isSeparable (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (q : ProjPoint W) :
    (finite_comapProjPointTwo_preimage_singleton h2 q).toFinset.card ≤ 4 := by
  rw [Finset.card_eq_sum_ones,
    ← sum_ramificationIdxTwo_mul_residueDegreeTwo_of_isSeparable h2 hsep q]
  refine Finset.sum_le_sum fun p hp => ?_
  have hmem : comapProjPointTwo h2 p = q :=
    (Set.Finite.mem_toFinset (finite_comapProjPointTwo_preimage_singleton h2 q)).1 hp
  exact one_le_ramificationIdxTwo_mul_residueDegreeTwo h2 hsep hmem

/-- **The fibre of `[2]` over a rational point has exactly four elements**, over an arbitrary field.

`≤ 4` is the previous lemma; `≥ 4` is the coset `{ P ⊕ R : R ∈ E[2] }`, four distinct elements of
the fibre by `hcard` and `projPointOfPoint_add_injective_two`.

This is `card_fibre_comapProjPointTwo_projPointOfPoint` (`MulByTwoFibreAffine`) with `hcard` and
`hP` replacing `card_torsion_two` and `exists_nsmul_two_eq`. -/
theorem card_fibre_comapProjPointTwo_projPointOfPoint_of_card (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) :
    (finite_comapProjPointTwo_preimage_singleton h2 (projPointOfPoint W S)).toFinset.card = 4 := by
  classical
  haveI := W.finite_torsion_two (F := F) h2
  haveI := Fintype.ofFinite (W.torsion 2)
  refine le_antisymm (card_fibre_comapProjPointTwo_le_four_of_isSeparable h2 hsep _) ?_
  have hc : Fintype.card (W.torsion 2) = 4 := by rw [← Nat.card_eq_fintype_card, hcard]
  rw [← hc, ← Finset.card_univ]
  exact Finset.card_le_card_of_injOn (fun R => projPointOfPoint W (P + R))
    (fun R _ => (Set.Finite.mem_toFinset _).2 (comapProjPointTwo_add_torsion_two h2 hP R))
    (Set.injOn_of_injective (projPointOfPoint_add_injective_two P))

/-- **The fibre of `[2]` over a rational point *is* the coset `{ P ⊕ R : R ∈ E[2] }`**, over an
arbitrary field.  Four distinct elements inside a four-element set; no further geometry, exactly as
in `fibre_comapProjPointTwo_eq_range`. -/
theorem fibre_comapProjPointTwo_eq_range_of_card (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) :
    comapProjPointTwo h2 ⁻¹' {projPointOfPoint W S}
      = Set.range fun R : W.torsion 2 => projPointOfPoint W (P + R) := by
  classical
  haveI := W.finite_torsion_two h2
  haveI := Fintype.ofFinite (W.torsion 2)
  have hfin := finite_comapProjPointTwo_preimage_singleton h2 (projPointOfPoint W S)
  have hsub : (Set.range fun R : W.torsion 2 => projPointOfPoint W (P + R))
      ⊆ comapProjPointTwo h2 ⁻¹' {projPointOfPoint W S} := by
    rintro p ⟨R, rfl⟩
    exact comapProjPointTwo_add_torsion_two h2 hP R
  refine (Set.eq_of_subset_of_ncard_le hsub ?_ hfin).symm
  have h1 : (comapProjPointTwo h2 ⁻¹' {projPointOfPoint W S}).ncard = 4 := by
    rw [Set.ncard_eq_toFinset_card _ hfin]
    exact card_fibre_comapProjPointTwo_projPointOfPoint_of_card h2 hsep hcard hP
  have h2' : (Set.range fun R : W.torsion 2 => projPointOfPoint W (P + R)).ncard = 4 := by
    rw [← Nat.card_coe_set_eq, Nat.card_range_of_injective (projPointOfPoint_add_injective_two P),
      hcard]
  omega

/-- **`[2]` is unramified over a rational point**, over an arbitrary field.

Four terms of the fibre sum are already `≥ 1` each and the sum is `4`, so the term at `p` is `1`;
being a product of two positive naturals it forces `e_p = 1`.

⚠️ Compare `ramificationIdxTwo_eq_one_of_comapProjPointTwo_eq_projPointOfPoint`, which reads the
same conclusion off the *collapsed* identity and is `F̄`-only for that reason.  The extra hypotheses
here are exactly the two rationality facts; `hsep` is not a third, see the module docstring. -/
theorem ramificationIdxTwo_eq_one_of_card (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {p : ProjPoint W} {S P : W.Point} (hP : 2 • P = S)
    (hp : comapProjPointTwo h2 p = projPointOfPoint W S) :
    ramificationIdxTwo h2 p = 1 := by
  classical
  have hfin := finite_comapProjPointTwo_preimage_singleton h2 (projPointOfPoint W S)
  set s := hfin.toFinset with hs
  have hmemfib : ∀ r ∈ s, comapProjPointTwo h2 r = projPointOfPoint W S := fun r hr =>
    (Set.Finite.mem_toFinset hfin).1 hr
  have hmem : p ∈ s := (Set.Finite.mem_toFinset hfin).2 hp
  have hcards : s.card = 4 :=
    card_fibre_comapProjPointTwo_projPointOfPoint_of_card h2 hsep hcard hP
  have hsum : ∑ r ∈ s, (ramificationIdxTwo h2 r).toNat * residueDegreeTwo h2 r = 4 :=
    sum_ramificationIdxTwo_mul_residueDegreeTwo_of_isSeparable h2 hsep _
  have hsplit : (ramificationIdxTwo h2 p).toNat * residueDegreeTwo h2 p
      + ∑ r ∈ s.erase p, (ramificationIdxTwo h2 r).toNat * residueDegreeTwo h2 r = 4 := by
    rw [Finset.add_sum_erase _
      (fun r => (ramificationIdxTwo h2 r).toNat * residueDegreeTwo h2 r) hmem]
    exact hsum
  have hlow : (s.erase p).card
      ≤ ∑ r ∈ s.erase p, (ramificationIdxTwo h2 r).toNat * residueDegreeTwo h2 r := by
    simpa using Finset.card_nsmul_le_sum (s.erase p)
      (fun r => (ramificationIdxTwo h2 r).toNat * residueDegreeTwo h2 r) 1
      (fun r hr => one_le_ramificationIdxTwo_mul_residueDegreeTwo h2 hsep
        (hmemfib r (Finset.mem_of_mem_erase hr)))
  have hec : (s.erase p).card = 3 := by rw [Finset.card_erase_of_mem hmem, hcards]
  have hprod : 1 ≤ (ramificationIdxTwo h2 p).toNat * residueDegreeTwo h2 p :=
    one_le_ramificationIdxTwo_mul_residueDegreeTwo h2 hsep hp
  set k := (ramificationIdxTwo h2 p).toNat * residueDegreeTwo h2 p with hk
  have hone : k = 1 := by omega
  have hE : (ramificationIdxTwo h2 p).toNat = 1 :=
    Nat.eq_one_of_mul_eq_one_right (hk.symm.trans hone)
  have hepos := ramificationIdxTwo_pos h2 p
  omega

/-! ### The fibre description of `[2]∗` -/

/-- **`[2]∗(S) = ∑_{p ↦ S} (p)`, every coefficient `1`**, over an arbitrary field: the previous
lemma read into the definition of `pullbackDivisorTwo`. -/
theorem pullbackDivisorTwo_single_projPointOfPoint_of_card (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) :
    pullbackDivisorTwo h2 (Finsupp.single (projPointOfPoint W S) (1 : ℤ))
      = ∑ p ∈ (finite_comapProjPointTwo_preimage_singleton h2
          (projPointOfPoint W S)).toFinset, Finsupp.single p (1 : ℤ) := by
  classical
  ext q
  have hrhs : (∑ p ∈ (finite_comapProjPointTwo_preimage_singleton h2
        (projPointOfPoint W S)).toFinset, Finsupp.single p (1 : ℤ)) q
      = if comapProjPointTwo h2 q = projPointOfPoint W S then 1 else 0 := by
    rw [Finset.sum_apply', Finset.sum_congr rfl fun p _ => Finsupp.single_apply,
      Finset.sum_ite_eq' _ q fun _ => (1 : ℤ)]
    simp only [Set.Finite.mem_toFinset, Set.mem_preimage, Set.mem_singleton_iff]
  rw [pullbackDivisorTwo_apply, hrhs]
  by_cases hq : comapProjPointTwo h2 q = projPointOfPoint W S
  · rw [hq, Finsupp.single_eq_same, mul_one,
      ramificationIdxTwo_eq_one_of_card h2 hsep hcard hP hq, if_pos rfl]
  · rw [Finsupp.single_apply, if_neg fun hc => hq hc.symm, mul_zero, if_neg hq]

/-- **`[2]∗(S) = ∑_{R ∈ E[2]} (P ⊕ R)`** for any `P` with `2 • P = S`, over an arbitrary field.
`#774`'s formula in the shape `#418` consumes it, with the closure removed.

The `[Fintype (W.torsion 2)]` is carried in the statement for the reason `#763` gives: the sum
cannot be written without it, and `Fintype.ofFinite` in a statement is a noncomputable leak. -/
theorem pullbackDivisorTwo_single_eq_sum_torsion_of_card [Fintype (W.torsion 2)]
    (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) :
    pullbackDivisorTwo h2 (Finsupp.single (projPointOfPoint W S) (1 : ℤ))
      = ∑ R : W.torsion 2, Finsupp.single (projPointOfPoint W (P + R)) (1 : ℤ) := by
  classical
  ext q
  rw [pullbackDivisorTwo_apply, Finset.sum_apply',
    Finset.sum_congr rfl fun R _ => Finsupp.single_apply]
  by_cases hq : comapProjPointTwo h2 q = projPointOfPoint W S
  · obtain ⟨R₀, hR₀⟩ : q ∈ Set.range fun R : W.torsion 2 => projPointOfPoint W (P + R) := by
      rw [← fibre_comapProjPointTwo_eq_range_of_card h2 hsep hcard hP]; exact hq
    rw [hq, Finsupp.single_eq_same, mul_one,
      ramificationIdxTwo_eq_one_of_card h2 hsep hcard hP hq,
      Finset.sum_eq_single R₀ (fun R _ hRne => if_neg fun hc =>
        hRne (projPointOfPoint_add_injective_two P (hc.trans hR₀.symm)))
      (fun hc => absurd (Finset.mem_univ R₀) hc), if_pos hR₀]
  · rw [Finsupp.single_apply, if_neg fun hc => hq hc.symm, mul_zero, Finset.sum_eq_zero]
    intro R _
    refine if_neg fun hc => hq ?_
    rw [← hc]
    exact comapProjPointTwo_add_torsion_two h2 hP R

end CoordinateRing

/-! ### Principality of `[2]∗((S) − (O))` -/

open CoordinateRing

/-- **`[2]∗((S) − (O)) = ∑_{R ∈ E[2]} ((P ⊕ R) − (R))`**, over an arbitrary field.  The `(O)` half
is the same theorem at `S = O` with `P = O`, since `projPointOfPoint W 0` is `none` by `rfl`. -/
theorem pullbackDivisorTwo_single_sub_single_eq_sum_torsion_of_card [Fintype (W.torsion 2)]
    (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) :
    pullbackDivisorTwo h2 (Finsupp.single (projPointOfPoint W S) (1 : ℤ)
        - Finsupp.single (none : ProjPoint W) (1 : ℤ))
      = ∑ R : W.torsion 2, (Finsupp.single (projPointOfPoint W (P + R)) (1 : ℤ)
          - Finsupp.single (projPointOfPoint W (R : W.Point)) (1 : ℤ)) := by
  have hO : (none : ProjPoint W) = projPointOfPoint W 0 := rfl
  rw [map_sub, pullbackDivisorTwo_single_eq_sum_torsion_of_card h2 hsep hcard hP, hO,
    pullbackDivisorTwo_single_eq_sum_torsion_of_card h2 hsep hcard (smul_zero 2),
    ← Finset.sum_sub_distrib]
  exact Finset.sum_congr rfl fun R _ => by rw [zero_add]

/-- The same formula on the affine chart, where `hprin` lives; each `(O)` drops out. -/
theorem affinePart_pullbackDivisorTwo_single_sub_single_of_card [Fintype (W.torsion 2)]
    (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) :
    affinePart W (pullbackDivisorTwo h2 (Finsupp.single (projPointOfPoint W S) (1 : ℤ)
        - Finsupp.single (none : ProjPoint W) (1 : ℤ)))
      = ∑ R : W.torsion 2, (pointDivisorAff W (P + R) - pointDivisorAff W (R : W.Point)) := by
  rw [pullbackDivisorTwo_single_sub_single_eq_sum_torsion_of_card h2 hsep hcard hP, map_sum]
  exact Finset.sum_congr rfl fun R _ => map_sub _ _ _

/-- **The class-group computation**, over an arbitrary field:

```
∑_R toClass (P ⊕ R) − ∑_R toClass R = 4 • toClass P = toClass (4 • P) = toClass (2 • S) = 0.
```

The count of summands is `hcard` here rather than `card_torsion_two`; nothing else changes, and in
particular no step divides a divisor by `2`. -/
theorem classOfDivisor_affinePart_pullbackDivisorTwo_eq_one_of_card (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) (hS : 2 • S = 0) :
    classOfDivisor W.FunctionField (affinePart W (pullbackDivisorTwo h2
        (Finsupp.single (projPointOfPoint W S) (1 : ℤ)
          - Finsupp.single (none : ProjPoint W) (1 : ℤ)))) = 1 := by
  classical
  haveI := W.finite_torsion_two h2
  haveI : Fintype (W.torsion 2) := Fintype.ofFinite _
  have hP4 : (4 : ℕ) • P = 0 := by
    rw [show (4 : ℕ) = 2 * 2 from rfl, mul_smul, hP, hS]
  have hterm : ∀ R ∈ (Finset.univ : Finset (W.torsion 2)),
      classOfDivisor W.FunctionField (pointDivisorAff W (P + R) - pointDivisorAff W (R : W.Point))
        = Additive.toMul (Point.toClass P) := by
    intro R _
    rw [classOfDivisor_sub, classOfDivisor_pointDivisorAff, classOfDivisor_pointDivisorAff,
      map_add, toMul_add, mul_div_cancel_right]
  have hc : Fintype.card (W.torsion 2) = 4 := by
    rw [← Nat.card_eq_fintype_card, hcard]
  rw [affinePart_pullbackDivisorTwo_single_sub_single_of_card h2 hsep hcard hP, classOfDivisor_sum,
    Finset.prod_congr rfl hterm, Finset.prod_const, Finset.card_univ, hc, ← toMul_nsmul,
    ← map_nsmul, hP4, Point.toClass_zero]
  rfl

/-- **`[2]∗((S) − (O))` is principal on the affine chart**, over an arbitrary field: the vanishing
class above turned back into a generator by `#726`'s criterion, which never needed a closure. -/
theorem exists_divisor_eq_affinePart_pullbackDivisorTwo_of_card (h2 : (2 : F) ≠ 0)
    (hsep : Algebra.IsSeparable ↥(mulByTwoEndo (W := W) h2).fieldRange W.FunctionField)
    (hcard : Nat.card (W.torsion 2) = 4) {S P : W.Point} (hP : 2 • P = S) (hS : 2 • S = 0) :
    ∃ g : W.FunctionField, g ≠ 0 ∧ divisor W g = affinePart W (pullbackDivisorTwo h2
      (Finsupp.single (projPointOfPoint W S) (1 : ℤ)
        - Finsupp.single (none : ProjPoint W) (1 : ℤ))) :=
  (exists_divisor_eq_iff_classOfDivisor_eq_one _).2
    (classOfDivisor_affinePart_pullbackDivisorTwo_eq_one_of_card h2 hsep hcard hP hS)

/-- **`hprin` at `n = 2` over an arbitrary field**, in the shape `exists_gS_two` consumes it: for a
nonsingular `2`-torsion point `S` on a curve whose `2`-torsion is rational and which has a halving
point `P` with `[2]P = S`, the pullback `[2]∗((S) − (O))` is twice a principal divisor.

⚠️ `hsep` is discharged internally from `hcard`; the hypotheses are `hcard` and `hP` and nothing
else about `F`.  ⚠️ This is **not** `#962` — see the module docstring for what still stands between
this and `hprin` over a field where those two facts fail. -/
theorem exists_nsmul_divisor_eq_divisor_mulByTwoEndo_of_card (h2 : (2 : F) ≠ 0)
    (hcard : Nat.card (W.torsion 2) = 4) {x y : F}
    (h : W.Nonsingular x y) (hS : Point.some x y h ∈ W.torsion 2)
    {P : W.Point} (hP : 2 • P = Point.some x y h)
    {f : W.FunctionField} (hf : f ≠ 0)
    (hfdiv : divisor W f = Finsupp.single (pointClosedPoint h.left) (2 : ℤ)) :
    ∃ g₀ : W.FunctionField, g₀ ≠ 0 ∧ 2 • divisor W g₀ = divisor W (mulByTwoEndo h2 f) := by
  classical
  have hsep := isSeparable_mulByTwoEndoFieldRange_of_card h2 hcard
  obtain ⟨g, hg, hgdiv⟩ :=
    exists_divisor_eq_affinePart_pullbackDivisorTwo_of_card h2 hsep hcard hP
      (mem_torsion_iff.mp hS)
  refine ⟨g, hg, ?_⟩
  obtain ⟨f₀, hf₀, hproj₀⟩ := divisorProj_eq_single_sub_single_of_torsion h hS
  have hd₀ : divisor W f₀ = Finsupp.single (pointClosedPoint h.left) (2 : ℤ) := by
    ext v
    have hv := congrArg (fun D => D (some v)) hproj₀
    simpa [Finsupp.single_apply] using hv
  have hfe : divisor W f = divisor W f₀ := hfdiv.trans hd₀.symm
  have hprojf : divisorProj W f = divisorProj W f₀ :=
    divisorProj_eq_iff.2 ⟨hfe, ordInfty_eq_of_divisor_eq hf hf₀ hfe⟩
  have hkey : divisorProj W (mulByTwoEndo h2 f)
      = (2 : ℤ) • pullbackDivisorTwo h2
          (Finsupp.single (projPointOfPoint W (Point.some x y h)) (1 : ℤ)
            - Finsupp.single (none : ProjPoint W) (1 : ℤ)) := by
    rw [divisorProj_mulByTwoEndo h2 hf, hprojf, hproj₀, ← pullbackDivisorTwo_zsmul]
    congr 1
    rw [smul_sub, Finsupp.smul_single, Finsupp.smul_single, smul_eq_mul, mul_one,
      projPointOfPoint_some]
    norm_num
  have hdiv2 : divisor W (mulByTwoEndo h2 f) = (2 : ℤ) • affinePart W (pullbackDivisorTwo h2
      (Finsupp.single (projPointOfPoint W (Point.some x y h)) (1 : ℤ)
        - Finsupp.single (none : ProjPoint W) (1 : ℤ))) := by
    rw [← affinePart_divisorProj, hkey, map_zsmul]
  rw [hdiv2, hgdiv, two_nsmul, two_zsmul]

/-- **Rung 5 of the Weil pairing at `n = 2`, over an arbitrary field.**  `exists_gS_two` with its
`hprin` discharged from `hcard` and `hP`: there are a principal `f_S` with `div f_S = 2·(S)` and a
nonzero `g_S` with `u · g_S ^ 2 = [2]∗ f_S` for a unit `u` of `F[W]`.

`exists_gS_two_of_isAlgClosed` (`PullbackPrincipalityTwo`) is this statement over `F̄`, where both
hypotheses are theorems; the `Recovery` section below derives it from this one. -/
theorem exists_gS_two_of_card (h2 : (2 : F) ≠ 0) (hcard : Nat.card (W.torsion 2) = 4) {x y : F}
    (h : W.Nonsingular x y) (hS : Point.some x y h ∈ W.torsion 2)
    {P : W.Point} (hP : 2 • P = Point.some x y h) :
    ∃ f : W.FunctionField, f ≠ 0 ∧
      divisor W f = Finsupp.single (pointClosedPoint h.left) (2 : ℤ) ∧
      ∃ gS : W.FunctionField, gS ≠ 0 ∧
        ∃ u : W.CoordinateRingˣ, (u : W.CoordinateRing) • gS ^ 2 = mulByTwoEndo h2 f :=
  exists_gS_two h2 h hS fun _ hf hfdiv =>
    exists_nsmul_divisor_eq_divisor_mulByTwoEndo_of_card h2 hcard h hS hP hf hfdiv

/-! ### Recovery of the merged algebraically closed statements

`#907`'s rule.  Over `F̄` both hypotheses are theorems — `card_torsion_two` and
`exists_nsmul_two_eq` — so the merged headlines come straight back out.  Both are `private`: a
public copy would duplicate a merged name. -/

section Recovery

variable [IsAlgClosed F]

/-- `exists_nsmul_divisor_eq_divisor_mulByTwoEndo`
(`EllipticCurves.FunctionField.PullbackPrincipalityTwo`), recovered. -/
private theorem exists_nsmul_divisor_eq_divisor_mulByTwoEndo_of_general (h2 : (2 : F) ≠ 0)
    {x y : F} (h : W.Nonsingular x y) (hS : Point.some x y h ∈ W.torsion 2)
    {f : W.FunctionField} (hf : f ≠ 0)
    (hfdiv : divisor W f = Finsupp.single (pointClosedPoint h.left) (2 : ℤ)) :
    ∃ g₀ : W.FunctionField, g₀ ≠ 0 ∧ 2 • divisor W g₀ = divisor W (mulByTwoEndo h2 f) :=
  let ⟨_, hP⟩ := exists_nsmul_two_eq h2 (Point.some x y h)
  exists_nsmul_divisor_eq_divisor_mulByTwoEndo_of_card h2 (card_torsion_two h2) h hS hP hf hfdiv

/-- `exists_gS_two_of_isAlgClosed`
(`EllipticCurves.FunctionField.PullbackPrincipalityTwo`), recovered. -/
private theorem exists_gS_two_of_isAlgClosed_of_general (h2 : (2 : F) ≠ 0) {x y : F}
    (h : W.Nonsingular x y) (hS : Point.some x y h ∈ W.torsion 2) :
    ∃ f : W.FunctionField, f ≠ 0 ∧
      divisor W f = Finsupp.single (pointClosedPoint h.left) (2 : ℤ) ∧
      ∃ gS : W.FunctionField, gS ≠ 0 ∧
        ∃ u : W.CoordinateRingˣ, (u : W.CoordinateRing) • gS ^ 2 = mulByTwoEndo h2 f :=
  let ⟨_, hP⟩ := exists_nsmul_two_eq h2 (Point.some x y h)
  exists_gS_two_of_card h2 (card_torsion_two h2) h hS hP

end Recovery

/-! ### Non-vacuity over `ℚ`

⚠️ **The certificate has to be over a field that is not algebraically closed**, or it certifies the
merged `exists_gS_two_of_isAlgClosed` instead of anything here (`#916`).  Both hypotheses are
proved, so `exampleRungFive` below has **no hypothesis at all**: it is rung 5 of the Weil pairing at
`n = 2`, on a named curve, over `ℚ`.

⚠️ **The curve is forced and the arithmetic is the content.**  It must have `E[2] ⊆ E(ℚ)` *and* a
rational halving of a `2`-torsion point — i.e. rational `4`-torsion above rational full `2`-torsion.
`y² = x³ + 5x² + 4x = x(x+1)(x+4)` has both:

* `E[2] = {O, (0,0), (−1,0), (−4,0)}` — the cubic splits over `ℚ` with distinct roots, so `hcard`
  holds and `Δ = 2304 ≠ 0`;
* `T = (0,0)` is halved by `P = (2, 6)`: the tangent there has slope
  `(3·4 + 2·5·2 + 4)/(2·6) = 36/12 = 3`, so `x([2]P) = 9 − 5 − 4 = 0` and `y([2]P) = 3(2−0) − 6 =
0`.

⚠️ **`y² = x³ − x` — this subtree's default curve — does not work here**, and the reason is the one
that has now defeated four separate pieces of work on this board.  It *does* have full rational
`2`-torsion, but `E(ℚ) = (ℤ/2)²`, so no rational point halves anything; the same fact appeared as
*"no two distinct multiples"* (`#1325`), *"no point of order `3`"* (`#1328`), *"no point of order
`4`"* (PR #504, recorded in `WeilPairingAlternatingAssemblyN`'s `ℚ` block), and *"no rational
halving"* here.  Change curve rather than weakening the certificate.

⚠️ No `open Classical in` anywhere in this block, and it is not an oversight: `ℚ` carries
`instDecidableEqRat`, which wins on instance priority whatever is open, so writing it would be a
no-op.  Every statement above takes `[DecidableEq F]` as a binder, so the whole block elaborates at
that one instance and costs no `convert`. -/

section Nonvacuity

/-- The curve `y² = x³ + 5x² + 4x = x(x+1)(x+4)` over `ℚ`, of discriminant `2304`. -/
private noncomputable def exampleCurve : Affine ℚ := ⟨0, 5, 0, 4, 0⟩

private instance : exampleCurve.IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero]
  norm_num [exampleCurve, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]

private lemma exampleTwo : (2 : ℚ) ≠ 0 := by norm_num

/-- `T = (0, 0)`, the `2`-torsion point cut out by `x = 0`. -/
private lemma exampleNsT : exampleCurve.Nonsingular 0 0 :=
  exampleCurve.equation_iff_nonsingular.mp (by
    norm_num [exampleCurve, WeierstrassCurve.Affine.equation_iff])

/-- `(−1, 0)`, the `2`-torsion point cut out by `x + 1 = 0`. -/
private lemma exampleNsR₁ : exampleCurve.Nonsingular (-1) 0 :=
  exampleCurve.equation_iff_nonsingular.mp (by
    norm_num [exampleCurve, WeierstrassCurve.Affine.equation_iff])

/-- `(−4, 0)`, the `2`-torsion point cut out by `x + 4 = 0`. -/
private lemma exampleNsR₂ : exampleCurve.Nonsingular (-4) 0 :=
  exampleCurve.equation_iff_nonsingular.mp (by
    norm_num [exampleCurve, WeierstrassCurve.Affine.equation_iff])

/-- `P = (2, 6)`, the halving point: `36 = 8 + 20 + 8`. -/
private lemma exampleNsP : exampleCurve.Nonsingular 2 6 :=
  exampleCurve.equation_iff_nonsingular.mp (by
    norm_num [exampleCurve, WeierstrassCurve.Affine.equation_iff])

private lemma exampleTorT : Point.some (0 : ℚ) 0 exampleNsT ∈ exampleCurve.torsion 2 :=
  (mem_torsion_two_some_iff exampleNsT).mpr (by norm_num [exampleCurve])

private lemma exampleTorR₁ : Point.some (-1 : ℚ) 0 exampleNsR₁ ∈ exampleCurve.torsion 2 :=
  (mem_torsion_two_some_iff exampleNsR₁).mpr (by norm_num [exampleCurve])

private lemma exampleTorR₂ : Point.some (-4 : ℚ) 0 exampleNsR₂ ∈ exampleCurve.torsion 2 :=
  (mem_torsion_two_some_iff exampleNsR₂).mpr (by norm_num [exampleCurve])

/-- The four rational `2`-torsion points, as a map out of `Fin 4`.  Named rather than inlined so
that its injectivity — which is what `hcard` rests on — is a statement of its own. -/
private noncomputable def exampleTorsionFour : Fin 4 → exampleCurve.torsion 2 :=
  ![⟨0, zero_mem _⟩, ⟨Point.some (0 : ℚ) 0 exampleNsT, exampleTorT⟩,
    ⟨Point.some (-1 : ℚ) 0 exampleNsR₁, exampleTorR₁⟩,
    ⟨Point.some (-4 : ℚ) 0 exampleNsR₂, exampleTorR₂⟩]

private lemma exampleTorsionFour_injective : Function.Injective exampleTorsionFour := by
  intro i j hij
  fin_cases i <;> fin_cases j <;>
    simp_all [exampleTorsionFour, Subtype.ext_iff]

/-- **`#E[2] = 4` over `ℚ` for this curve**, which is `hcard`.  `card_torsion_two_le`
(`EllipticCurves.Torsion.TwoTorsion`) is already unconditional and supplies `≤`; `≥` is the four
points above.  ⚠️ Note that the *upper* bound is where an algebraic closure would have been useless
anyway — what the closure buys in `card_torsion_two` is exactly this lower bound, and here it is
bought by naming the roots instead. -/
private lemma exampleCard : Nat.card (exampleCurve.torsion 2) = 4 := by
  haveI := exampleCurve.finite_torsion_two exampleTwo
  refine le_antisymm (card_torsion_two_le exampleTwo) ?_
  simpa using Nat.card_le_card_of_injective exampleTorsionFour exampleTorsionFour_injective

/-- **`P + P = T`**: the tangent at `(2, 6)` has slope `3`, so `x([2]P) = 9 − 5 − 4 = 0`. -/
private lemma exampleDoubleP :
    Point.some (2 : ℚ) 6 exampleNsP + Point.some (2 : ℚ) 6 exampleNsP
      = Point.some (0 : ℚ) 0 exampleNsT := by
  have hy : (6 : ℚ) ≠ exampleCurve.negY 2 6 := by
    norm_num [exampleCurve, WeierstrassCurve.Affine.negY]
  rw [Point.add_self_of_Y_ne hy, Point.some.injEq]
  refine ⟨?_, ?_⟩ <;>
    norm_num [exampleCurve, WeierstrassCurve.Affine.addX, WeierstrassCurve.Affine.addY,
      WeierstrassCurve.Affine.negAddY, WeierstrassCurve.Affine.negY,
      WeierstrassCurve.Affine.slope]

/-- **`[2]P = T`** in `nsmul` form, which is the shape the headline takes. -/
private lemma exampleTwoP :
    ((2 : ℕ) • Point.some (2 : ℚ) 6 exampleNsP : exampleCurve.Point)
      = Point.some (0 : ℚ) 0 exampleNsT := by
  rw [two_nsmul]; exact exampleDoubleP

/-- **Rung 5 of the Weil pairing at `n = 2` over `ℚ`, with no hypothesis whatsoever.**

⚠️ Compare the merged `exists_gS_two`, which carries `hprin` (`#418`), and
`exists_gS_two_of_isAlgClosed`, which discharges it only over `F̄`.  This statement is over `ℚ`, and
its hypothesis list is empty: `hcard` is `exampleCard` and the halving is `exampleTwoP`, both
proved.  It is the first `hprin` certificate on this board over a field that is not algebraically
closed.

⚠️ It is **not** evidence for `#962`, which asks for the same conclusion on a curve whose
`2`-torsion is *not* rational.  What it certifies is that the hypotheses of `exists_gS_two_of_card`
are simultaneously satisfiable away from `F̄`. -/
private theorem exampleRungFive :
    ∃ f : exampleCurve.FunctionField, f ≠ 0 ∧
      divisor exampleCurve f
          = Finsupp.single (pointClosedPoint exampleNsT.left) (2 : ℤ) ∧
        ∃ gS : exampleCurve.FunctionField, gS ≠ 0 ∧
          ∃ u : exampleCurve.CoordinateRingˣ,
            (u : exampleCurve.CoordinateRing) • gS ^ 2 = mulByTwoEndo exampleTwo f :=
  exists_gS_two_of_card exampleTwo exampleCard exampleNsT exampleTorT
    (P := Point.some (2 : ℚ) 6 exampleNsP) exampleTwoP

end Nonvacuity

end WeierstrassCurve.Affine
