/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.PlaceAtInfinity
import EllipticCurves.Torsion.CoordinateRingDedekind
import Mathlib.FieldTheory.RatFunc.AsPolynomial
import Mathlib.RingTheory.Algebraic.Integral
import Mathlib.RingTheory.Localization.Module

/-!
# `F(W)` is a quadratic extension of the rational function field `F(x)`

Let `W` be a Weierstrass curve over a field `F`.  Mathlib's `CoordinateRing.basis W` exhibits the
affine coordinate ring `F[W]` as a *free `F[X]`-module of rank two*, with basis `{1, Y}`.  This
file localises that statement at the nonzero polynomials and records its field-theoretic form:

```
Module.finrank (RatFunc F) W.FunctionField = 2
```

i.e. `[F(W) : F(x)] = 2`, where `x = genX W` is the generic `x`-coordinate.

This is a statement with **no `[2]` and no divisor theory in it**, but it is the bottom floor of the
tower that computes the degree of multiplication by two,

```
F(W) ⊇ F(x) ⊇ F(x ∘ [2]),        x ∘ [2] = Φ₂(x) / Ψ₂Sq(x),
```

whose middle degree is Mathlib's `RatFunc.finrank_eq_max_natDegree` and whose assembly is project
issue `#682`.  Before this file the tree had **no lower bound on `deg [2]` at all**: the finiteness
results `MulByTwoFinite` / `MulByTwoExtensionFinite` give only "finite, of degree `≤ 4`".

## The missing instance, and how it is built

The `F[X]`-algebra structure on `F(W)` exists (through `F[X] → F[W] → F(W)`), but the repository had
**no `Algebra (RatFunc F) W.FunctionField`**.  It is supplied here as `instAlgebraRatFunc`, from
Mathlib's `RatFunc.liftAlgebra`: since `algebraMap F[X] F(W)` is injective into a field, it factors
uniquely through the fraction field `F(X) = RatFunc F` of `F[X]`.  Mathlib keeps
`RatFunc.liftAlgebra` *scoped* because it produces a diamond at `L = RatFunc F`; specialised to
`W.FunctionField` — which is `FractionRing W.CoordinateRing`, never `RatFunc F` — there is no such
clash, so it is a global instance here.

Consequently `IsScalarTower F[X] (RatFunc F) W.FunctionField` (Mathlib's
`RatFunc.isScalarTower_liftAlgebra`) fires, and the new algebra map is **definitionally compatible**
with the `F[X] → F(W)` map that `PlaceAtInfinity.lean` and `ValuationAtInfinity.lean` already use.
That compatibility is what the last four results of this file record; without it the `finrank` is
unusable downstream, since nothing would connect `RatFunc.X` to `genX W`.

## Main definitions

* `WeierstrassCurve.Affine.CoordinateRing.instAlgebraRatFunc` — the algebra structure making `F(W)`
  an extension field of `RatFunc F`;
* `WeierstrassCurve.Affine.CoordinateRing.basisFunctionField` — the localised `{1, Y}` basis, a
  `Basis (Fin 2) (RatFunc F) W.FunctionField`.

## Main results

* `finrank_ratFunc_functionField : Module.finrank (RatFunc F) W.FunctionField = 2` — **the
  headline**;
* `basisFunctionField_zero`, `basisFunctionField_one` — the basis is `{1, genY W}`, so the `finrank`
  is not an abstract cardinality but the classical "`1` and `y` span `F(W)` over `F(x)`";
* `aeval_genX_eq_algebraMap : (Polynomial.aeval (genX W)) p = algebraMap F[X] W.FunctionField p` —
  the `F[X]`-algebra map is evaluation at the generic `x`-coordinate;
* `algebraMap_ratFunc_X : algebraMap (RatFunc F) W.FunctionField RatFunc.X = genX W` — **`RatFunc F`
  really is `F(x)`**, sitting inside `F(W)` as the subfield generated by the `x`-coordinate;
* `algebraMap_ratFunc_C`, `algebraMap_ratFunc_algebraMap` — the constants and the polynomials go
  where they should;
* `ordInfty_algebraMap_ratFunc_X` — the compatibility certificate: the image of `RatFunc.X` has a
  double pole at infinity, i.e. this `F(x)` is the one `PlaceAtInfinity.lean` already computes with;
* `algebraMap_ratFunc_eq_div` — a rational function goes to `Φ(x) / Ψ(x)` for its *reduced*
  numerator and denominator.  This is the form `#682` consumes: it is what turns
  `RatFunc.finrank_eq_max_natDegree`, which speaks about `RatFunc.num` and `RatFunc.denom`, into a
  statement about an element of `F(W)`.

## Scope

`[Field F]` only.  **No `[W.IsElliptic]` and no `IsDedekindDomain W.CoordinateRing`**: the rank-two
freeness of `F[W]` over `F[X]` is a consequence of `W.polynomial` being monic of degree two in `Y`,
which holds for every Weierstrass curve, singular or not.  Nothing here mentions `mulByTwoEndo`,
ramification, places or divisors.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2, III.4.
* H. Stichtenoth, *Algebraic Function Fields and Codes*, I.1.
-/

open Module Polynomial

open scoped nonZeroDivisors

namespace WeierstrassCurve.Affine.CoordinateRing

variable {F : Type*} [Field F] {W : Affine F}

/-- **`F(W)` is an extension field of the rational function field `F(x) = RatFunc F`.**

The map `F[X] → F(W)` is injective into a field, so by the universal property of the fraction field
it factors uniquely through `RatFunc F`; `RatFunc.liftAlgebra` packages that factorisation.

Mathlib declares `RatFunc.liftAlgebra` as a *scoped* instance because it creates a diamond when the
target is `RatFunc F` itself.  Here the target is `W.FunctionField = FractionRing W.CoordinateRing`,
which is never `RatFunc F`, so no diamond arises and the instance is global.  The compatibility with
the pre-existing `F[X] → F(W)` map is `IsScalarTower F[X] (RatFunc F) W.FunctionField`, which
Mathlib's `RatFunc.isScalarTower_liftAlgebra` then supplies automatically. -/
noncomputable instance instAlgebraRatFunc : Algebra (RatFunc F) W.FunctionField :=
  RatFunc.liftAlgebra F _

variable (W) in
/-- **The `{1, y}` basis of `F(W)` over `F(x)`**, obtained by localising Mathlib's rank-two
`F[X]`-basis `CoordinateRing.basis W` of `F[W]` at the nonzero polynomials.

The two `IsLocalization` inputs this needs are both already available: `RatFunc F` is by definition
the localisation of `F[X]` at `F[X]⁰`, and `F(W)` is the localisation of `F[W]` at the image of
`F[X]⁰` because `F[W]` is *algebraic* over `F[X]` (Mathlib's
`Algebra.IsAlgebraic.instIsLocalizationAlgebraMapSubmonoidNonZeroDivisors`), which in turn follows
from module-finiteness. -/
noncomputable def basisFunctionField : Basis (Fin 2) (RatFunc F) W.FunctionField :=
  (CoordinateRing.basis W).localizationLocalization (RatFunc F) F[X]⁰ W.FunctionField

@[simp]
lemma basisFunctionField_zero : basisFunctionField W 0 = 1 := by
  simp [basisFunctionField]

@[simp]
lemma basisFunctionField_one : basisFunctionField W 1 = genY W := by
  simp [basisFunctionField, genY, genPsi]

/-- **`F(W)` is a quadratic extension of `F(x)`**: `[F(W) : F(x)] = 2`.

Geometrically this is the statement that the `x`-coordinate map `W → ℙ¹` has degree two — every
point of the curve is determined by its `x`-coordinate together with one of the two roots of the
Weierstrass equation in `Y`.  Concretely it is `basisFunctionField`, whose index type is `Fin 2`. -/
theorem finrank_ratFunc_functionField : Module.finrank (RatFunc F) W.FunctionField = 2 := by
  rw [Module.finrank_eq_card_basis (basisFunctionField W)]
  simp

/-- `F(W)` is a finite-dimensional `F(x)`-vector space. -/
instance instFiniteDimensionalRatFunc : FiniteDimensional (RatFunc F) W.FunctionField :=
  Module.Finite.of_basis (basisFunctionField W)

/-! ### Compatibility with the maps out of `F[X]`

The `finrank` above is useless downstream unless the copy of `RatFunc F` inside `F(W)` is known to
be the subfield generated by the generic `x`-coordinate.  The lemmas below pin that down. -/

/-- The structure map `F[X] → F(W)` factors through `RatFunc F` — an unfolding of the scalar tower
`F[X] → F(x) → F(W)`, recorded because it is the bridge every downstream rewrite crosses. -/
@[simp]
lemma algebraMap_ratFunc_algebraMap (p : F[X]) :
    algebraMap (RatFunc F) W.FunctionField (algebraMap F[X] (RatFunc F) p)
      = algebraMap F[X] W.FunctionField p :=
  (IsScalarTower.algebraMap_apply F[X] (RatFunc F) W.FunctionField p).symm

/-- **The `F[X]`-algebra map into `F(W)` is evaluation at the generic `x`-coordinate.**  Both sides
are `F`-algebra maps `F[X] → F(W)` sending `X` to `genX W`, so they agree. -/
lemma aeval_genX_eq_algebraMap (p : F[X]) :
    (Polynomial.aeval (genX W)) p = algebraMap F[X] W.FunctionField p := by
  have hX : algebraMap F[X] W.FunctionField Polynomial.X = genX W := by
    rw [genX, genPsi, IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField]
    norm_num [CoordinateRing.mk, AdjoinRoot.algebraMap_eq]
  have key : (Polynomial.aeval (genX W) : F[X] →ₐ[F] W.FunctionField)
      = IsScalarTower.toAlgHom F F[X] W.FunctionField :=
    Polynomial.algHom_ext (by simpa using hX.symm)
  exact congrFun (congrArg DFunLike.coe key) p

/-- **`RatFunc F` really is `F(x)`.**  The indeterminate of the rational function field is sent to
the generic `x`-coordinate of `F(W)`, so `algebraMap (RatFunc F) W.FunctionField` identifies
`RatFunc F` with the subfield `F(x) ⊆ F(W)`. -/
@[simp]
lemma algebraMap_ratFunc_X :
    algebraMap (RatFunc F) W.FunctionField (RatFunc.X : RatFunc F) = genX W := by
  rw [← RatFunc.algebraMap_X, algebraMap_ratFunc_algebraMap, ← aeval_genX_eq_algebraMap]
  simp

/-- Constants go to constants: the tower `F → F(x) → F(W)` is compatible with `F → F(W)`. -/
@[simp]
lemma algebraMap_ratFunc_C (c : F) :
    algebraMap (RatFunc F) W.FunctionField (RatFunc.C c) = algebraMap F W.FunctionField c := by
  rw [← RatFunc.algebraMap_C, algebraMap_ratFunc_algebraMap, Polynomial.C_eq_algebraMap,
    ← IsScalarTower.algebraMap_apply]

/-- **Compatibility certificate against the merged place-at-infinity calculus.**  The indeterminate
of `RatFunc F`, pushed into `F(W)` by the algebra structure built above, has a double pole at
infinity — exactly `ordInfty_genX` (`PlaceAtInfinity.lean`).  So the copy of `F(x)` produced here is
the one the existing degree theory already works with, not a parallel one. -/
theorem ordInfty_algebraMap_ratFunc_X :
    WeierstrassCurve.Affine.ordInfty W
      (algebraMap (RatFunc F) W.FunctionField (RatFunc.X : RatFunc F)) = -2 := by
  rw [algebraMap_ratFunc_X]
  exact WeierstrassCurve.Affine.ordInfty_genX

/-- **A rational function evaluates at the generic point as `num(x) / denom(x)`**, for the *reduced*
numerator and denominator supplied by `RatFunc.num` / `RatFunc.denom`.

This is the shape `#682` needs.  Mathlib's degree formula `RatFunc.finrank_eq_max_natDegree` is
stated in terms of `RatFunc.num` and `RatFunc.denom`, so a reduced-fraction hypothesis
(for `[2]`: `IsCoprime (W.Φ 2) W.Ψ₂Sq`) turns a presentation `Φ(x)/Ψ(x)` of an element of `F(W)`
into a statement about *this* pair, and hence into a degree. -/
lemma algebraMap_ratFunc_eq_div (f : RatFunc F) :
    algebraMap (RatFunc F) W.FunctionField f
      = (Polynomial.aeval (genX W)) f.num / (Polynomial.aeval (genX W)) f.denom := by
  conv_lhs => rw [← RatFunc.num_div_denom f]
  rw [map_div₀, algebraMap_ratFunc_algebraMap, algebraMap_ratFunc_algebraMap,
    aeval_genX_eq_algebraMap, aeval_genX_eq_algebraMap]

/-! ### Non-vacuity

`y² = x³ - x` over `ℚ` (discriminant `64`), a genuine elliptic curve, on which the statements above
have content.  Nothing in this file needs `IsElliptic`, but a committed instantiation is what keeps
the declarations from silently becoming vacuous under a later refactor. -/

private def exampleCurve : Affine ℚ := ⟨0, 0, 0, -1, 0⟩

private instance : exampleCurve.IsElliptic := by
  rw [WeierstrassCurve.isElliptic_iff, isUnit_iff_ne_zero]
  norm_num [exampleCurve, WeierstrassCurve.Δ, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, WeierstrassCurve.b₈]

example : Module.finrank (RatFunc ℚ) exampleCurve.FunctionField = 2 :=
  finrank_ratFunc_functionField

example : algebraMap (RatFunc ℚ) exampleCurve.FunctionField (RatFunc.X : RatFunc ℚ)
    = genX exampleCurve :=
  algebraMap_ratFunc_X

example : WeierstrassCurve.Affine.ordInfty exampleCurve
    (algebraMap (RatFunc ℚ) exampleCurve.FunctionField (RatFunc.X : RatFunc ℚ)) = -2 :=
  ordInfty_algebraMap_ratFunc_X

end WeierstrassCurve.Affine.CoordinateRing
