/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.FunctionField.PlaceAtInfinity
import EllipticCurves.NewtonPolygon
import Mathlib.RingTheory.Valuation.ValuationSubring
import Mathlib.RingTheory.DedekindDomain.AdicValuation

/-!
# A valuation of `F(W)` with a pole at `x` is the place at infinity

`EllipticCurves.FunctionField.PlaceAtInfinity` builds `ordInfty`, the order of vanishing at the
point at infinity, and shows it is an additive valuation on `F(W)`.  This file proves the converse
half of the classification of places, in the branch where the generic `x`-coordinate has a pole:

```
O a valuation subring of F(W), F ⊆ O, genX W ∉ O  ⟹  ∀ f, f ∈ O ↔ 0 ≤ ordInfty W f
```

(`mem_iff_ordInfty_nonneg`), equivalently `O = ordInftyValuationSubring W`
(`eq_ordInftyValuationSubring`).  Together with the affine branch — `genX W ∈ O`, which reduces to
the general Dedekind statement about `F[W] ⊆ O` — this is rung 4 of `#639`, the statement that makes
an `F`-automorphism of `F(W)` permute the points of the projective curve.

## The identity everything runs on

The classical form of the argument says `V(x) = −2m` and `V(y) = −3m` for some `m > 0`.  That
statement **halves in the value group**, so taking it as the shape of the proof forces one to
assume in advance that the place is discrete.  Doubling it removes the division:

```
valuation_pow_two_eq_deg :  O.valuation a ^ 2 = O.valuation (genX W) ^ deg W a
```

for every nonzero `a ∈ F[W]` — additively, `2·V(a) = deg(a)·V(x)`.  Every step of the derivation is
then a comparison of integer powers in a linearly ordered commutative group, valid for an
**arbitrary** value group, and discreteness of `O` comes out as a *consequence*
(`exists_zpow_eq`) rather than going in as a hypothesis.

## Structure of the proof

0. `valuation_algebraMap_base` — the valuation is trivial on `F`, since `F` is a field inside `O`.
1. `one_lt_valuation_genX` — `genX W ∉ O` says exactly `1 < O.valuation (genX W)`; powers of that
   are then strictly monotone, which is where every "these two terms cannot cancel" step lands.
2. `valuation_genY_sq` — `V(y)² = V(x)³`, the Newton-polygon dichotomy.  This is *not* proved here:
   it is `WeierstrassCurve.valuation_pow_two_eq_pow_three_of_valuation_le_one`
   (`EllipticCurves.NewtonPolygon`), shared with `EllipticCurves.Reduction.PointValuation`, which
   needs the same fact for the adic valuation of a discrete valuation ring.
3. `valuation_polynomial` — `V(p(x)) = V(x) ^ deg p`, because the monomials of `p` have pairwise
   distinct valuations.
4. `valuation_pow_two_eq_deg` — the identity above, from 2 and 3 on `a = p • 1 + q • Y`: after
   doubling, the two parts have exponents `2 deg p` and `2 deg q + 3`, of **opposite parity**, so
   they can never cancel and the total is the larger — which is `deg a`, by
   `deg_smul_basis`.
5. `mem_iff_ordInfty_nonneg` — for `f = a / b`, step 4 twice gives
   `V(f)² = V(x) ^ (−ordInfty f)`, and `1 < V(x)` converts `V(f) ≤ 1` into `0 ≤ ordInfty f`.

## Main results

* `WeierstrassCurve.Affine.ordInftyValuationSubring` — the place at infinity, as a valuation
  subring.  This is also the **non-vacuity certificate**: it satisfies the hypotheses of the main
  theorem, so those hypotheses are not empty;
* **`WeierstrassCurve.Affine.valuation_pow_two_eq_deg`** — `2·V(a) = deg(a)·V(x)`;
* **`WeierstrassCurve.Affine.mem_iff_ordInfty_nonneg`** and `eq_ordInftyValuationSubring`;
* `WeierstrassCurve.Affine.exists_zpow_eq` — the value group is generated by a square root of
  `V(x)`, i.e. `O` is discrete.  Stated in the doubled form; `IsDiscreteValuationRing O` is *not*
  claimed here;
* `WeierstrassCurve.Affine.genX_mem_valuationSubringAtPrime` — the affine places do contain `genX`,
  so the hypothesis `genX W ∉ O` is restrictive and the eventual case split is a genuine dichotomy.

## Scope

No `[IsDedekindDomain W.CoordinateRing]` and no `[W.IsElliptic]` are needed for the main line; the
Dedekind hypothesis appears only in the last section, for the affine-places certificate.  The
**affine branch** `genX W ∈ O` is not proved here, nor is any assembly into a classification of all
places; those are separate issues.  Ward-independent, normality-independent.

## References

* Stichtenoth, *Algebraic Function Fields and Codes*, I.1.5, I.2.2.
* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.1–II.3.
-/

open Polynomial IsDedekindDomain
open scoped Polynomial.Bivariate nonZeroDivisors

namespace WeierstrassCurve.Affine

open CoordinateRing

variable {F : Type*} [Field F] {W : Affine F}

variable (W) in
/-- The place at infinity, as a valuation subring. -/
noncomputable def ordInftyValuationSubring : ValuationSubring W.FunctionField where
  carrier := {f | 0 ≤ ordInfty W f}
  mul_mem' := by
    intro f g hf hg
    simp only [Set.mem_setOf_eq] at *
    rcases eq_or_ne f 0 with rfl | hf0
    · simp
    rcases eq_or_ne g 0 with rfl | hg0
    · simp
    rw [ordInfty_mul hf0 hg0]; omega
  one_mem' := by simp
  add_mem' := by
    intro f g hf hg
    simp only [Set.mem_setOf_eq] at *
    rcases eq_or_ne f 0 with rfl | hf0
    · simpa using hg
    rcases eq_or_ne g 0 with rfl | hg0
    · simpa using hf
    rcases eq_or_ne (f + g) 0 with h | h
    · simp [h]
    have := le_ordInfty_add hf0 hg0 h
    omega
  zero_mem' := by simp
  neg_mem' := by
    intro f hf
    simp only [Set.mem_setOf_eq] at *
    rcases eq_or_ne f 0 with rfl | hf0
    · simp
    have : (-f) = algebraMap F W.FunctionField (-1) * f := by simp
    rw [this, ordInfty_mul (by simp) hf0, ordInfty_algebraMap_base (by norm_num : (-1 : F) ≠ 0)]
    omega
  mem_or_inv_mem' := by
    intro f
    simp only [Set.mem_setOf_eq]
    rcases eq_or_ne f 0 with rfl | hf0
    · simp
    rw [ordInfty_inv]
    omega

/-- Membership in the place at infinity is regularity at infinity. -/
@[simp]
lemma mem_ordInftyValuationSubring {f : W.FunctionField} :
    f ∈ ordInftyValuationSubring W ↔ 0 ≤ ordInfty W f := Iff.rfl

/-- The place at infinity contains the constants: it is a place *of `F(W)` over `F`*. -/
lemma algebraMap_mem_ordInftyValuationSubring (c : F) :
    algebraMap F W.FunctionField c ∈ ordInftyValuationSubring W := by
  rcases eq_or_ne c 0 with rfl | hc
  · simp
  simp [ordInfty_algebraMap_base hc]

/-- The place at infinity does **not** contain the generic `x`-coordinate, which has a double
pole there (`ordInfty_genX = -2`).  With the previous lemma this says the hypotheses of
`mem_iff_ordInfty_nonneg` are satisfiable, so that theorem is not vacuous. -/
lemma genX_notMem_ordInftyValuationSubring :
    CoordinateRing.genX W ∉ ordInftyValuationSubring W := by
  simp [ordInfty_genX]


/-! ### Steps 0 and 1 -/

section

variable {O : ValuationSubring W.FunctionField}
  (hF : ∀ c : F, algebraMap F W.FunctionField c ∈ O)

include hF in
/-- Step 0: the valuation is trivial on the base field. -/
lemma valuation_algebraMap_base {c : F} (hc : c ≠ 0) :
    O.valuation (algebraMap F W.FunctionField c) = 1 := by
  have hle : O.valuation (algebraMap F W.FunctionField c) ≤ 1 :=
    (O.valuation_le_one_iff _).2 (hF c)
  have h1 : O.valuation (algebraMap F W.FunctionField c⁻¹) ≤ 1 :=
    (O.valuation_le_one_iff _).2 (hF c⁻¹)
  have hmul : O.valuation (algebraMap F W.FunctionField c)
      * O.valuation (algebraMap F W.FunctionField c⁻¹) = 1 := by
    rw [← map_mul, ← map_mul, mul_inv_cancel₀ hc, map_one, map_one]
  refine le_antisymm hle ?_
  by_contra hlt
  rw [not_le] at hlt
  have : O.valuation (algebraMap F W.FunctionField c)
      * O.valuation (algebraMap F W.FunctionField c⁻¹) < 1 :=
    lt_of_le_of_lt (mul_le_of_le_one_right' h1) hlt
  exact absurd hmul (ne_of_lt this)

/-- Step 1: `genX` has a pole, so its valuation exceeds `1`. -/
lemma one_lt_valuation_genX (hx : CoordinateRing.genX W ∉ O) :
    1 < O.valuation (CoordinateRing.genX W) :=
  not_le.mp fun h => hx ((O.valuation_le_one_iff _).1 h)

end


/-! ### A helper in a linearly ordered commutative group with zero -/

section Gamma

variable {Γ : Type*} [LinearOrderedCommGroupWithZero Γ]

/-- Squaring commutes with `max`, since it is monotone. -/
private lemma sq_max {u w : Γ} : max u w ^ 2 = max (u ^ 2) (w ^ 2) := by
  rcases le_total u w with h | h
  · rw [max_eq_right h, max_eq_right (pow_le_pow_left₀ zero_le h 2)]
  · rw [max_eq_left h, max_eq_left (pow_le_pow_left₀ zero_le h 2)]

end Gamma

/-! ### Step 2 -/

section Newton

variable {O : ValuationSubring W.FunctionField}
  (hF : ∀ c : F, algebraMap F W.FunctionField c ∈ O)
  (hx : CoordinateRing.genX W ∉ O)

include hF in
/-- Every constant is `O`-integral, including `0`.  The form the coefficient bounds of the
Newton-polygon lemma want. -/
lemma valuation_algebraMap_base_le (c : F) :
    O.valuation (algebraMap F W.FunctionField c) ≤ 1 :=
  (O.valuation_le_one_iff _).2 (hF c)

include hF hx in
/-- **Step 2, from the shared Newton-polygon lemma.**  `2·V(y) = 3·V(x)`. -/
lemma valuation_genY_sq :
    O.valuation (CoordinateRing.genY W) ^ 2
      = O.valuation (CoordinateRing.genX W) ^ 3 :=
  (WeierstrassCurve.valuation_pow_two_eq_pow_three_of_valuation_le_one O.valuation
    (W.map (algebraMap F W.FunctionField))
    (by simpa using valuation_algebraMap_base_le hF W.a₁)
    (by simpa using valuation_algebraMap_base_le hF W.a₂)
    (by simpa using valuation_algebraMap_base_le hF W.a₃)
    (by simpa using valuation_algebraMap_base_le hF W.a₄)
    (by simpa using valuation_algebraMap_base_le hF W.a₆)
    equation_gen (one_lt_valuation_genX hx)).2

/-! ### Step 3 -/

omit hF in
/-- A constant polynomial maps into `F(W)` through the base field. -/
lemma valuation_algebraMap_polynomial_C (c : F) :
    O.valuation (algebraMap F[X] W.FunctionField (Polynomial.C c))
      = O.valuation (algebraMap F W.FunctionField c) := by
  rw [Polynomial.C_eq_algebraMap, ← IsScalarTower.algebraMap_apply]

omit hF hx in
/-- `X : F[X]` maps to the generic `x`-coordinate of `F(W)`. -/
lemma algebraMap_polynomial_X :
    algebraMap F[X] W.FunctionField Polynomial.X = CoordinateRing.genX W := by
  rw [CoordinateRing.genX, CoordinateRing.genPsi,
    IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField]
  norm_num [CoordinateRing.mk, AdjoinRoot.algebraMap_eq]

include hF hx in
/-- **Step 3: a polynomial in `x` has valuation `V(x) ^ deg p`.**  The monomials `cᵢ xⁱ` have
pairwise distinct valuations `V(x) ^ i`, so the sum has the valuation of its unique largest term,
which is the leading one because `1 < V(x)`. -/
lemma valuation_polynomial {p : F[X]} (hp : p ≠ 0) :
    O.valuation (algebraMap F[X] W.FunctionField p)
      = O.valuation (CoordinateRing.genX W) ^ p.natDegree := by
  classical
  set vX := O.valuation (CoordinateRing.genX W) with hXdef
  have hX1 : 1 < vX := one_lt_valuation_genX hx
  have hpow : ∀ m n : ℕ, m < n → vX ^ m < vX ^ n := fun m n h => pow_lt_pow_right₀ hX1 h
  set n := p.natDegree with hn
  have hsum : p = ∑ i ∈ Finset.range (n + 1), Polynomial.C (p.coeff i) * Polynomial.X ^ i :=
    Polynomial.as_sum_range_C_mul_X_pow p
  have hterm : ∀ i : ℕ, O.valuation (algebraMap F[X] W.FunctionField
      (Polynomial.C (p.coeff i) * Polynomial.X ^ i))
      = O.valuation (algebraMap F W.FunctionField (p.coeff i)) * vX ^ i := by
    intro i
    rw [map_mul, map_pow, Valuation.map_mul, Valuation.map_pow, algebraMap_polynomial_X,
      valuation_algebraMap_polynomial_C (O := O), ← hXdef]
  have htop : O.valuation (algebraMap F[X] W.FunctionField
      (Polynomial.C (p.coeff n) * Polynomial.X ^ n)) = vX ^ n := by
    have hc : p.coeff n ≠ 0 := Polynomial.leadingCoeff_ne_zero.2 hp
    rw [hterm n, valuation_algebraMap_base hF hc, one_mul]
  rw [hsum, map_sum]
  rw [Valuation.map_sum_eq_of_lt _ (Finset.self_mem_range_succ n) ?_, htop]
  intro i hi
  rw [Finset.mem_sdiff, Finset.mem_range, Finset.mem_singleton] at hi
  have hlt : i < n := lt_of_le_of_ne (Nat.lt_succ_iff.1 hi.1) hi.2
  rw [hterm i, htop]
  exact lt_of_le_of_lt (mul_le_of_le_one_left' (valuation_algebraMap_base_le hF _)) (hpow i n hlt)

/-! ### The degree of a general element in the basis `{1, Y}` -/

omit hF hx in
lemma deg_smul_basis {p q : F[X]} (hp : p ≠ 0) (hq : q ≠ 0) :
    deg W (p • (1 : W.CoordinateRing) + q • CoordinateRing.mk W Y)
      = max (2 * p.natDegree) (2 * q.natDegree + 3) := by
  have hd := CoordinateRing.degree_norm_smul_basis (W' := W) p q
  have hpd : p.degree = (p.natDegree : WithBot ℕ) := Polynomial.degree_eq_natDegree hp
  have hqd : q.degree = (q.natDegree : WithBot ℕ) := Polynomial.degree_eq_natDegree hq
  rw [hpd, hqd] at hd
  have hcast : max ((2 : ℕ) • (p.natDegree : WithBot ℕ)) ((2 : ℕ) • (q.natDegree : WithBot ℕ) + 3)
      = ((max (2 * p.natDegree) (2 * q.natDegree + 3) : ℕ) : WithBot ℕ) := by
    push_cast [nsmul_eq_mul]
    rcases le_total (2 * p.natDegree) (2 * q.natDegree + 3) with h | h
    · rw [max_eq_right h, max_eq_right (by exact_mod_cast h)]; push_cast; ring
    · rw [max_eq_left h, max_eq_left (by exact_mod_cast h)]; push_cast; ring
  rw [hcast] at hd
  rw [deg, Polynomial.natDegree, hd]
  rfl

/-! ### Step 4: the key identity -/

omit hF hx in
/-- The first basis vector of `F[W]` over `F[X]`, pushed into `F(W)`. -/
lemma algebraMap_smul_one (p : F[X]) :
    algebraMap W.CoordinateRing W.FunctionField (p • (1 : W.CoordinateRing))
      = algebraMap F[X] W.FunctionField p := by
  rw [Algebra.smul_def, mul_one,
    IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField]

omit hF hx in
/-- The second basis vector of `F[W]` over `F[X]`, pushed into `F(W)`. -/
lemma algebraMap_smul_Y (q : F[X]) :
    algebraMap W.CoordinateRing W.FunctionField (q • CoordinateRing.mk W Y)
      = algebraMap F[X] W.FunctionField q * CoordinateRing.genY W := by
  rw [Algebra.smul_def, map_mul,
    ← IsScalarTower.algebraMap_apply F[X] W.CoordinateRing W.FunctionField]
  rfl

include hF hx in
/-- **The key identity.**  `2·V(a) = deg(a)·V(x)`, stated after doubling so that it makes sense in
an arbitrary value group. -/
theorem valuation_pow_two_eq_deg {a : W.CoordinateRing} (ha : a ≠ 0) :
    O.valuation (algebraMap W.CoordinateRing W.FunctionField a) ^ 2
      = O.valuation (CoordinateRing.genX W) ^ deg W a := by
  classical
  set vX := O.valuation (CoordinateRing.genX W) with hXdef
  have hX1 : 1 < vX := one_lt_valuation_genX hx
  have hpow : ∀ m n : ℕ, m < n → vX ^ m < vX ^ n := fun m n h => pow_lt_pow_right₀ hX1 h
  have hpowinj : ∀ m n : ℕ, vX ^ m = vX ^ n → m = n := by
    intro m n h
    rcases lt_trichotomy m n with hmn | hmn | hmn
    · exact absurd h (ne_of_lt (hpow m n hmn))
    · exact hmn
    · exact absurd h.symm (ne_of_lt (hpow n m hmn))
  obtain ⟨p, q, rfl⟩ := CoordinateRing.exists_smul_basis_eq a
  have hP : ∀ r : F[X], r ≠ 0 →
      O.valuation (algebraMap F[X] W.FunctionField r) ^ 2 = vX ^ (2 * r.natDegree) := by
    intro r hr
    rw [valuation_polynomial hF hx hr, ← pow_mul, mul_comm]
  by_cases hq : q = 0
  · subst hq
    have hp : p ≠ 0 := by
      intro h; subst h; simp at ha
    rw [zero_smul, add_zero, algebraMap_smul_one, hP p hp]
    congr 1
    rw [CoordinateRing.smul, mul_one, deg_mk_C]
  · by_cases hp : p = 0
    · subst hp
      rw [zero_smul, zero_add, algebraMap_smul_Y, Valuation.map_mul, mul_pow, hP q hq,
        valuation_genY_sq hF hx, ← pow_add]
      congr 1
      rw [CoordinateRing.smul, deg_mul (CoordinateRing.mk_C_ne_zero hq) CoordinateRing.mk_Y_ne_zero,
        deg_mk_C, deg_mk_Y]
    · have hvp : O.valuation (algebraMap W.CoordinateRing W.FunctionField
          (p • (1 : W.CoordinateRing))) ^ 2 = vX ^ (2 * p.natDegree) := by
        rw [algebraMap_smul_one, hP p hp]
      have hvq : O.valuation (algebraMap W.CoordinateRing W.FunctionField
          (q • CoordinateRing.mk W Y)) ^ 2 = vX ^ (2 * q.natDegree + 3) := by
        rw [algebraMap_smul_Y, Valuation.map_mul, mul_pow, hP q hq, valuation_genY_sq hF hx,
          ← pow_add]
      have hne : O.valuation (algebraMap W.CoordinateRing W.FunctionField
          (p • (1 : W.CoordinateRing)))
          ≠ O.valuation (algebraMap W.CoordinateRing W.FunctionField
          (q • CoordinateRing.mk W Y)) := by
        intro h
        rw [h, hvq] at hvp
        exact absurd (hpowinj _ _ hvp) (by omega)
      rw [map_add, Valuation.map_add_of_distinct_val _ hne, sq_max, hvp, hvq,
        deg_smul_basis hp hq]
      rcases le_total (2 * p.natDegree) (2 * q.natDegree + 3) with h | h
      · rw [max_eq_right h, max_eq_right (le_of_lt (hpow _ _ (by omega)))]
      · rw [max_eq_left h, max_eq_left (le_of_lt (hpow _ _ (by omega)))]

/-! ### Step 5: the conclusion -/

include hF hx in
/-- **A valuation subring of `F(W)` containing `F` and not containing `x` is the place at
infinity.** -/
theorem mem_iff_ordInfty_nonneg (f : W.FunctionField) : f ∈ O ↔ 0 ≤ ordInfty W f := by
  classical
  rcases eq_or_ne f 0 with rfl | hf
  · simp
  set vX := O.valuation (CoordinateRing.genX W) with hXdef
  have hX1 : 1 < vX := one_lt_valuation_genX hx
  have hX0 : vX ≠ 0 := ne_of_gt (lt_trans zero_lt_one hX1)
  have hpow : ∀ m n : ℕ, m < n → vX ^ m < vX ^ n := fun m n h => pow_lt_pow_right₀ hX1 h
  set n := (IsLocalization.sec W.CoordinateRing⁰ f).1 with hn
  set s := ((IsLocalization.sec W.CoordinateRing⁰ f).2 : W.CoordinateRing) with hs
  have hspec : f * algebraMap W.CoordinateRing W.FunctionField s
      = algebraMap W.CoordinateRing W.FunctionField n := IsLocalization.sec_spec _ f
  have hs0 : s ≠ 0 := nonZeroDivisors.coe_ne_zero _
  have hn0 : n ≠ 0 := by
    intro h
    rw [h, map_zero, mul_eq_zero] at hspec
    rcases hspec with h' | h'
    · exact hf h'
    · exact hs0 ((IsFractionRing.injective W.CoordinateRing W.FunctionField) (by rw [h', map_zero]))
  have hkey : O.valuation f ^ 2 * vX ^ deg W s = vX ^ deg W n := by
    rw [← valuation_pow_two_eq_deg hF hx hs0, ← valuation_pow_two_eq_deg hF hx hn0, ← mul_pow,
      ← map_mul, hspec]
  have hordInfty : ordInfty W f = (deg W s : ℤ) - deg W n := ordInfty_of_ne_zero hf
  rw [← O.valuation_le_one_iff f, hordInfty]
  constructor
  · intro hle
    have h1 : vX ^ deg W n ≤ vX ^ deg W s := by
      rw [← hkey]
      exact mul_le_of_le_one_left' (pow_le_one₀ zero_le hle)
    have : deg W n ≤ deg W s := by
      by_contra hc
      exact absurd h1 (not_le.2 (hpow _ _ (by omega)))
    omega
  · intro hge
    have hdle : deg W n ≤ deg W s := by omega
    have h1 : O.valuation f ^ 2 * vX ^ deg W s ≤ vX ^ deg W s := by
      rw [hkey]
      rcases eq_or_lt_of_le hdle with h | h
      · rw [h]
      · exact le_of_lt (hpow _ _ h)
    by_contra hc
    rw [not_le] at hc
    have h2 : vX ^ deg W s < O.valuation f ^ 2 * vX ^ deg W s := by
      calc vX ^ deg W s = 1 * vX ^ deg W s := (one_mul _).symm
        _ < O.valuation f ^ 2 * vX ^ deg W s :=
            (mul_lt_mul_iff_left₀ (zero_lt_iff.mpr (pow_ne_zero _ hX0))).2
              (one_lt_pow₀ hc (by norm_num))
    exact absurd h1 (not_le.2 h2)

include hF hx in
/-- **`O` is the place at infinity**, as an equality of valuation subrings.  The sharp form of
`mem_iff_ordInfty_nonneg`. -/
theorem eq_ordInftyValuationSubring : O = ordInftyValuationSubring W :=
  SetLike.ext fun f => (mem_iff_ordInfty_nonneg hF hx f).trans mem_ordInftyValuationSubring.symm

include hF hx in
/-- **`O` is discrete**, in the doubled form that avoids halving in the value group: the square of
the valuation of any nonzero element is an integer power of `O.valuation (genX W)`.

`IsDiscreteValuationRing O` follows from this and is deliberately **not** claimed here — it would
need the value group to be identified with `ℤ`, which is a separate piece of work. -/
theorem exists_zpow_eq {f : W.FunctionField} (hf : f ≠ 0) :
    ∃ n : ℤ, O.valuation f ^ 2 = O.valuation (CoordinateRing.genX W) ^ n := by
  refine ⟨-ordInfty W f, ?_⟩
  set vX := O.valuation (CoordinateRing.genX W) with hXdef
  have hX0 : vX ≠ 0 := ne_of_gt (lt_trans zero_lt_one (one_lt_valuation_genX hx))
  set n := (IsLocalization.sec W.CoordinateRing⁰ f).1 with hn
  set s := ((IsLocalization.sec W.CoordinateRing⁰ f).2 : W.CoordinateRing) with hs
  have hspec : f * algebraMap W.CoordinateRing W.FunctionField s
      = algebraMap W.CoordinateRing W.FunctionField n := IsLocalization.sec_spec _ f
  have hs0 : s ≠ 0 := nonZeroDivisors.coe_ne_zero _
  have hn0 : n ≠ 0 := by
    intro h
    rw [h, map_zero, mul_eq_zero] at hspec
    rcases hspec with h' | h'
    · exact hf h'
    · exact hs0 ((IsFractionRing.injective W.CoordinateRing W.FunctionField) (by rw [h', map_zero]))
  have hkey : O.valuation f ^ 2 * vX ^ deg W s = vX ^ deg W n := by
    rw [← valuation_pow_two_eq_deg hF hx hs0, ← valuation_pow_two_eq_deg hF hx hn0, ← mul_pow,
      ← map_mul, hspec]
  rw [ordInfty_of_ne_zero hf, neg_sub, zpow_sub₀ hX0, zpow_natCast, zpow_natCast,
    eq_div_iff (pow_ne_zero _ hX0)]
  exact hkey

end Newton

/-! ### The other branch of the case split is inhabited

`mem_iff_ordInfty_nonneg` assumes `genX W ∉ O`.  That hypothesis is restrictive rather than
automatic: every *affine* place contains `genX W`, since `genX W` lies in the image of the
coordinate ring.  So the case split `genX W ∈ O` / `genX W ∉ O` that the classification of places
runs on is a genuine dichotomy, not a disjunction with a dead branch. -/

section Affine

variable [IsDedekindDomain W.CoordinateRing]

/-- The generic `x`-coordinate lies in every affine place. -/
lemma genX_mem_valuationSubringAtPrime (v : HeightOneSpectrum W.CoordinateRing) :
    CoordinateRing.genX W ∈ HeightOneSpectrum.valuationSubringAtPrime W.FunctionField v := by
  rw [CoordinateRing.genX, CoordinateRing.genPsi]
  exact Subalgebra.algebraMap_mem _ _

/-- The place at infinity is **not** an affine place: `genX W` separates them.  This is
`ord_genX_ne_ordInfty_genX` in the form the classification of places consumes. -/
theorem ordInftyValuationSubring_ne_valuationSubringAtPrime
    (v : HeightOneSpectrum W.CoordinateRing) :
    ordInftyValuationSubring W ≠ HeightOneSpectrum.valuationSubringAtPrime W.FunctionField v :=
  fun h => genX_notMem_ordInftyValuationSubring (h ▸ genX_mem_valuationSubringAtPrime v)

end Affine

end WeierstrassCurve.Affine
