/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import Mathlib.AlgebraicGeometry.EllipticCurve.IsomOfJ
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import EllipticCurves.Fixtures

/-!
# A change of variables over an algebraic extension descends to a FINITE subextension

Mathlib proves that two elliptic curves over a **separably closed** field with the same
`j`-invariant are related by an admissible change of variables over that field:
`WeierstrassCurve.exists_variableChange_of_j_eq`, in
`Mathlib/AlgebraicGeometry/EllipticCurve/IsomOfJ.lean`.  That is the twist step of Silverman AEC
VII.5.5, and this file is the bridge that makes it usable here.

## ⚠️⚠️ The obstruction this file exists to remove

**A separable closure carries no discrete valuation, so `exists_variableChange_of_j_eq` cannot be
fed to any statement in `EllipticCurves.Reduction`.**  Its `[IsSepClosed F]` forces `F` to be an
infinite algebraic extension of the base whenever the base is not already separably closed, and
the extensions of a discrete valuation to such an `F` are not discrete — their value groups are
divisible by every `n`.  Every potential-reduction statement in this tree quantifies over a
*discrete* valuation subring:

* `Reduction/PotentialGoodReduction.lean`'s `isIntegral_j_of_hasGoodReduction_baseChange_over`,
* `Reduction/PotentialMultiplicativeReduction.lean`'s
  `one_lt_valuation_j_of_hasMultiplicativeReduction_baseChange_over`,
* `Reduction/PotentialReductionExclusive.lean`'s
  `not_hasGoodReduction_and_hasMultiplicativeReduction_baseChange_over`,

each binding `(A : ValuationSubring L) [IsDiscreteValuationRing A]`, and Mathlib's
`HasGoodReduction`, `IsMinimal` and `reduction` are defined only under
`[IsDiscreteValuationRing R]`.  ⇒ **the isomorphism has to be moved down to a finite extension
before this development can consume it**, and that move is what is below.  ⚠️ It is pure field
theory: no valuation, no DVR and no reduction appears in any statement in this file, and nothing
from `Reduction/` is imported.

## Main results

⚠️ **Each statement's hypotheses are named twice — in its bullet here and again in that
declaration's own headline below** — the field and `Algebra K L` instances excepted, which are left
to the signature. The bullets point at what each one ASKS rather than at what it concludes; the
conclusion is the same shape in all three — a `FiniteDimensional` intermediate field together
with a change of variables over it — and is stated once here instead of three times.

* `WeierstrassCurve.exists_intermediateField_variableChange` — the descent lemma. ⚠️ **No separable
  closedness and no ellipticity anywhere**: an algebraic `L / K`, two curves over `K`, and a change
  of variables over `L` carrying one to the other.
* `WeierstrassCurve.exists_intermediateField_variableChange_of_j_eq` — the twist step with the
  separably closed extension as a **hypothesis**, which is the reusable form: an `L` that is both
  separably closed and algebraic over `K`, two elliptic curves over `K` and `W.j = W'.j`.
* `WeierstrassCurve.exists_intermediateField_variableChange_separableClosure_of_j_eq` — the same
  with `SeparableClosure K` supplied, so the caller gives only `W.j = W'.j` and two `IsElliptic`s.

## ⚠️ No degree bound is proved, and the classical `12` is not available by this route

Each statement says *a* finite extension.  None of them bounds `[L₀ : K]`.  The classical bound
`[L₀ : K] ∣ 12`, read off the `u⁴` and `u⁶` relations on `c₄` and `c₆`, is **not** obtainable here:
`exists_variableChange_of_j_eq` is a bare existence statement over a separably closed field and
produces no information about its `u`, so the field this file adjoins is generated by whatever
quadruple that theorem happened to return.  Anyone who wants the `12` has to re-derive the change
of variables, not descend one.

## What is *not* here

* ⚠️⚠️ **The converse of VII.5.5 is not here and is not unblocked by this file alone.**  With a
  good-reduction model over `R` carrying a prescribed `j` and with this file's twist step, the
  potential-good converse still needs a third input: **a discrete valuation subring of the finite
  extension `L₀` lying over `R`.**  Whether that is reachable on the pinned Mathlib is an open
  question which nothing here answers — at this pin there is no `StrictlyHenselian`, no
  `strictHenselisation` and no `LocalField`, the same absence that makes
  `Reduction/NeronOggShafarevich.lean` rule the classical local-field form out of scope.
  `Mathlib/RingTheory/Valuation/Extension.lean` and
  `Mathlib/RingTheory/Valuation/AlgebraInstances.lean` are where to look.
* **No statement quantifying over `VariableChange K`.**  That would be false, not weaker: a curve
  and a twist of it are isomorphic only after extension, and `### Non-vacuity` below proves one
  such pair non-isomorphic over `ℚ` rather than asserting it.
* **No generalisation past algebraic `L / K`.**  Four elements of a transcendental extension
  generate no finite subextension and the descent lemma is false there.

## Two instance measurements, both run by deleting a line and rebuilding

⚠️ **`(W⁄L).IsElliptic` is supplied by `EllipticCurves.Fixture.instIsEllipticBaseChange` and by
nothing in Mathlib**, which is why an API file imports `EllipticCurves.Fixtures` here.
`WeierstrassCurve.baseChange` is a plain `def`, so Mathlib's instance for `W.map f` is not found
from it by instance search.  ⚠️ **Measured on the API half of this file**, that is with the
`EllipticCurves.Fixtures` import *and* `### Non-vacuity` below both deleted: the build reports
**two** errors and both sit on the **one** line of the `exists_variableChange_of_j_eq`
application, *"failed to synthesize instance of type class `(W⁄L).IsElliptic`"* and the
`rcases` failure that the unsynthesised `obtain` cascades into.  So it is one failing site and
not two, and deleting the import with `### Non-vacuity` left in place measures something else
entirely — that section names **two** `Fixture` curves, `y2EqX3SubX` and `y2EqX3Add4X`, at
**10** occurrences each, plus the `open EllipticCurves.Fixture` line.  ⚠️ **No second copy of that
bridge is declared here**, on the instruction in that instance's own docstring: the other general
`(W⁄F).IsElliptic` in this library,
`WeierstrassCurve.Affine.CoordinateRing.instIsEllipticBaseChange` in
`EllipticCurves.FunctionField.GaloisFunctionField`, is downstream of `Torsion/` and unreachable
from here anyway.

⚠️ `Mathlib.FieldTheory.IntermediateField.Adjoin.Basic` is **already in this file's import closure
through `Mathlib.AlgebraicGeometry.EllipticCurve.IsomOfJ`** — the file builds with that line
deleted, measured — and it is written out because `IntermediateField.finiteDimensional_adjoin` and
`IntermediateField.subset_adjoin` are used directly in the proof below.

## ⚠️ What this file is the first in the tree to use, measured at `741ab16f`

`git grep -c 'exists_variableChange_of_j_eq\|IsomOfJ' 741ab16f -- 'EllipticCurves/*.lean'` prints
nothing and exits `1`, as does the same command for `ofJ` and for `SeparableClosure`.  So the
Mathlib theorem this file consumes had no use site in the tree, and `SeparableClosure` had none
either: `IsSepClosed` occurs on **5** lines in **3** files at that sha
(`FunctionField/TateDeterminantCyclotomic.lean`, `FunctionField/WeilPairingPerfect.lean`,
`Galois/CyclotomicCharacter.lean`) and at every one of them it is a **hypothesis** on an ambient
field, never a closure that is constructed.  ⚠️ `VariableChange` occurs on **5** lines in **2**
files, both under `Reduction/`, and at none of them as the subject of a statement — three are
`(1 : VariableChange L)` inside one proof of `Reduction/GoodReductionBaseChange.lean` and two are
prose in `Reduction/ReductionBaseChange.lean`.

## References

* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], VII.5.5.
-/

open IntermediateField

namespace WeierstrassCurve

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- **A change of variables over an algebraic extension descends to a finite subextension.**  Over
a field `K` and an extension `L` with `L / K` algebraic, given two Weierstrass curves `W` and `W'`
over `K` and a change of variables `C` over `L` with `C • (W⁄L) = W'⁄L`, there is an intermediate
field `L₀` of `L / K` with `FiniteDimensional K L₀` and a change of variables over `L₀` carrying
`W⁄L₀` to `W'⁄L₀`.

⚠️ **Neither curve is assumed elliptic and `L` is not assumed separably closed**; the hypotheses
are exactly `L / K` algebraic and the change of variables `C`.

`L₀` is `K` adjoined to the four coordinates of `C`.  ⚠️ **The unit field is the only step with
content**: `C.u` is a unit of `L`, so its value is nonzero, so the value's image in the *field*
`L₀` is nonzero and `Units.mk0` remakes it a unit there.  `C.u` itself cannot be transported — a
unit of `L` is not a unit of a subring — which is why the proof rebuilds it from the value. -/
theorem exists_intermediateField_variableChange [Algebra.IsAlgebraic K L]
    {W W' : WeierstrassCurve K} (C : VariableChange L) (hC : C • (W⁄L) = W'⁄L) :
    ∃ L₀ : IntermediateField K L, FiniteDimensional K L₀ ∧
      ∃ C₀ : VariableChange L₀, C₀ • (W⁄L₀) = W'⁄L₀ := by
  classical
  set S : Set L := {(C.u : L), C.r, C.s, C.t} with hS
  have hfin : S.Finite := by
    rw [hS]; exact (((Set.finite_singleton _).insert _).insert _).insert _
  haveI : Finite S := hfin.to_subtype
  have hint : ∀ x ∈ S, IsIntegral K x := fun x _ =>
    (Algebra.IsAlgebraic.isAlgebraic (R := K) x).isIntegral
  refine ⟨adjoin K S, finiteDimensional_adjoin hint, ?_⟩
  set L₀ := adjoin K S with hL₀
  have hmem : ∀ x ∈ S, x ∈ L₀ := fun x hx => subset_adjoin K S hx
  have hu : (C.u : L) ∈ L₀ := hmem _ (by rw [hS]; simp)
  have hr : C.r ∈ L₀ := hmem _ (by rw [hS]; simp)
  have hs : C.s ∈ L₀ := hmem _ (by rw [hS]; simp)
  have ht : C.t ∈ L₀ := hmem _ (by rw [hS]; simp)
  have hune : (⟨(C.u : L), hu⟩ : L₀) ≠ 0 := by
    simp only [ne_eq, ← ZeroMemClass.coe_eq_zero, Units.ne_zero, not_false_eq_true]
  refine ⟨⟨Units.mk0 ⟨(C.u : L), hu⟩ hune, ⟨C.r, hr⟩, ⟨C.s, hs⟩, ⟨C.t, ht⟩⟩, ?_⟩
  have hbase : ∀ V : WeierstrassCurve K, (V⁄L₀).map (algebraMap L₀ L) = V⁄L := fun V => by
    simp only [WeierstrassCurve.baseChange, WeierstrassCurve.map_map,
      ← IsScalarTower.algebraMap_eq K L₀ L]
  apply WeierstrassCurve.map_injective (algebraMap L₀ L).injective
  beta_reduce
  rw [← WeierstrassCurve.map_variableChange, hbase, hbase]
  convert hC using 2
  ext <;> rfl

/-- **The twist step of Silverman VII.5.5, with the separably closed extension as a hypothesis.**
Over a field `K`, let `L` be an extension of `K` that is separably closed and algebraic over `K`,
and let `W` and `W'` be elliptic curves over `K` with `W.j = W'.j`.  Then there is an intermediate
field `L₀` of `L / K` with `FiniteDimensional K L₀` and a change of variables over `L₀` carrying
`W⁄L₀` to `W'⁄L₀`.

⚠️ `[Algebra.IsAlgebraic K L]` is a genuine hypothesis and does **not** follow from
`[IsSepClosed L]` — a separably closed field can be enormous over `K`.  Both are named, together
with the two `IsElliptic` instances and `W.j = W'.j`, and that is the whole hypothesis list.

The hypothesis form is the reusable one; it is instantiated at `SeparableClosure K` just below,
and ⚠️ it is equally instantiable at `AlgebraicClosure K` — `### Non-vacuity` below checks that
reading too, since an algebraically closed field is separably closed by
`IsSepClosed.of_isAlgClosed`. -/
theorem exists_intermediateField_variableChange_of_j_eq (L : Type*) [Field L] [Algebra K L]
    [IsSepClosed L] [Algebra.IsAlgebraic K L] (W W' : WeierstrassCurve K) [W.IsElliptic]
    [W'.IsElliptic] (hj : W.j = W'.j) :
    ∃ L₀ : IntermediateField K L, FiniteDimensional K L₀ ∧
      ∃ C₀ : VariableChange L₀, C₀ • (W⁄L₀) = W'⁄L₀ := by
  obtain ⟨C, hC⟩ := WeierstrassCurve.exists_variableChange_of_j_eq (W⁄L) (W'⁄L) <| by
    simp only [WeierstrassCurve.baseChange, WeierstrassCurve.map_j, hj]
  exact exists_intermediateField_variableChange C hC

/-- **Two elliptic curves over `K` with the same `j`-invariant are isomorphic over a finite
extension of `K`.**  The hypotheses are two `IsElliptic` instances and `W.j = W'.j`; there is no
condition on `K` at all.  The conclusion is a `FiniteDimensional` intermediate field of
`SeparableClosure K / K` together with a change of variables over it carrying `W` to `W'`.

⚠️ The base is `SeparableClosure K`, which is Mathlib's `separableClosure K (AlgebraicClosure K)`,
and both instances this needs are already there: `SeparableClosure.isSepClosed` and
`separableClosure.isAlgebraic`.  Nothing had to be proved to choose it.

⚠️ **No degree bound** — see this module's own `## ⚠️ No degree bound is proved` section. -/
theorem exists_intermediateField_variableChange_separableClosure_of_j_eq
    (W W' : WeierstrassCurve K) [W.IsElliptic] [W'.IsElliptic] (hj : W.j = W'.j) :
    ∃ L₀ : IntermediateField K (SeparableClosure K), FiniteDimensional K L₀ ∧
      ∃ C₀ : VariableChange L₀, C₀ • (W⁄L₀) = W'⁄L₀ :=
  exists_intermediateField_variableChange_of_j_eq _ W W' hj

section Nonvacuity

/-! ### Non-vacuity

⚠️⚠️ **The certificate below is over `ℚ`, and `ℚ` being far from separably closed is *proved* and
not assumed.**  That is the whole point of the check: over a separably closed `K` the headline is
trivial with `L₀ = ⊥`, so a certificate over such a base would prove nothing.

⚠️⚠️ **And it goes one step further than non-vacuity.**  `not_exists_variableChange_rat` proves
that the two curves of the certificate are **not** isomorphic over `ℚ` itself, so the finite
extension in the conclusion is doing real work and the headline is not a `VariableChange K`
statement in disguise.  The obstruction is a sign: `c₄` transforms by `u⁻¹ ^ 4`, the two values are
`48` and `-192`, and a fourth power in `ℚ` is never negative.

The pair is `Fixture.y2EqX3SubX` (`y² = x³ - x`, `Δ = 64`, `c₄ = 48`) and `Fixture.y2EqX3Add4X`
(`y² = x³ + 4x`, `Δ = -4096`, `c₄ = -192`), both of `j`-invariant `1728`. -/

open EllipticCurves.Fixture

/-- ⚠️ **`ℚ` is not separably closed**, so the certificate below is not a restatement of the
headline's trivial case.  `ℚ` has characteristic zero, hence is perfect, hence a separably closed
`ℚ` would be algebraically closed (`IsSepClosed.isAlgClosed_of_perfectField`) and `-1` would have a
square root in it.  ⚠️ The tree proves `¬ IsAlgClosed ℚ` three times already
(`FunctionField/PlaceDegreeComparison.lean`, `FunctionField/WeilPairingAlternatingBaseChange.lean`,
`FunctionField/WeilPairingAlternatingBaseChangeN.lean`); this is the separable-closure form of the
same two lines, and it is `private` for the same reason those are. -/
private theorem rat_not_isSepClosed : ¬ IsSepClosed ℚ := fun h => by
  obtain ⟨z, hz⟩ := @IsAlgClosed.exists_pow_nat_eq ℚ _
    (@IsSepClosed.isAlgClosed_of_perfectField ℚ _ h _) (-1) 2 two_pos
  nlinarith [sq_nonneg z]

/-- `j = 48³ / 64 = 1728` for `y² = x³ - x`. -/
private lemma j_y2EqX3SubX : (y2EqX3SubX ℚ).j = 1728 := by
  rw [WeierstrassCurve.j, Units.val_inv_eq_inv_val, WeierstrassCurve.coe_Δ']
  norm_num [y2EqX3SubX, WeierstrassCurve.Δ, WeierstrassCurve.c₄, WeierstrassCurve.b₂,
    WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈]

/-- `j = (-192)³ / (-4096) = 1728` for `y² = x³ + 4x`. -/
private lemma j_y2EqX3Add4X : (y2EqX3Add4X ℚ).j = 1728 := by
  rw [WeierstrassCurve.j, Units.val_inv_eq_inv_val, WeierstrassCurve.coe_Δ']
  norm_num [y2EqX3Add4X, WeierstrassCurve.Δ, WeierstrassCurve.c₄, WeierstrassCurve.b₂,
    WeierstrassCurve.b₄, WeierstrassCurve.b₆, WeierstrassCurve.b₈]

/-- ⚠️⚠️ **The two certificate curves are NOT isomorphic over `ℚ`**, so the extension in the
headline cannot be dropped and the statement is not secretly a `VariableChange ℚ` one.  `c₄`
transforms by `u⁻¹ ^ 4` (`WeierstrassCurve.variableChange_c₄`), the two `c₄` are `48` and `-192`,
and `u⁻¹ ^ 4 * 48 = -192` asks a fourth power in `ℚ` to be `-4`. -/
private theorem not_exists_variableChange_rat :
    ¬ ∃ C : VariableChange ℚ, C • (y2EqX3SubX ℚ) = y2EqX3Add4X ℚ := by
  rintro ⟨C, hC⟩
  have h := congrArg WeierstrassCurve.c₄ hC
  rw [WeierstrassCurve.variableChange_c₄] at h
  norm_num [y2EqX3SubX, y2EqX3Add4X, WeierstrassCurve.c₄, WeierstrassCurve.b₂,
    WeierstrassCurve.b₄] at h
  have hx : ((C.u : ℚ)) ≠ 0 := C.u.ne_zero
  have h4 : (0 : ℚ) < (C.u : ℚ) ^ 4 := by positivity
  rw [inv_mul_eq_div, div_eq_iff h4.ne'] at h
  nlinarith [h4]

/-- The certificate at `SeparableClosure ℚ`: `y² = x³ - x` and `y² = x³ + 4x` have the same
`j`-invariant, are not isomorphic over `ℚ` by `not_exists_variableChange_rat`, and are related by
a change of variables over a finite extension of `ℚ`. -/
example : ∃ L₀ : IntermediateField ℚ (SeparableClosure ℚ), FiniteDimensional ℚ L₀ ∧
    ∃ C₀ : VariableChange L₀, C₀ • ((y2EqX3SubX ℚ)⁄L₀) = (y2EqX3Add4X ℚ)⁄L₀ :=
  exists_intermediateField_variableChange_separableClosure_of_j_eq _ _
    (j_y2EqX3SubX.trans j_y2EqX3Add4X.symm)

/-- ⚠️ The same certificate at `AlgebraicClosure ℚ`, which is the second reading of the hypothesis
form: `IsSepClosed.of_isAlgClosed` supplies `[IsSepClosed]` and
`AlgebraicClosure.isAlgebraic`-style instances supply `[Algebra.IsAlgebraic]`, so **both concrete
bases work and nothing had to be proved for either**.  Recorded because which object to instantiate
at was an open question when this file was specified. -/
example : ∃ L₀ : IntermediateField ℚ (AlgebraicClosure ℚ), FiniteDimensional ℚ L₀ ∧
    ∃ C₀ : VariableChange L₀, C₀ • ((y2EqX3SubX ℚ)⁄L₀) = (y2EqX3Add4X ℚ)⁄L₀ :=
  exists_intermediateField_variableChange_of_j_eq _ _ _
    (j_y2EqX3SubX.trans j_y2EqX3Add4X.symm)

end Nonvacuity

end WeierstrassCurve
