/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import Mathlib.GroupTheory.FiniteAbelian.Basic
import Mathlib.Algebra.Module.ZMod
import Mathlib.Data.ZMod.QuotientRing

/-!
# Classification core for the `n`-torsion structure theorem

This file proves the pure finite-abelian-group input to the elliptic-curve `n`-torsion structure
theorem `E[n] ≃ (ℤ/nℤ)²`: a finite additive abelian group `A` that is killed by `n`, has
`Nat.card A = n²`, and whose `p`-torsion is small (`#A[p] ≤ p²` for every prime `p`) is
isomorphic to `ZMod n × ZMod n`.

The geometric content (the count `#E[n] = n²` and the rank bound) is supplied elsewhere; this
file is independent of the division-polynomial / formal-group machinery.

## Main statements

* `AddCommGroup.equiv_zmod_sq_of_two_gen`: a finite abelian group killed by `n`, generated by two
  elements, with `Nat.card A = n²`, is isomorphic to `ZMod n × ZMod n`.
* `AddCommGroup.equiv_zmod_sq_of_card_sq`: the full classification core (killed by `n`,
  `Nat.card A = n²`, and `#A[p] ≤ p²` for all primes `p`).

## References

* [Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.6, Corollary 6.4
  (the group-theoretic step only).
-/

open scoped DirectSum Function

namespace AddCommGroup

variable {A : Type*} [AddCommGroup A]

/-- A finite abelian group `A` that is killed by `n`, generated by two elements, and has
`Nat.card A = n²`, is isomorphic to `ZMod n × ZMod n`.

The two-element generating set gives a surjection `(ZMod n)² → A`; equality of cardinalities
upgrades it to a bijection. -/
theorem equiv_zmod_sq_of_two_gen [Finite A] {n : ℕ} (hn : 0 < n)
    (hkill : ∀ a : A, n • a = 0) (hcard : Nat.card A = n ^ 2)
    {g₁ g₂ : A} (hgen : AddSubgroup.closure {g₁, g₂} = ⊤) :
    Nonempty (A ≃+ ZMod n × ZMod n) := by
  haveI : NeZero n := ⟨hn.ne'⟩
  haveI : Module (ZMod n) A := AddCommGroup.zmodModule hkill
  -- The `ZMod n`-span of `{g₁, g₂}` is everything, because scalar multiplication is `nsmul`.
  have hspan : Submodule.span (ZMod n) {g₁, g₂} = ⊤ := by
    rw [Submodule.eq_top_iff']
    intro a
    have ha : a ∈ AddSubgroup.closure {g₁, g₂} := by rw [hgen]; exact AddSubgroup.mem_top a
    refine (AddSubgroup.closure_le
      (Submodule.span (ZMod n) {g₁, g₂}).toAddSubgroup).mpr ?_ ha
    intro x hx
    exact Submodule.subset_span hx
  -- The linear surjection `(ZMod n)² → A`, `(r, s) ↦ r • g₁ + s • g₂`.
  let f : (ZMod n × ZMod n) →ₗ[ZMod n] A :=
    (LinearMap.toSpanSingleton (ZMod n) A g₁).coprod (LinearMap.toSpanSingleton (ZMod n) A g₂)
  have hrange : LinearMap.range f = ⊤ := by
    rw [LinearMap.range_coprod, ← LinearMap.span_singleton_eq_range,
      ← LinearMap.span_singleton_eq_range, ← Submodule.span_union, Set.singleton_union, hspan]
  have hsurj : Function.Surjective f := LinearMap.range_eq_top.mp hrange
  -- Equal finite cardinality upgrades the surjection to a bijection.
  haveI : Finite (ZMod n × ZMod n) := inferInstance
  have hcard2 : Nat.card (ZMod n × ZMod n) = n ^ 2 := by
    rw [Nat.card_prod, Nat.card_zmod, sq]
  haveI := Fintype.ofFinite A
  haveI := Fintype.ofFinite (ZMod n × ZMod n)
  have hcardeq : Fintype.card (ZMod n × ZMod n) = Fintype.card A := by
    rw [← Nat.card_eq_fintype_card, ← Nat.card_eq_fintype_card, hcard, hcard2]
  have hbij : Function.Bijective f :=
    (Fintype.bijective_iff_surjective_and_card f).mpr ⟨hsurj, hcardeq⟩
  exact ⟨(LinearEquiv.ofBijective f hbij).symm.toAddEquiv⟩

/-- A finite direct sum of cyclic groups `ZMod (a k)` whose orders are pairwise coprime is itself
cyclic: every element is an integer multiple of the "all ones" element `∑ k, of k 1`. This is the
Chinese remainder theorem repackaged for direct sums. -/
theorem zmultiples_sum_of_one_eq_top {κ : Type*} [Fintype κ] [DecidableEq κ] (a : κ → ℕ)
    (ha : ∀ k, a k ≠ 0) (hco : Pairwise (Nat.Coprime on a)) :
    AddSubgroup.zmultiples (∑ k, DirectSum.of (fun k => ZMod (a k)) k 1) = ⊤ := by
  haveI : NeZero (∏ k, a k) := ⟨Finset.prod_ne_zero_iff.mpr fun k _ => ha k⟩
  set G : (⨁ k, ZMod (a k)) := ∑ k, DirectSum.of (fun k => ZMod (a k)) k 1 with hG
  -- The isomorphism `⨁ ZMod (a k) ≃+ ZMod (∏ a k)` given by CRT.
  let Φ : (⨁ k, ZMod (a k)) ≃+ ZMod (∏ k, a k) :=
    (DirectSum.addEquivProd (fun k => ZMod (a k))).trans (ZMod.prodEquivPi a hco).symm.toAddEquiv
  -- `Φ` sends the all-ones element to `1`.
  have hprod : DirectSum.addEquivProd (fun k => ZMod (a k)) G = fun _ => 1 := by
    funext k
    have hval : DirectSum.addEquivProd (fun k => ZMod (a k)) G k = G k := rfl
    rw [hval, hG, DirectSum.sum_apply]
    simp [DirectSum.of_apply]
  have hsymm : (ZMod.prodEquivPi a hco).symm (fun _ => 1) = 1 := by
    apply (ZMod.prodEquivPi a hco).injective
    rw [RingEquiv.apply_symm_apply]
    funext k
    rw [ZMod.prodEquivPi_apply, map_one]
  have hΦG : Φ G = 1 := by
    have h1 : Φ G
        = (ZMod.prodEquivPi a hco).symm (DirectSum.addEquivProd (fun k => ZMod (a k)) G) := rfl
    rw [h1, hprod, hsymm]
  rw [AddSubgroup.eq_top_iff']
  intro d
  have hd : d = (Φ d).val • G := by
    have h2 : Φ d = (Φ d).val • Φ G := by
      rw [hΦG, nsmul_eq_mul, mul_one, ZMod.natCast_zmod_val]
    calc d = Φ.symm (Φ d) := (Φ.symm_apply_apply d).symm
      _ = Φ.symm ((Φ d).val • Φ G) := by rw [← h2]
      _ = (Φ d).val • Φ.symm (Φ G) := by rw [map_nsmul]
      _ = (Φ d).val • G := by rw [Φ.symm_apply_apply]
  rw [hd]
  exact nsmul_mem (AddSubgroup.mem_zmultiples G) _

/-- If the index set of a finite direct sum of cyclic groups `ZMod (a i)` can be `2`-coloured
so that within each colour class the orders `a i` are pairwise coprime, then the direct sum is
generated by two elements (the sum of the standard generators over each colour class). -/
theorem exists_two_gen_of_coloring {ι : Type*} [Finite ι] (a : ι → ℕ)
    (ha : ∀ i, a i ≠ 0) (color : ι → Bool)
    (hc : ∀ i j, color i = color j → i ≠ j → (a i).Coprime (a j)) :
    ∃ g₁ g₂ : ⨁ i, ZMod (a i),
      AddSubgroup.closure ({g₁, g₂} : Set (⨁ i, ZMod (a i))) = ⊤ := by
  classical
  haveI := Fintype.ofFinite ι
  set G : Bool → (⨁ i, ZMod (a i)) :=
    fun b => ∑ i ∈ Finset.univ.filter (fun i => color i = b),
      DirectSum.of (fun i => ZMod (a i)) i 1 with hGdef
  refine ⟨G false, G true, ?_⟩
  -- Every standard generator `of i 1` lies in the closure of `{G false, G true}`.
  have key : ∀ i, DirectSum.of (fun i => ZMod (a i)) i 1 ∈
      AddSubgroup.closure ({G false, G true} : Set (⨁ i, ZMod (a i))) := by
    intro i
    let κ := {i' : ι // color i' = color i}
    let incl : (⨁ j : κ, ZMod (a j.val)) →+ (⨁ i, ZMod (a i)) :=
      DirectSum.toAddMonoid (fun j => DirectSum.of (fun i => ZMod (a i)) j.val)
    have hcop : Pairwise (Nat.Coprime on fun j : κ => a j.val) := by
      intro j₁ j₂ hj
      exact hc j₁.val j₂.val (j₁.2.trans j₂.2.symm) (fun h => hj (Subtype.ext h))
    have htop := zmultiples_sum_of_one_eq_top (fun j : κ => a j.val) (fun j => ha j.val) hcop
    have hi : DirectSum.of (fun j : κ => ZMod (a j.val)) ⟨i, rfl⟩ 1 ∈
        AddSubgroup.zmultiples (∑ j, DirectSum.of (fun j : κ => ZMod (a j.val)) j 1) := by
      rw [htop]; exact AddSubgroup.mem_top _
    rw [AddSubgroup.mem_zmultiples_iff] at hi
    obtain ⟨k, hk⟩ := hi
    have himg : incl (DirectSum.of (fun j : κ => ZMod (a j.val)) ⟨i, rfl⟩ 1)
        = DirectSum.of (fun i => ZMod (a i)) i 1 := by
      simp only [incl, DirectSum.toAddMonoid_of]
    have hGb : incl (∑ j, DirectSum.of (fun j : κ => ZMod (a j.val)) j 1) = G (color i) := by
      rw [map_sum, hGdef]
      simp only [incl, DirectSum.toAddMonoid_of]
      exact (Finset.sum_subtype (Finset.univ.filter fun i' => color i' = color i)
        (p := fun i' => color i' = color i) (fun x => by simp)
        (fun i' => DirectSum.of (fun i => ZMod (a i)) i' 1)).symm
    have heq : DirectSum.of (fun i => ZMod (a i)) i 1 = k • G (color i) := by
      rw [← himg, ← hk, map_zsmul, hGb]
    rw [heq]
    refine zsmul_mem (AddSubgroup.subset_closure ?_) k
    cases h : color i <;> simp
  rw [eq_top_iff]
  intro d _
  rw [← DirectSum.sum_univ_of d]
  refine AddSubgroup.sum_mem _ (fun i _ => ?_)
  have hdi : d i = (d i).val • (1 : ZMod (a i)) := by
    haveI : NeZero (a i) := ⟨ha i⟩
    rw [nsmul_eq_mul, mul_one, ZMod.natCast_zmod_val]
  have hof : DirectSum.of (fun i => ZMod (a i)) i (d i)
      = (d i).val • DirectSum.of (fun i => ZMod (a i)) i 1 := by
    conv_lhs => rw [hdi]
    rw [map_nsmul]
  rw [hof]
  exact nsmul_mem (key i) _

/-- Transporting the `q`-torsion count across an isomorphism. -/
theorem card_nsmul_eq_zero_congr {B : Type*} [AddCommGroup B] (e : A ≃+ B) (q : ℕ) :
    Nat.card {a : A // q • a = 0} = Nat.card {b : B // q • b = 0} := by
  apply Nat.card_congr
  refine Equiv.subtypeEquiv e.toEquiv (fun a => ?_)
  change q • a = 0 ↔ q • e a = 0
  rw [← map_nsmul, EmbeddingLike.map_eq_zero_iff]

/-- A cyclic group `ZMod (q ^ e)` with `e ≥ 1` has at least `q` elements killed by `q`
(namely the multiples of `q ^ (e-1)`). -/
theorem card_le_card_nsmul_eq_zero_zmod {q e : ℕ} (hq : 0 < q) (he : 0 < e) :
    q ≤ Nat.card {x : ZMod (q ^ e) // q • x = 0} := by
  have hqe : q ^ e ≠ 0 := pow_ne_zero _ hq.ne'
  haveI : NeZero (q ^ e) := ⟨hqe⟩
  set y : ZMod (q ^ e) := ((q ^ (e - 1) : ℕ) : ZMod (q ^ e)) with hy
  have hqy : q • y = 0 := by
    rw [hy, nsmul_eq_mul, ← Nat.cast_mul,
      show q * q ^ (e - 1) = q ^ e by rw [← pow_succ', Nat.sub_add_cancel he]]
    exact ZMod.natCast_self _
  -- the subgroup of multiples of `y` lands in the `q`-torsion
  have hsub : ∀ z ∈ AddSubgroup.zmultiples y, q • z = 0 := by
    intro z hz
    obtain ⟨k, rfl⟩ := AddSubgroup.mem_zmultiples_iff.mp hz
    rw [smul_comm, hqy, smul_zero]
  have hcard : q ≤ Nat.card (AddSubgroup.zmultiples y) := by
    rw [Nat.card_zmultiples, hy, ZMod.addOrderOf_coe _ hqe,
      Nat.gcd_eq_right (pow_dvd_pow q (Nat.sub_le e 1)),
      Nat.pow_div (Nat.sub_le e 1) hq, Nat.sub_sub_self he, pow_one]
  refine hcard.trans (Nat.card_le_card_of_injective
    (fun z => (⟨z.1, hsub z.1 z.2⟩ : {x : ZMod (q ^ e) // q • x = 0}))
    (fun z₁ z₂ h => Subtype.ext (by simpa using h)))

/-- The `q`-torsion of a finite direct sum splits as a product over the summands. -/
theorem card_nsmul_eq_zero_directSum {ι : Type*} [Fintype ι]
    (B : ι → Type*) [∀ i, AddCommGroup (B i)] (q : ℕ) :
    Nat.card {d : ⨁ i, B i // q • d = 0} = ∏ i, Nat.card {x : B i // q • x = 0} := by
  classical
  rw [card_nsmul_eq_zero_congr (DirectSum.addEquivProd B) q]
  rw [Nat.card_congr (show {f : (∀ i, B i) // q • f = 0} ≃ ∀ i, {x : B i // q • x = 0} from
    (Equiv.subtypeEquiv (Equiv.refl _) (fun f => by
      simp only [Equiv.refl_apply, funext_iff, Pi.smul_apply, Pi.zero_apply])).trans
      (Equiv.subtypePiEquivPi))]
  exact Nat.card_pi

/-- **Classification core for the `n`-torsion structure theorem.** A finite abelian group `A` that
is killed by `n > 0`, has `Nat.card A = n²`, and whose `p`-torsion satisfies `#A[p] ≤ p²` for
every prime `p`, is isomorphic to `ZMod n × ZMod n`. -/
theorem equiv_zmod_sq_of_card_sq [Finite A] {n : ℕ} (hn : 0 < n)
    (hkill : ∀ a : A, n • a = 0) (hcard : Nat.card A = n ^ 2)
    (hrank : ∀ p : ℕ, p.Prime → Nat.card {a : A // p • a = 0} ≤ p ^ 2) :
    Nonempty (A ≃+ ZMod n × ZMod n) := by
  classical
  obtain ⟨ι, hι, p, hp, ef, ⟨e⟩⟩ := AddCommGroup.equiv_directSum_zmod_of_finite A
  set a : ι → ℕ := fun i => p i ^ ef i with ha
  have ha0 : ∀ i, a i ≠ 0 := fun i => pow_ne_zero _ (hp i).pos.ne'
  -- Rank bound: for each prime `q`, at most two nontrivial summands carry the prime `q`.
  have hbound : ∀ q, q.Prime →
      (Finset.univ.filter (fun i => p i = q ∧ 0 < ef i)).card ≤ 2 := by
    intro q hq
    have h1 : ∀ i, 1 ≤ Nat.card {x : ZMod (a i) // q • x = 0} := by
      intro i
      haveI : NeZero (a i) := ⟨ha0 i⟩
      haveI : Nonempty {x : ZMod (a i) // q • x = 0} := ⟨⟨0, smul_zero q⟩⟩
      exact Nat.card_pos
    have hq2 : ∀ i ∈ Finset.univ.filter (fun i => p i = q ∧ 0 < ef i),
        q ≤ Nat.card {x : ZMod (a i) // q • x = 0} := by
      intro i hi
      rw [Finset.mem_filter] at hi
      obtain ⟨-, hpi, hei⟩ := hi
      have hai : a i = q ^ ef i := by simp only [ha, hpi]
      rw [hai]
      exact card_le_card_nsmul_eq_zero_zmod hq.pos hei
    have hprodge : q ^ (Finset.univ.filter (fun i => p i = q ∧ 0 < ef i)).card ≤
        Nat.card {x : A // q • x = 0} := by
      rw [card_nsmul_eq_zero_congr e q, card_nsmul_eq_zero_directSum]
      calc q ^ (Finset.univ.filter (fun i => p i = q ∧ 0 < ef i)).card
          = ∏ _i ∈ Finset.univ.filter (fun i => p i = q ∧ 0 < ef i), q := by
            rw [Finset.prod_const]
        _ ≤ ∏ i ∈ Finset.univ.filter (fun i => p i = q ∧ 0 < ef i),
              Nat.card {x : ZMod (a i) // q • x = 0} := Finset.prod_le_prod' hq2
        _ ≤ ∏ i, Nat.card {x : ZMod (a i) // q • x = 0} :=
            Finset.prod_le_prod_of_subset_of_one_le' (Finset.subset_univ _)
              (fun i _ _ => h1 i)
    exact (Nat.pow_le_pow_iff_right hq.one_lt).mp (hprodge.trans (hrank q hq))
  -- Two-colour the summands so that equal primes get different colours.
  let fo := Fintype.equivFin ι
  let color : ι → Bool := fun i => decide (∃ j, fo j < fo i ∧ p j = p i ∧ 0 < ef j)
  have hcolor : ∀ i j, color i = color j → i ≠ j → (a i).Coprime (a j) := by
    intro i j hcc hne
    by_contra hnc
    have hei : 0 < ef i := by
      rcases Nat.eq_zero_or_pos (ef i) with h | h
      · exact absurd (by rw [ha]; simp [h]) hnc
      · exact h
    have hej : 0 < ef j := by
      rcases Nat.eq_zero_or_pos (ef j) with h | h
      · exact absurd (by rw [ha]; simp [h]) hnc
      · exact h
    have hpij : p i = p j := by
      by_contra hpne
      have hcopow : (p i ^ ef i).Coprime (p j ^ ef j) :=
        Nat.Coprime.pow (ef i) (ef j) ((Nat.coprime_primes (hp i) (hp j)).mpr hpne)
      exact hnc (by simpa only [ha] using hcopow)
    have hfij : fo i ≠ fo j := fun h => hne (fo.injective h)
    -- three distinct nontrivial summands with prime `p i`, contradicting `hbound`.
    have contra : ∀ k, k ≠ i → k ≠ j → p k = p i → 0 < ef k → False := by
      intro k hki hkj hk2 hk3
      have h2lt : 2 < (Finset.univ.filter (fun i' => p i' = p i ∧ 0 < ef i')).card :=
        Finset.two_lt_card_iff.mpr ⟨k, i, j,
          Finset.mem_filter.mpr ⟨Finset.mem_univ _, hk2, hk3⟩,
          Finset.mem_filter.mpr ⟨Finset.mem_univ _, rfl, hei⟩,
          Finset.mem_filter.mpr ⟨Finset.mem_univ _, hpij.symm, hej⟩, hki, hkj, hne⟩
      exact absurd (hbound (p i) (hp i)) (by omega)
    rcases lt_trichotomy (fo i) (fo j) with hlt | heq | hgt
    · have hcj : color j = true := by
        simp only [color, decide_eq_true_eq]; exact ⟨i, hlt, hpij, hei⟩
      have hci : color i = true := hcc ▸ hcj
      simp only [color, decide_eq_true_eq] at hci
      obtain ⟨k, hk1, hk2, hk3⟩ := hci
      exact contra k (fun h => (ne_of_lt hk1) (congrArg fo h))
        (fun h => (ne_of_lt (hk1.trans hlt)) (congrArg fo h)) hk2 hk3
    · exact hfij heq
    · have hci : color i = true := by
        simp only [color, decide_eq_true_eq]; exact ⟨j, hgt, hpij.symm, hej⟩
      have hcj : color j = true := hcc ▸ hci
      simp only [color, decide_eq_true_eq] at hcj
      obtain ⟨k, hk1, hk2, hk3⟩ := hcj
      exact contra k (fun h => (ne_of_lt (hk1.trans hgt)) (congrArg fo h))
        (fun h => (ne_of_lt hk1) (congrArg fo h)) (hk2.trans hpij.symm) hk3
  -- Assemble: two generators of the direct sum, pulled back to `A`.
  obtain ⟨G₀, G₁, hG⟩ := exists_two_gen_of_coloring a ha0 color hcolor
  refine equiv_zmod_sq_of_two_gen hn hkill hcard (g₁ := e.symm G₀) (g₂ := e.symm G₁) ?_
  have himg : (e.symm : (⨁ i, ZMod (a i)) →+ A) '' {G₀, G₁} = {e.symm G₀, e.symm G₁} := by
    simp [Set.image_insert_eq]
  rw [show ({e.symm G₀, e.symm G₁} : Set A) = (e.symm : (⨁ i, ZMod (a i)) →+ A) '' {G₀, G₁} from
    himg.symm, ← AddMonoidHom.map_closure, hG,
    AddSubgroup.map_top_of_surjective _ e.symm.surjective]

end AddCommGroup
