/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.Torsion.EllipticNetSlices
import Mathlib.Algebra.DualNumber

/-!
# The regularity hypothesis of `isEllipticNet_of_isEllipticSequence` is necessary

`EllipticCurves.Torsion.EllipticNetSlices` proves

```
IsEllipticNet W  ↔  IsEllipticSequence W          (isEllipticNet_iff_isEllipticSequence)
```

for any `W : ℤ → R` over any `CommRing` whose values at nonzero indices are **regular**, and
records that the hypothesis `hreg` was *not known* to be necessary.  It is: this file exhibits an
odd `W` over an explicit finite `CommRing` that is an elliptic sequence and is **not** an elliptic
net.  So `hreg` cannot simply be deleted, and the `↔` is not a theorem about arbitrary sequences.

## Why a counterexample exists at all: one grading, and the number `7`

Give the polynomial ring `ℤ[W_n : n ∈ ℤ]` the grading `deg (W n) = n ^ 2`.  Every one of the three
products of

```
rel W p q r s = W (p+q+s) W (p-q) W (r+s) W r - W (p+r+s) W (p-r) W (q+s) W q
                  + W (q+r+s) W (q-r) W (p+s) W p
```

then has the **same** degree `2 * (p² + q² + r² + s² + ps + qs + rs)` — expand and compare — so
`rel` is homogeneous, of degree `2 * (a² + b² + c²)` on the `s = 0` layer.

Now `rel W p q r s` is homogeneous of *polynomial* degree `4` as well, and so is every `s = 0`
relator, so an `s ≠ 0` relator lies in the ideal generated by the `s = 0` layer **iff** it lies in
the `ℤ`-linear span of that layer — a multiplier would have to be a constant.  Gradings therefore
decide the question, and the smallest instance is decided by a classical fact:

* `rel W 1 1 1 1 = W 3 * W 0 * W 2 * W 1`, of degree `9 + 0 + 4 + 1 = 14 = 2 * 7`;
* an `s = 0` relator of degree `14` would need `a² + b² + c² = 7`, and `7 = 8 * 0 + 7` is **not** a
  sum of three squares (Legendre's three-square theorem).

So no `ℤ`-combination of the `s = 0` layer is `rel W 1 1 1 1`: the *universal* elliptic sequence is
not an elliptic net, and any ring in which `W 3 * W 0 * W 2 * W 1` survives is a counterexample.
⚠️ The argument above is the *motivation* and is not formalised here; what is formalised is a
concrete witness, which needs none of it.

## The witness

`isEllipticSequence_of_mul_self_eq_zero` is the whole of the `s = 0` side: each of the three
products of `rel W p q r 0` carries a repeated factor — `W r * W r`, `W q * W q`, `W p * W p` — so
`∀ n, W n * W n = 0` makes **every** `s = 0` relator vanish termwise, with no cancellation and no
hypothesis on `W` at all.  The `s ≠ 0` relator `rel W 1 1 1 1 = W 3 * W 0 * W 2 * W 1` has no
repeated factor, and that is the entire mechanism.

What is needed, then, is a `CommRing` with four square-zero elements whose product is nonzero.
`SqZeroRing` is three nested dual numbers over `ZMod 4`, and the four elements are `2`, `ε₁`, `ε₂`
and `ε₃`, one from each layer; `sqZeroSeq` places them at the indices `0, 1, 2, 3` and extends
oddly.  ⚠️ Three nested layers rather than four because `ZMod 4` supplies the fourth square-zero
direction itself, `2 * 2 = 0`; `2 + 2 = 0` is also what makes the odd extension consistent at the
index `0`, where oddness forces `W 0 = - W 0`.

## ⚠️ What this settles and what it does not

* It settles that `hreg` cannot be **deleted** from
  `IsEllipticNet.isEllipticNet_of_isEllipticSequence` or from
  `IsEllipticNet.isEllipticNet_iff_isEllipticSequence`.
* ⚠️ It does **not** show that `hreg` is the weakest workable hypothesis.  The witness has
  `W n * W n = 0` at *every* index, so regularity fails as badly as it can; nothing here bears on
  intermediate hypotheses.
* ⚠️ It says **nothing** about `IsEllipticNet.isEllipticNet_iff_rel_one`, which also assumes
  `W 1 = 1`.  The witness is odd (`sqZeroSeq_odd`) but not normalised, and cannot be repaired to be:
  `sqZeroSeq_one_ne_one` records that `W 1 * W 1 = 0` forces `W 1 ≠ 1` in a nontrivial ring.
  Whether `hreg` is removable *for normalised* `W` is **unmeasured**, and this file does not
  measure it.
* ⚠️ It bears on **nothing downstream**.  For `normEDS` and for the division polynomials both
  collapses are theorems conditional on `WardGapCore` alone
  (`WeierstrassCurve.normEDS_isEllipticNet_of_gapCore`), because `normEDS` over the integral domain
  `UnivEDS` satisfies `hreg` outright.

## Main statements

* `IsEllipticNet.isEllipticSequence_of_mul_self_eq_zero` : a square-zero sequence over any
  `CommRing` is an elliptic sequence.
* `IsEllipticNet.sqZeroSeq` : the witness, over `IsEllipticNet.SqZeroRing`, with
  `IsEllipticNet.sqZeroSeq_odd`, `IsEllipticNet.isEllipticSequence_sqZeroSeq` and
  `IsEllipticNet.not_isEllipticNet_sqZeroSeq`.
* **`IsEllipticNet.exists_odd_isEllipticSequence_not_isEllipticNet`** : the headline, and the
  answer to the question `EllipticNetSlices` left open.

## References

* M. Ward, *Memoir on elliptic divisibility sequences*, Amer. J. Math. 70 (1948).
* K. Stange, *Elliptic nets and elliptic curves*, Algebra & Number Theory 5 (2011).
-/

open scoped DualNumber
open TrivSqZeroExt

namespace IsEllipticNet

/-! ### Square-zero sequences are elliptic sequences -/

/-- **Every sequence whose values square to zero is an elliptic sequence**, over any `CommRing`.

⚠️ There is no cancellation here and no hypothesis on `W`: each of the three products of
`rel W p q r 0` repeats one of `W p`, `W q`, `W r`, so each vanishes on its own.  ⚠️ The same is
emphatically *not* true of `rel W p q r s` for `s ≠ 0`, whose products need **not** repeat
anything: `rel W 1 1 1 1 = W 3 * W 0 * W 2 * W 1` reads four distinct indices, and that is what
`sqZeroSeq` exploits.  ⚠️ It is *one* surviving relator that a witness needs, not a whole surviving
layer — plenty of `s ≠ 0` relators do repeat a factor and so vanish here too, for instance at
`s = -2 * q`, where the first product is again a square `W (p - q) ^ 2 * W (r + s) * W r`. -/
theorem isEllipticSequence_of_mul_self_eq_zero {R : Type*} [CommRing R] {W : ℤ → R}
    (h : ∀ n : ℤ, W n * W n = 0) : IsEllipticSequence W := by
  intro p q r
  simp only [rel, add_zero]
  linear_combination (norm := ring1) (W (p + q) * W (p - q)) * h r -
    (W (p + r) * W (p - r)) * h q + (W (q + r) * W (q - r)) * h p

/-! ### A ring with four square-zero elements of nonzero product -/

/-- The first of three dual-number layers over `ZMod 4`. -/
abbrev SqZeroRing₁ : Type := (ZMod 4)[ε]

instance : CommRing SqZeroRing₁ := inferInstance

/-- The second of three dual-number layers over `ZMod 4`. -/
abbrev SqZeroRing₂ : Type := SqZeroRing₁[ε]

instance : CommRing SqZeroRing₂ := inferInstance

/-- **The witness ring**: three nested dual-number layers over `ZMod 4`.

Its four square-zero elements of interest are `sqZeroGen₀ = 2` (from `ZMod 4`) and the `ε` of each
of the three layers.  ⚠️ Four *independent* nilpotent directions are genuinely needed: a product of
four square-zero elements can only be nonzero if no two of them are proportional, and no `ZMod n`
and no `k[X]/(Xⁿ)` supplies more than one such direction. -/
abbrev SqZeroRing : Type := SqZeroRing₂[ε]

instance : CommRing SqZeroRing := inferInstance

/-- The square-zero element `2` of `ZMod 4`, pushed into `SqZeroRing`. -/
def sqZeroGen₀ : SqZeroRing := inl (inl (inl 2))

/-- The `ε` of the innermost dual-number layer, pushed into `SqZeroRing`. -/
def sqZeroGen₁ : SqZeroRing := inl (inl (inr 1))

/-- The `ε` of the middle dual-number layer, pushed into `SqZeroRing`. -/
def sqZeroGen₂ : SqZeroRing := inl (inr 1)

/-- The `ε` of the outermost dual-number layer. -/
def sqZeroGen₃ : SqZeroRing := inr 1

lemma sqZeroGen₀_mul_self : sqZeroGen₀ * sqZeroGen₀ = 0 := by
  rw [sqZeroGen₀, inl_mul_inl, inl_mul_inl, inl_mul_inl,
    show (2 : ZMod 4) * 2 = 0 from by decide, inl_zero, inl_zero, inl_zero]

/-- `2 + 2 = 0` in `ZMod 4`, which is what lets `sqZeroSeq` be odd at the index `0`, where oddness
forces `W 0 = - W 0`. -/
lemma sqZeroGen₀_add_self : sqZeroGen₀ + sqZeroGen₀ = 0 := by
  rw [sqZeroGen₀, ← inl_add, ← inl_add, ← inl_add, show (2 : ZMod 4) + 2 = 0 from by decide,
    inl_zero, inl_zero, inl_zero]

lemma sqZeroGen₁_mul_self : sqZeroGen₁ * sqZeroGen₁ = 0 := by
  rw [sqZeroGen₁, inl_mul_inl, inl_mul_inl, inr_mul_inr, inl_zero, inl_zero]

lemma sqZeroGen₂_mul_self : sqZeroGen₂ * sqZeroGen₂ = 0 := by
  rw [sqZeroGen₂, inl_mul_inl, inr_mul_inr, inl_zero]

lemma sqZeroGen₃_mul_self : sqZeroGen₃ * sqZeroGen₃ = 0 := by rw [sqZeroGen₃, inr_mul_inr]

/-- **The product of the four generators is `inr (inr (inr 2))`**, one `inr` per layer: each
multiplication moves a generator out of the `inl` part it sits in and into the `inr` part of its
own layer, which is exactly why the product survives although every factor squares to zero. -/
lemma sqZeroGen_prod :
    sqZeroGen₀ * sqZeroGen₁ * sqZeroGen₂ * sqZeroGen₃ = inr (inr (inr 2)) := by
  rw [sqZeroGen₀, sqZeroGen₁, sqZeroGen₂, sqZeroGen₃, inl_mul_inl, inl_mul_inl, inl_mul_inr,
    inl_mul_inl, inl_mul_inr, inl_mul_inr]
  simp

lemma sqZeroGen_prod_ne_zero : sqZeroGen₀ * sqZeroGen₁ * sqZeroGen₂ * sqZeroGen₃ ≠ 0 := by
  rw [sqZeroGen_prod]
  intro h
  rw [← inr_zero] at h
  replace h := inr_injective h
  rw [← inr_zero] at h
  replace h := inr_injective h
  rw [← inr_zero] at h
  exact absurd (inr_injective h) (by decide)

/-! ### The witness sequence -/

/-- The four generators placed at the indices `0, 1, 2, 3`, and `0` elsewhere. -/
def sqZeroVal : ℤ → SqZeroRing := fun n =>
  if n = 0 then sqZeroGen₀ else if n = 1 then sqZeroGen₁ else if n = 2 then sqZeroGen₂
  else if n = 3 then sqZeroGen₃ else 0

/-- **The witness**: `sqZeroVal` extended oddly to the negative indices.

Its values square to zero at every index, so it is an elliptic sequence
(`isEllipticSequence_sqZeroSeq`); the four indices `0, 1, 2, 3` that
`rel sqZeroSeq 1 1 1 1 = W 3 * W 0 * W 2 * W 1` reads are pairwise distinct, so that one relator
does not vanish (`not_isEllipticNet_sqZeroSeq`). -/
def sqZeroSeq : ℤ → SqZeroRing := fun n => if 0 ≤ n then sqZeroVal n else -sqZeroVal (-n)

lemma sqZeroVal_mul_self (n : ℤ) : sqZeroVal n * sqZeroVal n = 0 := by
  unfold sqZeroVal
  split_ifs
  · exact sqZeroGen₀_mul_self
  · exact sqZeroGen₁_mul_self
  · exact sqZeroGen₂_mul_self
  · exact sqZeroGen₃_mul_self
  · exact mul_zero 0

lemma sqZeroSeq_mul_self (n : ℤ) : sqZeroSeq n * sqZeroSeq n = 0 := by
  unfold sqZeroSeq
  split_ifs
  · exact sqZeroVal_mul_self n
  · rw [neg_mul_neg]; exact sqZeroVal_mul_self (-n)

/-- **The witness is odd**, so the failure of `isEllipticNet_of_isEllipticSequence` without `hreg`
is not an artefact of dropping `Function.Odd`.  ⚠️ The index `0` is the only case with content:
there oddness asks for `W 0 = - W 0`, which is `sqZeroGen₀_add_self`. -/
lemma sqZeroSeq_odd : Function.Odd sqZeroSeq := by
  intro n
  rcases lt_trichotomy n 0 with h | rfl | h
  · rw [sqZeroSeq, sqZeroSeq, if_pos (by omega), if_neg (by omega), neg_neg]
  · simp only [sqZeroSeq, neg_zero, le_refl, if_pos, sqZeroVal]
    rw [eq_neg_iff_add_eq_zero]
    exact sqZeroGen₀_add_self
  · rw [sqZeroSeq, sqZeroSeq, if_neg (by omega), if_pos (by omega), neg_neg]

theorem isEllipticSequence_sqZeroSeq : IsEllipticSequence sqZeroSeq :=
  isEllipticSequence_of_mul_self_eq_zero sqZeroSeq_mul_self

lemma sqZeroSeq_zero : sqZeroSeq 0 = sqZeroGen₀ := by norm_num [sqZeroSeq, sqZeroVal]

lemma sqZeroSeq_one : sqZeroSeq 1 = sqZeroGen₁ := by norm_num [sqZeroSeq, sqZeroVal]

lemma sqZeroSeq_two : sqZeroSeq 2 = sqZeroGen₂ := by norm_num [sqZeroSeq, sqZeroVal]

lemma sqZeroSeq_three : sqZeroSeq 3 = sqZeroGen₃ := by norm_num [sqZeroSeq, sqZeroVal]

/-- **`rel W 1 1 1 1 = W 3 * W 0 * W 2 * W 1`**, evaluated at the witness.  Two of the three
products of `rel` are equal and cancel; the surviving one reads four *distinct* indices, which is
the whole difference between this relator and the `s = 0` layer. -/
lemma rel_sqZeroSeq_one :
    rel sqZeroSeq 1 1 1 1 = sqZeroGen₀ * sqZeroGen₁ * sqZeroGen₂ * sqZeroGen₃ := by
  have h : rel sqZeroSeq 1 1 1 1 =
      sqZeroSeq 0 * sqZeroSeq 1 * sqZeroSeq 2 * sqZeroSeq 3 := by
    simp only [rel]
    norm_num
    ring
  rw [h, sqZeroSeq_zero, sqZeroSeq_one, sqZeroSeq_two, sqZeroSeq_three]

theorem not_isEllipticNet_sqZeroSeq : ¬ IsEllipticNet sqZeroSeq := fun h =>
  sqZeroGen_prod_ne_zero (rel_sqZeroSeq_one ▸ h 1 1 1 1)

/-- ⚠️ **The witness is not normalised, and cannot be**: `W 1 * W 1 = 0` and `SqZeroRing` is
nontrivial.  This is why the file says nothing about `isEllipticNet_iff_rel_one`, whose hypotheses
include `W 1 = 1`. -/
lemma sqZeroSeq_one_ne_one : sqZeroSeq 1 ≠ 1 := by
  have hone : (1 : SqZeroRing) ≠ 0 := by
    intro h
    have h1 : ((1 : SqZeroRing).fst.fst.fst) = ((0 : SqZeroRing).fst.fst.fst) := by rw [h]
    rw [fst_one, fst_one, fst_one, fst_zero, fst_zero, fst_zero] at h1
    exact absurd h1 (by decide)
  intro h
  have h0 := sqZeroSeq_mul_self 1
  rw [h, one_mul] at h0
  exact hone h0

/-! ### The answer -/

/-- **The regularity hypothesis of `IsEllipticNet.isEllipticNet_of_isEllipticSequence` is
necessary**: there is an odd elliptic sequence over a `CommRing` that is not an elliptic net.

⚠️ Read the bound on this.  It says `hreg` cannot be **deleted**; it does not say `hreg` is the
weakest hypothesis that works, and it does not touch `isEllipticNet_iff_rel_one`, which also assumes
`W 1 = 1` — see `sqZeroSeq_one_ne_one` and the module docstring. -/
theorem exists_odd_isEllipticSequence_not_isEllipticNet :
    ∃ (R : Type) (_ : CommRing R) (W : ℤ → R),
      Function.Odd W ∧ IsEllipticSequence W ∧ ¬ IsEllipticNet W :=
  ⟨SqZeroRing, inferInstance, sqZeroSeq, sqZeroSeq_odd, isEllipticSequence_sqZeroSeq,
    not_isEllipticNet_sqZeroSeq⟩

end IsEllipticNet
