/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.Torsion.OmegaOnCurve

/-!
# The NUMERATOR half of "duplication composes with multiplication by `n`"

`EllipticCurves.Torsion.OmegaOnCurve` states `#404`'s crux as
`WeierstrassCurve.HasΨSqDoubling n`,

```
ΨSq₂ₙ = ΨSqₙ · (4Φₙ³ + b₂Φₙ²ΨSqₙ + 2b₄ΦₙΨSqₙ² + b₆ΨSqₙ³)      in R[X],
```

whose bracket is `Ψ₂Sq = 4X³ + b₂X² + 2b₄X + b₆` homogenised at `(Φₙ, ΨSqₙ)` — the **denominator**
of the duplication map evaluated at the `n`-division coordinates.  This file supplies the other
half, `WeierstrassCurve.HasΦDoubling n`,

```
Φ₂ₙ = Φₙ⁴ − b₄Φₙ²ΨSqₙ² − 2b₆ΦₙΨSqₙ³ − b₈ΨSqₙ⁴              in R[X],
```

the **numerator** `Φ₂ = X⁴ − b₄X² − 2b₆X − b₈` homogenised at the same pair.  Together the two say
that `x ↦ Φ₂(x)/Ψ₂Sq(x)` composed with `x ↦ Φₙ(x)/ΨSqₙ(x)` is `x ↦ Φ₂ₙ(x)/ΨSq₂ₙ(x)` numerator and
denominator separately, which is the shape a proof of the coordinate formula at `2ⁿ` would consume.

## ⚠️ Why this file exists: it answers a question, and the answer is "no"

PR #533 recorded the numerator identity as spiked, closing by `ring1` at `n = 1` and `n = 2`, and
declined to ship it with an explicit warning: *"I have no evidence its general case is easier than
the denominator half … a fourth route that closes at `n = 1, 2` should be treated the same way
until someone measures `n = 3`."*  It has now been measured, and at every index tested the two
halves behave **identically**:

* Neither is an identity in `b₂, b₄, b₆, b₈` taken as **independent** indeterminates.  Both hold at
  `n = 1` and **fail at every `n` from `2` to `24`** — verified symbolically over
  `ℚ[b₂, b₄, b₆, b₈][X]` at `n = 2, 3, 4` and by evaluation at a random point of a `61`-bit prime
  field for `n ≤ 24`.
* Both become identities the moment `4b₈ = b₂b₆ − b₄²` is imposed, i.e. over `ℤ[1/2]` with
  `b₈` eliminated, at every `n ≤ 24`.
* Sharper, and this is what makes them provable at a fixed index over an **arbitrary** `CommRing`:
  each difference is **exactly divisible** by `4b₈ − b₂b₆ + b₄²`, with a cofactor whose
  coefficients are **integers**.  Measured cofactor sizes, numerator and denominator side by side:

  | `n` | denominator (`HasΨSqDoubling`) | numerator (`HasΦDoubling`) |
  | --- | --- | --- |
  | `2` | 34 terms | 33 terms |
  | `3` | 653 terms | 652 terms |
  | `4` | 7202 terms | 7204 terms |

So the numerator half is neither easier nor harder; it is the same statement about the other
coordinate, and the `#533` warning was the right call.

## The instrument, and what it does NOT do

`WeierstrassCurve.C_b_relation` lifts Mathlib's `WeierstrassCurve.b_relation` into `R[X]`, and the
cofactors above turn each fixed index into a single `linear_combination … * W.C_b_relation` closed
by `ring1` — over an arbitrary `CommRing`, with **no characteristic hypothesis, no field, and no
universal reduction**.  `WeierstrassCurve.hasΦDoubling_two` below is that proof at `n = 2`.

⚠️ **This is an instrument for fixed indices only and discharges nothing at general `n`.**  The
cofactor is index-specific and grows by a factor of about `11` per index; there is no uniform
certificate, and none of this touches `#404`'s crux, which is the statement at **every** `n`.

⚠️ **Two further measurements, both negative, recorded so they are not re-run.**

* Neither identity is free in `(X, Ψ₂Sq, Ψ₃, preΨ₄, b₄, b₆, b₈)` either — keeping the three
  division polynomials as atoms instead of expanding them into the `bᵢ` does not make it a `ring`
  identity, so the expansion is not an artefact of how the goal is stated.
* Writing `a, b, c, d, e` for `preΨ` at `n − 2, …, n + 2`, the difference is **not** in the ideal
  generated by the single Ward instance `ψₙ₊₂ψₙ₋₂ = ψₙ₊₁ψₙ₋₁ψ₂² − ψ₃ψₙ²` (`rel n 2 1`).  That
  instance is *true* — checked at `3 ≤ n ≤ 13` — and it is the one relation the shape of the
  identity suggests, but eliminating `e` through it leaves a nonzero remainder at both parities.
  So `#404` is not reducible to a single named slice of `#260`; it needs more of the elliptic-net
  relations than that.

## Cost, and what is deliberately absent

`WeierstrassCurve.hasΦDoubling_three` was **proved** by the same certificate — the 652-term
cofactor above, over an arbitrary `CommRing`, no hypotheses — and is **not shipped**: it elaborates
in about **5 minutes**, against a whole-library build of roughly three, and it has no consumer.
⚠️ The comparison worth recording is that the certificate is the *cheap* route at `n = 3`: the
evaluated form over a field with `2` invertible, which is how
`WeierstrassCurve.Affine.hasPreΩSqAt_three` reaches the denominator half, took about **10 minutes**
in the same shape (`field_simp` then `ring1`).  Regenerating the cofactor is mechanical — divide
the expanded difference by `4b₈ − b₂b₆ + b₄²` in the variable `b₈` — so nothing is lost by leaving
it out.

## Main definitions and results

* `WeierstrassCurve.preΨ_six`, `WeierstrassCurve.preΨ_seven` : the closed forms of `preΨ₆` and
  `preΨ₇` in terms of `preΨ₅`, `Ψ₃`, `preΨ₄` and `Ψ₂Sq`, from the `preΨ'` recurrences.  General
  facts about Mathlib's division polynomials, independent of everything above.
* `WeierstrassCurve.C_b_relation` : `4·C b₈ = C b₂ · C b₆ − (C b₄)²` in `R[X]`.
* `WeierstrassCurve.HasΦDoubling` : the numerator identity, as a predicate on the index.
* `WeierstrassCurve.hasΦDoubling_zero`, `_one`, `_two`, and `WeierstrassCurve.HasΦDoubling.neg`.

## References

* [Silverman, AEC][silverman2009], Exercise 3.7 and III.4.
-/

open Polynomial

open scoped Polynomial.Bivariate

local macro "C_simp" : tactic =>
  `(tactic| simp only [map_ofNat, C_0, C_1, C_neg, C_add, C_sub, C_mul, C_pow])

namespace WeierstrassCurve

variable {R : Type*} [CommRing R] (W : WeierstrassCurve R)

/-! ### Two more closed forms for `preΨ` -/

/-- **`preΨ₆ = Ψ₃·preΨ₅ − Ψ₃·preΨ₄²`**, from the even `preΨ'` recurrence at `m = 0`. -/
lemma preΨ_six : W.preΨ 6 = W.Ψ₃ * W.preΨ 5 - W.Ψ₃ * W.preΨ₄ ^ 2 := by
  rw [show (6 : ℤ) = ((2 * (0 + 3) : ℕ) : ℤ) by norm_num, preΨ_ofNat, preΨ'_even,
    show (5 : ℤ) = ((5 : ℕ) : ℤ) by norm_num, preΨ_ofNat]
  norm_num [preΨ'_one, preΨ'_two, preΨ'_three, preΨ'_four]

/-- **`preΨ₇ = preΨ₅·Ψ₃³ − preΨ₄³·Ψ₂Sq²`**, from the odd `preΨ'` recurrence at `m = 1`. -/
lemma preΨ_seven : W.preΨ 7 = W.preΨ 5 * W.Ψ₃ ^ 3 - W.preΨ₄ ^ 3 * W.Ψ₂Sq ^ 2 := by
  rw [show (7 : ℤ) = ((2 * (1 + 2) + 1 : ℕ) : ℤ) by norm_num, preΨ_ofNat, preΨ'_odd,
    show (5 : ℤ) = ((5 : ℕ) : ℤ) by norm_num, preΨ_ofNat]
  norm_num [preΨ'_two, preΨ'_three, preΨ'_four]

/-! ### Mathlib's `b`-relation, in `R[X]` -/

/-- **`4b₈ = b₂b₆ − b₄²`, pushed through `C` into `R[X]`.**  This is Mathlib's
`WeierstrassCurve.b_relation` in the ring where the division-polynomial identities live, and it is
the one input that `ring1` cannot supply for itself: with `b₂, b₄, b₆, b₈` as independent atoms the
identities of this file are **false**, and they become true exactly modulo this relation. -/
lemma C_b_relation : (4 : R[X]) * C W.b₈ = C W.b₂ * C W.b₆ - C W.b₄ ^ 2 := by
  rw [show (4 : R[X]) = C (4 : R) by C_simp, ← C_mul, ← C_mul, ← C_pow, ← C_sub]
  exact congrArg C W.b_relation

/-! ### The numerator half -/

/-- **The numerator half of "duplication composes with multiplication by `n`"**:

```
Φ₂ₙ = Φₙ⁴ − b₄Φₙ²ΨSqₙ² − 2b₆ΦₙΨSqₙ³ − b₈ΨSqₙ⁴      in R[X].
```

The right-hand side is `Φ₂ = X⁴ − b₄X² − 2b₆X − b₈` homogenised at `(Φₙ, ΨSqₙ)`, so together with
`WeierstrassCurve.HasΨSqDoubling` — which does the same for the denominator `Ψ₂Sq` — this says that
the duplication map applied to the `n`-division coordinates gives the `2n`-division coordinates,
numerator and denominator separately.

⚠️ **This is not a weaker statement than the crux and it is not a step towards it.**  Every
measurement in the module docstring puts it on exactly the same footing as
`WeierstrassCurve.HasΨSqDoubling`: same failure as a free identity in the `bᵢ` from `n = 2` onwards,
same exact divisibility by `4b₈ − b₂b₆ + b₄²`, cofactors of the same size to within one term. -/
def HasΦDoubling (n : ℤ) : Prop :=
  W.Φ (2 * n) = W.Φ n ^ 4 - C W.b₄ * W.Φ n ^ 2 * W.ΨSq n ^ 2 -
    2 * C W.b₆ * W.Φ n * W.ΨSq n ^ 3 - C W.b₈ * W.ΨSq n ^ 4

/-- **The identity is an even function of the index**, since `Φ` and `ΨSq` both are. -/
lemma HasΦDoubling.neg {W : WeierstrassCurve R} {n : ℤ} (h : W.HasΦDoubling n) :
    W.HasΦDoubling (-n) := by
  rw [HasΦDoubling, mul_neg, Φ_neg, Φ_neg, ΨSq_neg]
  exact h

/-- **At `n = 0`.**  `Φ₀ = 1` and `ΨSq₀ = 0`, so both sides are `1`. -/
lemma hasΦDoubling_zero : W.HasΦDoubling 0 := by
  rw [HasΦDoubling]
  norm_num

/-- **At `n = 1`.**  `Φ₁ = X` and `ΨSq₁ = 1`, so this is the definition of
`Φ₂ = X⁴ − b₄X² − 2b₆X − b₈`. -/
lemma hasΦDoubling_one : W.HasΦDoubling 1 := by
  rw [HasΦDoubling, show (2 : ℤ) * 1 = 2 by norm_num, Φ_two, Φ_one, ΨSq_one]
  C_simp
  ring1

set_option maxRecDepth 100000 in
/-- **At `n = 2`**, over an arbitrary `CommRing`.

⚠️ **`ring1` alone cannot do this**, and that is not a presentation artefact: with `b₂, b₄, b₆, b₈`
as independent indeterminates the identity is **false** (it holds only at `n = 0, 1`), and keeping
`Ψ₂Sq, Ψ₃, preΨ₄` as atoms instead does not help either.  What makes it true is
`WeierstrassCurve.C_b_relation`, and the difference of the two sides is *exactly* the cofactor
below times `4b₈ − b₂b₆ + b₄²` — an exact division with integer coefficients, which is why no
characteristic hypothesis, no field and no universal reduction are needed here.  The cofactor was
obtained by dividing the expanded difference by that relation in the variable `b₈`; at `n = 3` the
same recipe gives a 652-term cofactor that also closes, and at `n = 4` one of 7204 terms. -/
lemma hasΦDoubling_two : W.HasΦDoubling 2 := by
  rw [HasΦDoubling, show (2 : ℤ) * 2 = 4 by norm_num, Φ_four, Φ_two, ΨSq_two, Ψ₂Sq, Ψ₃, preΨ₄]
  C_simp
  linear_combination (norm := ring1)
    (
      X * C W.b₆ * C W.b₈ ^ 2 + 5 * X ^ 2 * C W.b₆ ^ 2 * C W.b₈ + 2 * X ^ 2 * C W.b₄ * C W.b₈ ^ 2
        + 4 * X ^ 3 * C W.b₆ ^ 3 + 16 * X ^ 3 * C W.b₄ * C W.b₆ * C W.b₈
        + X ^ 3 * C W.b₂ * C W.b₈ ^ 2 + 4 * X ^ 4 * C W.b₈ ^ 2 + 15 * X ^ 4 * C W.b₄ * C W.b₆ ^ 2
        + 12 * X ^ 4 * C W.b₄ ^ 2 * C W.b₈ + 8 * X ^ 4 * C W.b₂ * C W.b₆ * C W.b₈
        + 38 * X ^ 5 * C W.b₆ * C W.b₈ + 16 * X ^ 5 * C W.b₄ ^ 2 * C W.b₆
        + 7 * X ^ 5 * C W.b₂ * C W.b₆ ^ 2 + 12 * X ^ 5 * C W.b₂ * C W.b₄ * C W.b₈
        + 39 * X ^ 6 * C W.b₆ ^ 2 + 60 * X ^ 6 * C W.b₄ * C W.b₈ + 4 * X ^ 6 * C W.b₄ ^ 3
        + 14 * X ^ 6 * C W.b₂ * C W.b₄ * C W.b₆ + 3 * X ^ 6 * C W.b₂ ^ 2 * C W.b₈
        + 84 * X ^ 7 * C W.b₄ * C W.b₆ + 30 * X ^ 7 * C W.b₂ * C W.b₈
        + 4 * X ^ 7 * C W.b₂ * C W.b₄ ^ 2 + 3 * X ^ 7 * C W.b₂ ^ 2 * C W.b₆ + 72 * X ^ 8 * C W.b₈
        + 28 * X ^ 8 * C W.b₄ ^ 2 + 36 * X ^ 8 * C W.b₂ * C W.b₆ + X ^ 8 * C W.b₂ ^ 2 * C W.b₄
        + 93 * X ^ 9 * C W.b₆ + 16 * X ^ 9 * C W.b₂ * C W.b₄ + 42 * X ^ 10 * C W.b₄
        + X ^ 10 * C W.b₂ ^ 2 + 5 * X ^ 11 * C W.b₂ + 4 * X ^ 12
    ) * W.C_b_relation

end WeierstrassCurve
