/-
Copyright (c) 2026 The Elliptic Curves formalisation contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Elliptic Curves formalisation contributors
-/
import EllipticCurves.Torsion.TwoTorsion
import Mathlib.FieldTheory.Galois.Basic

/-!
# The `2`-torsion field is a finite Galois extension

For an elliptic curve `W` over a field `F` of characteristic `≠ 2`, this file proves that the
`2`-torsion cubic `Ψ₂Sq` is a **separable** polynomial, and draws the two consequences that a
descent argument needs: a splitting field `L` of `Ψ₂Sq` is a **finite Galois** extension of `F`,
and over that `L` the `2`-torsion is full — `#E[2] = 4` and `E[2] ≃+ ZMod 2 × ZMod 2`.

`EllipticCurves.Torsion.TwoTorsion` already proves both conclusions over any field over which
`Ψ₂Sq` splits — `card_torsion_two_of_splits` and `nonempty_torsionTwo_addEquiv_of_splits` — and
the **docstring** of the first says in terms that

> Over a splitting field `L` of `Ψ₂Sq` it holds by construction, but transporting the conclusion
> back down to `F` is a **descent** problem and is not this lemma's business.

A descent needs more than *some* extension over which the conclusion holds: it needs `L / F` to be
**Galois**, because the fixed-field theorem is what carries an invariant object back down to `F`.
That is what this file supplies, and beyond `[W.IsElliptic]` and `L` being a splitting field of
`Ψ₂Sq` — which is what the Galois conclusion is *about* — the only input it takes is
`(2 : F) ≠ 0`, the hypothesis the whole `n = 2` layer already carries.

## The mechanism

`Ψ₂Sq` is Mathlib's `twoTorsionPolynomial`, a cubic with leading coefficient `4` and discriminant
`16Δ`, both nonzero for an elliptic curve away from characteristic `2` — this is exactly the pair
of facts `card_roots_Ψ₂Sq_of_splits` already uses to count its roots. Over a splitting field the
nonvanishing of the discriminant is equivalent to the roots being pairwise distinct
(`Cubic.discr_ne_zero_iff_roots_nodup`), and a polynomial that splits with distinct roots is
separable (`Polynomial.nodup_aroots_iff_of_splits`). Separability is a statement about `Ψ₂Sq` over
`F` alone, so it transfers back: `separable_Ψ₂Sq` below.

Mathlib then supplies the Galois conclusion from separability with nothing further to prove:
`IsGalois.of_separable_splitting_field`, whose separability hypothesis is exactly what
`separable_Ψ₂Sq` provides. ⚠️ **The finiteness is not a consequence of separability.** It is
`Polynomial.IsSplittingField.finiteDimensional`, whose only hypothesis is the splitting-field
instance — it takes no separability at all — which is why `isGalois_of_isSplittingField_Ψ₂Sq`
and `finiteDimensional_of_isSplittingField_Ψ₂Sq` carry different hypotheses below.

## Main statements

**The hypotheses the bullets omit.** Every statement about `L` takes
`[W.Ψ₂Sq.IsSplittingField F L]`. `separable_Ψ₂Sq`, `isGalois_of_isSplittingField_Ψ₂Sq`,
`card_torsion_two_baseChange_of_isSplittingField` and
`nonempty_torsionTwo_addEquiv_baseChange_of_isSplittingField` take `[W.IsElliptic]` and
`(2 : F) ≠ 0`, and the last two take `[DecidableEq L]` as well. ⚠️ `splits_Ψ₂Sq_baseChange` and
`finiteDimensional_of_isSplittingField_Ψ₂Sq` take **neither** `[W.IsElliptic]` nor `(2 : F) ≠ 0`:
they are statements about the splitting field and not about the discriminant, and they hold in
characteristic `2`.

* `WeierstrassCurve.Affine.separable_Ψ₂Sq`: the `2`-torsion cubic is a separable polynomial.
* `WeierstrassCurve.Affine.splits_Ψ₂Sq_baseChange`: the `2`-torsion cubic of the base-changed curve
  `W⁄L` splits.
* `WeierstrassCurve.Affine.isGalois_of_isSplittingField_Ψ₂Sq`: `L / F` is Galois.
* `WeierstrassCurve.Affine.finiteDimensional_of_isSplittingField_Ψ₂Sq`: `L / F` is finite.
* `WeierstrassCurve.Affine.card_torsion_two_baseChange_of_isSplittingField`: `#E[2] = 4` over `L`.
* `WeierstrassCurve.Affine.nonempty_torsionTwo_addEquiv_baseChange_of_isSplittingField`:
  `E[2] ≃+ ZMod 2 × ZMod 2` over `L`.

## What is *not* here

* **The halving-point extension.** `EllipticCurves.Torsion.DoublingSurjective`'s
  `exists_nsmul_two_eq` is the second `[IsAlgClosed F]` input to the `n = 2` pullback-principality
  chain, and adjoining a point `P` with `2 • P = S` is a different extension, generated by a root
  of `Φ₂ - C x₀ · ΨSq₂` rather than of `Ψ₂Sq`. Nothing below says anything about it. ⚠️ **That
  quartic is not separable, so the argument here does not transfer to it by substitution**: over an
  algebraic closure its roots are the `x`-coordinates of the four points `Q` with `2 • Q = S`, and
  `Q` and `-Q` share an `x`-coordinate while `-P = P ⊕ S` because `S` is `2`-torsion — so four
  roots counted with multiplicity sit over at most two distinct values. No declaration below is
  stated in a form that would let it transfer.
* **A discharge of `hprin` over a general field.** `#962` records that gate; this file supplies one
  of its ledger rows and no statement below mentions a divisor, a place or a principal divisor.
* **`n = 3`.** `Ψ₃` is a quartic and not a cubic, so `Cubic.discr_ne_zero_iff_roots_nodup` does
  not reach it; nothing here is stated at a general index and nothing here applies to
  `EllipticCurves.Torsion.ThreeTorsionStructure`.
* **Separability in characteristic `2`.** In characteristic `2` the cubic degenerates —
  `Ψ₂Sq = 4X³ + b₂X² + 2b₄X + b₆` loses its cubic and its linear term — and `separable_Ψ₂Sq` and
  everything drawn from it take `(2 : F) ≠ 0`. Nothing below decides whether the `2`-torsion field
  is separable there, in either direction.

## Non-vacuity

The `Nonvacuity` section certifies over `ℚ`, on `EllipticCurves.Fixture.y2EqX3Add4X`
(`y² = x³ + 4x`, whose cubic is `4X³ + 16X = 4 · X · (X² + 4)`), that the extension this file
produces is a **proper** one: `#E[2] = 2` over `ℚ` and `#E[2] = 4` over the splitting field. A
curve whose cubic already splits over `ℚ` would leave everything green and certify only the case
in which `L` is `F` itself.
-/

open Polynomial

namespace WeierstrassCurve.Affine

variable {F : Type*} [Field F] {W : Affine F}

/-! ## Separability of the `2`-torsion cubic -/

/-- `Ψ₂Sq`'s leading coefficient is `4`, and Mathlib's `WeierstrassCurve.Ψ₂Sq_ne_zero` asks for
`(4 : F) ≠ 0` where this layer carries `(2 : F) ≠ 0`. ⚠️ Duplicated on purpose: every other copy in
the tree — under this name, and under `four_ne_zero` in `EllipticCurves.Torsion.XSupport` — is
itself `private`, so none of them can be cited from here. -/
private lemma four_ne_zero_of_two_ne_zero (h2 : (2 : F) ≠ 0) : (4 : F) ≠ 0 := by
  rw [show (4 : F) = 2 * 2 by norm_num]
  exact mul_ne_zero h2 h2

/-- **The `2`-torsion cubic is separable** for an elliptic curve over a field of characteristic
`≠ 2`.

The two inputs are the ones `card_roots_Ψ₂Sq_of_splits` already uses: the leading coefficient `4`
and the discriminant `16Δ` are both nonzero. Over a splitting field the second is equivalent to
the three roots being pairwise distinct (`Cubic.discr_ne_zero_iff_roots_nodup`), and a polynomial
that splits with no repeated root is separable — a property of `Ψ₂Sq` over `F` itself, by
`Polynomial.nodup_aroots_iff_of_splits`. -/
theorem separable_Ψ₂Sq [W.IsElliptic] (h2 : (2 : F) ≠ 0) : W.Ψ₂Sq.Separable := by
  classical
  have ha : W.twoTorsionPolynomial.a ≠ 0 := W.twoTorsionPolynomial_a_ne_zero h2
  have hd : W.twoTorsionPolynomial.discr ≠ 0 :=
    W.twoTorsionPolynomial_discr_ne_zero_of_isElliptic h2.isUnit
  have hsplits : (W.Ψ₂Sq.map (algebraMap F W.Ψ₂Sq.SplittingField)).Splits :=
    IsSplittingField.splits W.Ψ₂Sq.SplittingField W.Ψ₂Sq
  refine (Polynomial.nodup_aroots_iff_of_splits (K := W.Ψ₂Sq.SplittingField)
    (W.Ψ₂Sq_ne_zero (four_ne_zero_of_two_ne_zero h2)) hsplits).mp ?_
  have hnodup := (Cubic.discr_ne_zero_iff_roots_nodup
    (φ := algebraMap F W.Ψ₂Sq.SplittingField) ha (by rw [← Ψ₂Sq_eq]; exact hsplits)).mp hd
  simpa [Polynomial.aroots, Cubic.roots, Cubic.map_toPoly, Ψ₂Sq_eq] using hnodup

/-! ## A splitting field of the `2`-torsion cubic -/

section SplittingField

variable (W) (L : Type*) [Field L] [Algebra F L] [W.Ψ₂Sq.IsSplittingField F L]

variable {W L} in
/-- A numeral that is nonzero in `F` stays nonzero in a field extension `L`. ⚠️ The general-numeral
form of this is `EllipticCurves.FunctionField.FunctionFieldBaseChange.algebraMap_ofNat_ne_zero`,
which is downstream of `Torsion/` and so cannot be cited from here. -/
private lemma algebraMap_two_ne_zero (h2 : (2 : F) ≠ 0) : (2 : L) ≠ 0 := by
  rw [← map_ofNat (algebraMap F L) 2, ne_eq, map_eq_zero]
  exact h2

/-- **The `2`-torsion cubic of the base-changed curve splits** over a splitting field `L` of
`Ψ₂Sq`.

This is `WeierstrassCurve.map_Ψ₂Sq` — `(W⁄L).Ψ₂Sq` is `W.Ψ₂Sq` mapped along `F → L` — together with
the defining property of `L`. It takes no hypothesis on the characteristic and does not need
`[W.IsElliptic]`. -/
theorem splits_Ψ₂Sq_baseChange : (W⁄L).Ψ₂Sq.Splits := by
  change ((W.map (algebraMap F L)).Ψ₂Sq).Splits
  rw [WeierstrassCurve.map_Ψ₂Sq]
  exact IsSplittingField.splits L W.Ψ₂Sq

/-- **A splitting field of the `2`-torsion cubic is a Galois extension** of `F`, for an elliptic
curve over a field of characteristic `≠ 2`.

⚠️ This is the statement a descent argument consumes, and it is the reason `separable_Ψ₂Sq` is
worth proving: *some* extension over which `#E[2] = 4` is free — `card_torsion_two_of_splits`
already gives it over any splitting field — but a descent needs the fixed-field theorem, which
needs `L / F` Galois. -/
theorem isGalois_of_isSplittingField_Ψ₂Sq [W.IsElliptic] (h2 : (2 : F) ≠ 0) : IsGalois F L :=
  IsGalois.of_separable_splitting_field (p := W.Ψ₂Sq) (separable_Ψ₂Sq h2)

include W in
/-- **A splitting field of the `2`-torsion cubic is finite over `F`.**

Mathlib's `Polynomial.IsSplittingField.finiteDimensional`, recorded here because the finiteness is
the half of *"finite Galois"* that Mathlib's Hilbert 90
(`groupCohomology.isMulCoboundary₁_of_isMulCocycle₁_of_aut_to_units`) takes as a hypothesis, and a
consumer reaching for that theorem should not have to rediscover which of the two lemmas supplies
it. It takes no hypothesis on the characteristic and does not need `[W.IsElliptic]`. -/
theorem finiteDimensional_of_isSplittingField_Ψ₂Sq : FiniteDimensional F L :=
  IsSplittingField.finiteDimensional L W.Ψ₂Sq

/-- **`#E[2] = 4` over a splitting field of the `2`-torsion cubic**, for an elliptic curve over a
field of characteristic `≠ 2`.

`card_torsion_two_of_splits` over `L`, whose splitting hypothesis is discharged by
`splits_Ψ₂Sq_baseChange` rather than by an algebraic closure. -/
theorem card_torsion_two_baseChange_of_isSplittingField [W.IsElliptic] [DecidableEq L]
    (h2 : (2 : F) ≠ 0) : Nat.card ((W⁄L).torsion 2) = 4 := by
  haveI : (W⁄L).IsElliptic := inferInstanceAs (W.map (algebraMap F L)).IsElliptic
  exact card_torsion_two_of_splits (algebraMap_two_ne_zero h2) (splits_Ψ₂Sq_baseChange W L)

/-- **`E[2] ≃+ ZMod 2 × ZMod 2` over a splitting field of the `2`-torsion cubic**, for an elliptic
curve over a field of characteristic `≠ 2`. -/
theorem nonempty_torsionTwo_addEquiv_baseChange_of_isSplittingField [W.IsElliptic] [DecidableEq L]
    (h2 : (2 : F) ≠ 0) : Nonempty (((W⁄L).torsion 2) ≃+ ZMod 2 × ZMod 2) := by
  haveI : (W⁄L).IsElliptic := inferInstanceAs (W.map (algebraMap F L)).IsElliptic
  exact nonempty_torsionTwo_addEquiv_of_splits (algebraMap_two_ne_zero h2)
    (splits_Ψ₂Sq_baseChange W L)

end SplittingField

/-! ## Non-vacuity -/

section Nonvacuity

/-! The certificate curve is the shared `EllipticCurves.Fixture.y2EqX3Add4X` at `R = ℚ`:
`y² = x³ + 4x`, whose `2`-torsion cubic is `4X³ + 16X = 4 · X · (X² + 4)`.  ⚠️ **What this block
tests is that the extension this file produces is a proper one** — over `ℚ` the cubic has the
single root `0`, so `#E[2] = 2`, and over a splitting field of it `#E[2] = 4`.  Substituting a
curve whose cubic already splits over `ℚ` — `EllipticCurves.Fixture.y2EqX3SubX`, say, whose cubic
is `4X³ - 4X` — would leave everything below green and certify only the case in which `L` is `F`
itself, which the `_of_splits` lemmas of `EllipticCurves.Torsion.TwoTorsion` already cover. -/

open EllipticCurves.Fixture

/-- The `2`-torsion cubic of the example curve, factored: `4X³ + 16X = 4 · X · (X² + 4)`. -/
private lemma Ψ₂Sq_y2EqX3Add4X :
    (y2EqX3Add4X ℚ).Ψ₂Sq = C 4 * X * (X ^ 2 + C 4) := by
  simp only [WeierstrassCurve.Ψ₂Sq, WeierstrassCurve.b₂, WeierstrassCurve.b₄,
    WeierstrassCurve.b₆, y2EqX3Add4X]
  norm_num only
  simp only [map_ofNat, Polynomial.C_0]
  ring

/-- **The cubic does not split over `ℚ`**, in the form the root count needs: its only rational root
is `0`, because `x² + 4` is positive. -/
private lemma eval_Ψ₂Sq_y2EqX3Add4X_eq_zero_iff {x : ℚ} :
    (y2EqX3Add4X ℚ).Ψ₂Sq.eval x = 0 ↔ x = 0 := by
  rw [Ψ₂Sq_y2EqX3Add4X]
  simp only [eval_mul, eval_add, eval_pow, eval_C, eval_X]
  constructor
  · intro h
    rcases mul_eq_zero.mp h with h' | h'
    · rcases mul_eq_zero.mp h' with h'' | h''
      · norm_num at h''
      · exact h''
    · nlinarith [sq_nonneg x]
  · rintro rfl
    ring

/-- The example curve has exactly one rational `2`-torsion `x`-coordinate. -/
private lemma card_roots_Ψ₂Sq_y2EqX3Add4X :
    Nat.card {x : ℚ // (y2EqX3Add4X ℚ).Ψ₂Sq.eval x = 0} = 1 := by
  rw [Nat.card_eq_one_iff_unique]
  exact ⟨⟨fun a b => Subtype.ext ((eval_Ψ₂Sq_y2EqX3Add4X_eq_zero_iff.mp a.2).trans
    (eval_Ψ₂Sq_y2EqX3Add4X_eq_zero_iff.mp b.2).symm)⟩,
    ⟨⟨0, eval_Ψ₂Sq_y2EqX3Add4X_eq_zero_iff.mpr rfl⟩⟩⟩

/-- **The `2`-torsion cubic does not split over `ℚ`** for `y² = x³ + 4x`: it would then have three
roots there, and it has one.  So a splitting field of it is a proper extension of `ℚ`. -/
private theorem not_splits_Ψ₂Sq_y2EqX3Add4X : ¬ (y2EqX3Add4X ℚ).Ψ₂Sq.Splits := by
  intro h
  have hthree := card_roots_Ψ₂Sq_of_splits (W := y2EqX3Add4X ℚ) (by norm_num) h
  rw [card_roots_Ψ₂Sq_y2EqX3Add4X] at hthree
  omega

/-- **`#E[2] = 2` over `ℚ`** for `y² = x³ + 4x`: the point at infinity together with the single
rational root `0` of the cubic.  This is the half of the certificate that makes the base change
below say something. -/
private theorem card_torsion_two_y2EqX3Add4X :
    Nat.card ((y2EqX3Add4X ℚ).torsion 2) = 2 := by
  haveI := (y2EqX3Add4X ℚ).finite_roots_Ψ₂Sq (by norm_num)
  rw [Nat.card_congr (torsionTwoEquiv (W := y2EqX3Add4X ℚ) (by norm_num)), Finite.card_option,
    card_roots_Ψ₂Sq_y2EqX3Add4X]

private noncomputable instance : DecidableEq (y2EqX3Add4X ℚ).Ψ₂Sq.SplittingField :=
  Classical.decEq _

/-- **The splitting field of the cubic is a Galois extension of `ℚ`**, with no hypothesis at all,
for `y² = x³ + 4x`. -/
private theorem isGalois_splittingField_y2EqX3Add4X :
    IsGalois ℚ (y2EqX3Add4X ℚ).Ψ₂Sq.SplittingField :=
  isGalois_of_isSplittingField_Ψ₂Sq (y2EqX3Add4X ℚ) _ (by norm_num)

/-- **`#E[2] = 4` over the splitting field**, with no hypothesis at all, for `y² = x³ + 4x` — where
`card_torsion_two_y2EqX3Add4X` gives `2` over `ℚ`.  The base change is therefore not the identity
and the extension this file produces is proper. -/
private theorem card_torsion_two_baseChange_y2EqX3Add4X :
    Nat.card (((y2EqX3Add4X ℚ)⁄(y2EqX3Add4X ℚ).Ψ₂Sq.SplittingField).torsion 2) = 4 :=
  card_torsion_two_baseChange_of_isSplittingField (y2EqX3Add4X ℚ) _ (by norm_num)

end Nonvacuity

end WeierstrassCurve.Affine
